In [1]:
from tqsdk.ta import MA, EMA

在使用天勤量化之前，默认您已经知晓并同意以下免责条款，如果不同意请立即停止使用：https://www.shinnytech.com/blog/disclaimer/

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
import warnings
warnings.simplefilter(action='ignore',category=pd.errors.PerformanceWarning)

In [39]:
%run CommonUtil.ipynb

# 参数

In [3]:
# 需要封装 传入函数
# 对均线的短中长周期设参数
# s1,s2,s3 = 4, 8, 24
# s1,s2,s3 = 8, 16, 48
# s1,s2,s3 = 12, 24, 72
# s1,s2,s3 = 20,40,120
s0=3
# s1,s2,s3 = 8,16,32
# m1,m2,m3 = 32,64,128
# l1,l2,l3 = 128,256,512
# s1,s2,s3 = 8,13,21
# m1,m2,m3 = 21,34,55
# l1,l2,l3 = 55,89,144
# 8,16,32,64,128,256,512

s1,s2,s3 = 6,12,24
m1,m2,m3 = 24,48,96
l1,l2,l3 = 96,192,384


kls=0.2
klm=1
kls=1.2
zig1=0.2/100
zig2=0.4/100
zig3=0.6/100
zig4=0.9/100
yc_vol_ratio=2 # 异常vol ratio

# 对长上影/下影分类  ma_body 的2倍以上就是
ups,lows = 2,2
#回踩反抽
huicai_range = 0.5
# 对vol 最高第二高进行定位
vs=13  #量的变化更快，采用更短的周期
vm=46
vl=150
vThresh = 0.15

# 用于计算买卖压的
body_thresh=0.5
bsp_thresh1 = 1.4
bsp_thresh2 = 2.1
bsp_n = 20

# 计算n周期ma_body
n_ma_body=20
# 和高点比较（千分之）
peak_var_pct = 1.5 
cs=20 
cm=46
cl=112 #1 Day

# 靠拢的参数: ma_body的倍数
# ma1-3
kl_s_ratio = 1
# ma3-5
kl_m_ratio = 1.5

# read data

In [12]:
# raw = pd.read_csv('./data/ic2509_250906.csv')
raw = pd.read_csv('./data/ic2509_250912.csv')

In [13]:
klines=raw.loc[:,['time','open','high','low','close','volume']]

# calculate

In [105]:
%run CommonUtil.ipynb

In [106]:
# %time 
start = datetime.datetime.now()
base = calc_base_data(klines)
datetime.datetime.now()-start
# base=calc_base_data(klines)

ZeroDivisionError: float division by zero

In [95]:
base1=base.set_index('time')

In [96]:
base1.loc['2025/09/04-12:35':'2025/09/08-10:35',:][['ma_category_s','close','ma1','ma2','ma3','mv_stage','peak_2nd1']]
# ma_stage
# 空头 1
# 空头震荡 2
# 空转多 3
# 多头 4
# 多头震荡 5
# 多转空 6

,ma_category_s,close,ma1,ma2,ma3,mv_stage,peak_2nd1
time,,,,,,,
2025/09/04-13:05,1.0,6667.8,6686.510935,6702.545038,6729.602461,2,6777.4
2025/09/04-13:10,1.0,6703.0,6691.222096,6702.615032,6727.474264,2,6777.4
2025/09/04-13:15,1.0,6711.0,6696.872926,6703.905027,6726.156323,2,6729.8
2025/09/04-13:20,1.0,6694.2,6696.109233,6702.411946,6723.599817,2,6729.8
2025/09/04-13:25,1.0,6674.0,6689.792309,6698.040877,6719.631832,2,6729.8
2025/09/04-13:30,1.0,6671.8,6684.651649,6694.003819,6715.805285,2,6729.8
2025/09/04-13:35,1.0,6657.6,6676.922607,6688.403232,6711.148863,1,6729.8
2025/09/04-13:40,1.0,6650.4,6669.344719,6682.556581,6706.288954,1,6729.8
2025/09/04-13:45,1.0,6654.0,6664.960514,6678.163261,6702.105837,1,6729.8
2025/09/04-13:50,1.0,6643.0,6658.686081,6672.753528,6697.377370,1,6729.8
2025/09/04-13:55,1.0,6668.0,6661.347201,6672.022216,6695.027181,1,6711.0
2025/09/04-14:00,1.0,6648.0,6657.533715,6668.326491,6691.265006,1,6711.0
2025/09/04-14:05,1.0,6623.4,6647.781225,6661.414723,6685.835806,1,6711.0
2025/09/04-14:10,1.0,6622.6,6640.586589,6655.443227,6680.776941,1,6711.0
2025/09/04-14:15,1.0,6599.4,6628.818992,6646.821192,6674.266786,1,6711.0
2025/09/04-14:20,1.0,6599.8,6620.527852,6639.587163,6668.309443,1,6711.0
2025/09/04-14:25,1.0,6589.2,6611.577037,6631.835291,6661.980688,1,6711.0
2025/09/04-14:30,1.0,6590.6,6605.583598,6625.491400,6656.270233,1,6711.0
2025/09/04-14:35,1.0,6557.2,6591.759713,6614.985031,6648.344614,1,6711.0
2025/09/04-14:40,1.0,6594.8,6592.628366,6611.879642,6644.061045,1,6711.0
2025/09/04-14:45,1.0,6628.4,6602.848833,6614.421235,6642.808161,2,6711.0
2025/09/04-14:50,1.0,6633.2,6611.520595,6617.310276,6642.039508,2,6711.0
2025/09/04-14:55,1.0,6635.8,6618.457568,6620.154849,6641.540348,2,6711.0
2025/09/04-15:00,2.0,6647.0,6626.612548,6624.284872,6641.977120,2,6711.0
2025/09/05-09:35,2.0,6651.8,6633.808963,6628.517969,6642.762950,3,6711.0
2025/09/05-09:40,2.0,6672.8,6644.949259,6635.330589,6645.165914,3,6711.0
2025/09/05-09:45,3.0,6665.8,6650.906614,6640.018191,6646.816641,3,6711.0
2025/09/05-09:50,3.0,6701.0,6665.219010,6649.400007,6651.151310,3,6711.0
2025/09/05-09:55,4.0,6718.6,6680.470721,6660.046160,6656.547205,3,6711.0
2025/09/05-10:00,4.0,6730.0,6694.621944,6670.808289,6662.423429,3,6711.0
2025/09/05-10:05,4.0,6732.8,6705.529960,6680.345476,6668.053554,3,6668.0
2025/09/05-10:10,4.0,6714.0,6707.949971,6685.523095,6671.729270,3,6668.0
2025/09/05-10:15,4.0,6715.6,6710.135694,6690.150311,6675.238928,3,6668.0
2025/09/05-10:20,4.0,6715.4,6711.639781,6694.034878,6678.451814,3,6668.0
2025/09/05-10:25,4.0,6731.0,6717.171272,6699.721820,6682.655669,3,6668.0
2025/09/05-10:30,4.0,6745.0,6725.122337,6706.687694,6687.643215,3,6668.0
2025/09/05-10:35,4.0,6752.8,6733.030241,6713.781895,6692.855758,3,6668.0
2025/09/05-10:40,4.0,6747.6,6737.193029,6718.984680,6697.235298,2,6668.0
2025/09/05-10:45,4.0,6763.0,6744.566449,6725.756268,6702.496474,2,6668.0
2025/09/05-10:50,4.0,6767.4,6751.090321,6732.162996,6707.688756,2,6668.0
2025/09/05-10:55,4.0,6777.8,6758.721658,6739.184074,6713.297655,2,6732.8
2025/09/05-11:00,4.0,6763.8,6760.172613,6742.971139,6717.337843,2,6732.8
2025/09/05-11:05,4.0,6776.0,6764.694723,6748.052502,6722.030816,1,6732.8
2025/09/05-11:10,4.0,6785.2,6770.553374,6753.767502,6727.084350,1,6777.8
2025/09/05-11:15,4.0,6780.8,6773.480981,6757.926348,6731.381602,1,6777.8
2025/09/05-11:20,4.0,6757.6,6768.943558,6757.876140,6733.479074,1,6777.8
2025/09/05-11:25,4.0,6758.4,6765.931113,6757.956734,6735.472748,1,6777.8
2025/09/05-11:30,4.0,6776.2,6768.865081,6760.763391,6738.730928,1,6777.8
2025/09/05-13:05,4.0,6765.4,6767.875058,6761.476715,6740.864454,1,6777.8
2025/09/05-13:10,4.0,6768.8,6768.139327,6762.603374,6743.099298,1,6777.8
2025/09/05-13:15,4.0,6770.0,6768.670948,6763.741317,6745.251354,1,6777.8
2025/09/05-13:20,4.0,6768.0,6768.479248,6764.396499,6747.071246,1,6777.8
2025/09/05-13:25,4.0,6767.0,6768.056606,6764.797037,6748.665546,1,6777.8
2025/09/05-13:30,4.0,6786.0,6773.183290,6768.059032,6751.652302,1,6777.8
2025/09/05-13:35,4.0,6794.0,6779.130921,6772.049950,6755.040118,1,6777.8
2025/09/05-13:40,4.0,6800.6,6785.264944,6776.442265,6758.684909,1,6777.8
2025/09/05-13:45,4.0,6796.0,6788.332103,6779.451148,6761.670116,1,6777.8
2025/09/05-13:50,4.0,6813.2,6795.437216,6784.643279,6765.792507,1,6777.8
2025/09/05-13:55,4.0,6818.8,6802.112297,6789.898159,6770.033106,1,6777.8
2025/09/05-14:00,4.0,6834.8,6811.451641,6796.806134,6775.214458,1,6777.8
2025/09/05-14:05,4.0,6850.6,6822.636886,6805.082114,6781.245301,1,6777.8
2025/09/05-14:10,4.0,6854.8,6831.826347,6812.731019,6787.129677,1,6777.8
2025/09/05-14:15,4.0,6856.6,6838.904534,6819.480093,6792.687303,1,6777.8
2025/09/05-14:20,4.0,6865.6,6846.531810,6826.575464,6798.520319,1,6777.8
2025/09/05-14:25,4.0,6875.2,6854.722721,6834.056161,6804.654693,1,6777.8
2025/09/05-14:30,4.0,6880.8,6862.173372,6841.247521,6810.746318,2,6777.8
2025/09/05-14:35,4.0,6878.8,6866.923837,6847.024826,6816.190612,2,6777.8
2025/09/05-14:40,4.0,6901.2,6876.717027,6855.359468,6822.991363,2,6785.2
2025/09/05-14:45,4.0,6900.4,6883.483591,6862.288781,6829.184054,2,6785.2
2025/09/05-14:50,4.0,6894.2,6886.545422,6867.198199,6834.385330,2,6785.2
2025/09/05-14:55,4.0,6883.8,6885.761016,6869.752322,6838.338503,2,6785.2
2025/09/05-15:00,4.0,6898.6,6889.429297,6874.190426,6843.159423,3,6785.2
2025/09/08-09:35,4.0,6899.6,6892.335212,6878.099592,6847.674669,3,6785.2
2025/09/08-09:40,4.0,6922.4,6900.925151,6884.915039,6853.652696,3,6785.2
2025/09/08-09:45,4.0,6927.4,6908.489394,6891.451187,6859.552480,3,6901.2
2025/09/08-09:50,4.0,6894.6,6904.520996,6891.935620,6862.356282,3,6901.2
2025/09/08-09:55,4.0,6924.2,6910.143568,6896.899370,6867.303779,3,6901.2
2025/09/08-10:00,4.0,6931.0,6916.102549,6902.145621,6872.399477,3,6927.4
2025/09/08-10:05,4.0,6917.0,6916.358963,6904.430910,6875.967519,3,6927.4
2025/09/08-10:10,4.0,6926.0,6919.113545,6907.749232,6879.970117,3,6927.4
2025/09/08-10:15,4.0,6911.4,6916.909675,6908.310888,6882.484508,3,6927.4
2025/09/08-10:20,4.0,6890.2,6909.278339,6905.524598,6883.101747,3,6927.4
2025/09/08-10:25,4.0,6885.2,6902.398814,6902.397737,6883.269607,3,6927.4
2025/09/08-10:30,5.0,6878.8,6895.656296,6898.767316,6882.912039,3,6927.4
2025/09/08-10:35,5.0,6887.2,6893.240211,6896.987729,6883.255076,3,6927.4

# 分析

## 分析peak

In [97]:
base1.loc['2025/09/08-10:30':'2025/09/11-10:30',:][['close1', 'peak1',
       'valley1', 'p_v_value1','peak_2nd1', 'p_v_value_bw1', 'p_pos1', 'v_pos1',
       'z_pos1', 'dw_pct_last1', 'up_pct_last1', 'z_pct_prev1',
       'z_len_prev1', 'up_pct_avg1', 'dw_pct_avg1', 'z_pct_curr1',
       'z_pct_avg1', 'up_pct_avg_k1', 'dw_pct_avg_k1', 'z_len_curr1',
       'z_len_full1', 'z_pct_curr_avg_k1', 'z_pct_prev_avg_k1',
       'z_pct_avg_k1', 'v_pct_curr1', 'p_pct_curr1', 'valley_last1',
       'peak_last1', 'v_pct_bw1', 'p_pct_bw1', 'z_pct_curr_full1',
       'z_pct_curr_next1', 'zig_flag1', 'zig_index1']]

,close1,peak1,valley1,p_v_value1,peak_2nd1,p_v_value_bw1,p_pos1,v_pos1,z_pos1,dw_pct_last1,up_pct_last1,z_pct_prev1,z_len_prev1,up_pct_avg1,dw_pct_avg1,z_pct_curr1,z_pct_avg1,up_pct_avg_k1,dw_pct_avg_k1,z_len_curr1,z_len_full1,z_pct_curr_avg_k1,z_pct_prev_avg_k1,z_pct_avg_k1,v_pct_curr1,p_pct_curr1,valley_last1,peak_last1,v_pct_bw1,p_pct_bw1,z_pct_curr_full1,z_pct_curr_next1,zig_flag1,zig_index1
time,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025/09/08-10:30,6878.8,6931.0,6894.6,6931.0,6927.4,6842.4,6,8,6,0.0000,5.2795,5.2795,0.0,7.509441,-6.197649,-7.531381,-6.197649,1.328321,-0.728261,6.0,11.0,-1.255230,inf,0.970686,-2.291649,-7.531381,6883.8,6927.4,-7.571143,-12.783148,-12.783148,-6.319434,0,272
2025/09/08-10:35,6887.2,6931.0,6894.6,6931.0,6927.4,6842.4,7,9,7,0.0000,5.2795,5.2795,0.0,7.509441,-6.197649,-6.319434,-6.197649,1.328321,-0.728261,7.0,11.0,-0.902776,inf,0.970686,-1.073304,-6.319434,6883.8,6927.4,-7.571143,-12.783148,-12.783148,-10.301544,0,272
2025/09/08-10:40,6859.6,6931.0,6894.6,6931.0,6927.4,6842.4,8,10,8,0.0000,5.2795,5.2795,0.0,7.509441,-6.197649,-10.301544,-6.197649,1.328321,-0.728261,8.0,11.0,-1.287693,inf,0.970686,-5.076437,-10.301544,6883.8,6927.4,-7.571143,-12.783148,-12.783148,-10.734382,0,272
2025/09/08-10:45,6856.6,6931.0,6894.6,6931.0,6927.4,6842.4,9,11,9,0.0000,5.2795,5.2795,0.0,7.509441,-6.197649,-10.734382,-6.197649,1.328321,-0.728261,9.0,11.0,-1.192709,inf,0.970686,-5.511560,-10.734382,6883.8,6927.4,-7.571143,-12.783148,-12.783148,-12.090607,0,272
2025/09/08-10:50,6847.2,6931.0,6894.6,6931.0,6927.4,6842.4,10,12,10,0.0000,5.2795,5.2795,0.0,7.509441,-6.197649,-12.090607,-6.197649,1.328321,-0.728261,10.0,11.0,-1.209061,inf,0.970686,-6.874946,-12.090607,6883.8,6927.4,-7.571143,-12.783148,-12.783148,-12.783148,0,272
2025/09/08-10:55,6842.4,6931.0,6842.4,6842.4,6927.4,6842.4,11,0,0,-12.7831,0.0000,-12.7831,11.0,7.509441,-6.197649,-12.783148,7.509441,1.328321,-0.728261,11.0,11.0,-1.162104,-1.162100,0.970686,-7.571143,-12.783148,6894.6,6927.4,0.000000,-12.783148,4.004443,4.004443,1,273
2025/09/08-11:00,6869.8,6869.8,6842.4,6869.8,6931.0,6869.8,0,1,0,0.0000,4.0044,4.0044,1.0,7.509441,-6.197649,4.004443,-6.197649,1.328321,-0.728261,1.0,1.0,4.004443,4.004400,0.970686,4.004443,-8.829895,6894.6,6931.0,4.004443,0.000000,-2.299921,-2.299921,1,274
2025/09/08-11:05,6854.0,6869.8,6854.0,6854.0,6931.0,6854.0,1,0,0,-2.2999,0.0000,-2.2999,1.0,7.509441,-6.197649,-2.299921,7.509441,1.328321,-0.728261,1.0,1.0,-2.299921,-2.299900,0.970686,NaN,-2.299921,6842.4,6931.0,0.000000,-2.299921,13.481179,0.992121,1,275
2025/09/08-11:10,6860.8,6869.8,6854.0,6854.0,6931.0,6946.4,2,1,1,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,0.992121,7.509441,1.328321,-0.728261,1.0,24.0,0.992121,-inf,0.970686,0.992121,-1.310082,6842.4,6931.0,13.481179,11.150252,13.481179,3.880945,0,275
2025/09/08-11:15,6880.6,6869.8,6854.0,6854.0,6931.0,6946.4,3,2,2,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,3.880945,7.509441,1.328321,-0.728261,2.0,24.0,1.940473,-inf,0.970686,3.880945,1.572098,6842.4,6931.0,13.481179,11.150252,13.481179,3.501605,0,275
2025/09/08-11:20,6878.0,6869.8,6854.0,6854.0,6931.0,6946.4,4,3,3,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,3.501605,7.509441,1.328321,-0.728261,3.0,24.0,1.167202,-inf,0.970686,3.501605,1.193630,6842.4,6931.0,13.481179,11.150252,13.481179,4.873067,0,275
2025/09/08-11:25,6887.4,6869.8,6854.0,6854.0,6931.0,6946.4,5,4,4,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,4.873067,7.509441,1.328321,-0.728261,4.0,24.0,1.218267,-inf,0.970686,4.873067,2.561938,6842.4,6931.0,13.481179,11.150252,13.481179,4.377006,0,275
2025/09/08-11:30,6884.0,6869.8,6854.0,6854.0,6931.0,6946.4,6,5,5,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,4.377006,7.509441,1.328321,-0.728261,5.0,24.0,0.875401,-inf,0.970686,4.377006,2.067018,6842.4,6931.0,13.481179,11.150252,13.481179,5.252407,0,275
2025/09/08-13:05,6890.0,6869.8,6854.0,6854.0,6931.0,6946.4,7,6,6,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,5.252407,7.509441,1.328321,-0.728261,6.0,24.0,0.875401,-inf,0.970686,5.252407,2.940406,6842.4,6931.0,13.481179,11.150252,13.481179,5.660928,0,275
2025/09/08-13:10,6892.8,6869.8,6854.0,6854.0,6931.0,6946.4,8,7,7,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,5.660928,7.509441,1.328321,-0.728261,7.0,24.0,0.808704,-inf,0.970686,5.660928,3.347987,6842.4,6931.0,13.481179,11.150252,13.481179,5.631748,0,275
2025/09/08-13:15,6892.6,6869.8,6854.0,6854.0,6931.0,6946.4,9,8,8,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,5.631748,7.509441,1.328321,-0.728261,8.0,24.0,0.703968,-inf,0.970686,5.631748,3.318874,6842.4,6931.0,13.481179,11.150252,13.481179,5.602568,0,275
2025/09/08-13:20,6892.4,6869.8,6854.0,6854.0,6931.0,6946.4,10,9,9,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,5.602568,7.509441,1.328321,-0.728261,9.0,24.0,0.622508,-inf,0.970686,5.602568,3.289761,6842.4,6931.0,13.481179,11.150252,13.481179,4.114386,0,275
2025/09/08-13:25,6882.2,6869.8,6854.0,6854.0,6931.0,6946.4,11,10,10,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,4.114386,7.509441,1.328321,-0.728261,10.0,24.0,0.411439,-inf,0.970686,4.114386,1.805002,6842.4,6931.0,13.481179,11.150252,13.481179,4.085206,0,275
2025/09/08-13:30,6882.0,6869.8,6854.0,6854.0,6931.0,6946.4,12,11,11,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,4.085206,7.509441,1.328321,-0.728261,11.0,24.0,0.371382,-inf,0.970686,4.085206,1.775889,6842.4,6931.0,13.481179,11.150252,13.481179,4.464546,0,275
2025/09/08-13:35,6884.6,6869.8,6854.0,6854.0,6931.0,6946.4,13,12,12,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,4.464546,7.509441,1.328321,-0.728261,12.0,24.0,0.372046,-inf,0.970686,4.464546,2.154357,6842.4,6931.0,13.481179,11.150252,13.481179,4.347826,0,275
2025/09/08-13:40,6883.8,6869.8,6854.0,6854.0,6931.0,6946.4,14,13,13,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,4.347826,7.509441,1.328321,-0.728261,13.0,24.0,0.334448,-inf,0.970686,4.347826,2.037905,6842.4,6931.0,13.481179,11.150252,13.481179,5.631748,0,275
2025/09/08-13:45,6892.6,6869.8,6854.0,6854.0,6931.0,6946.4,15,14,14,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,5.631748,7.509441,1.328321,-0.728261,14.0,24.0,0.402268,-inf,0.970686,5.631748,3.318874,6842.4,6931.0,13.481179,11.150252,13.481179,5.981908,0,275
2025/09/08-13:50,6895.0,6869.8,6854.0,6854.0,6931.0,6946.4,16,15,15,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,5.981908,7.509441,1.328321,-0.728261,15.0,24.0,0.398794,-inf,0.970686,5.981908,3.668229,6842.4,6931.0,13.481179,11.150252,13.481179,7.353370,0,275
2025/09/08-13:55,6904.4,6869.8,6854.0,6854.0,6931.0,6946.4,17,16,16,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,7.353370,7.509441,1.328321,-0.728261,16.0,24.0,0.459586,-inf,0.970686,7.353370,5.036537,6842.4,6931.0,13.481179,11.150252,13.481179,8.578932,0,275
2025/09/08-14:00,6912.8,6869.8,6854.0,6854.0,6931.0,6946.4,18,17,17,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,8.578932,7.509441,1.328321,-0.728261,17.0,24.0,0.504643,-inf,0.970686,8.578932,6.259280,6842.4,6931.0,13.481179,11.150252,13.481179,7.411730,0,275
2025/09/08-14:05,6904.8,6869.8,6854.0,6854.0,6931.0,6946.4,19,18,18,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,7.411730,7.509441,1.328321,-0.728261,18.0,24.0,0.411763,-inf,0.970686,7.411730,5.094763,6842.4,6931.0,13.481179,11.150252,13.481179,6.653049,0,275
2025/09/08-14:10,6899.6,6869.8,6854.0,6854.0,6931.0,6946.4,20,19,19,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,6.653049,7.509441,1.328321,-0.728261,19.0,24.0,0.350160,-inf,0.970686,6.653049,4.337826,6842.4,6931.0,13.481179,11.150252,13.481179,8.462212,0,275
2025/09/08-14:15,6912.0,6869.8,6854.0,6854.0,6931.0,6946.4,21,20,20,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,8.462212,7.509441,1.328321,-0.728261,20.0,24.0,0.423111,-inf,0.970686,8.462212,6.142828,6842.4,6931.0,13.481179,11.150252,13.481179,8.783192,0,275
2025/09/08-14:20,6914.2,6869.8,6854.0,6854.0,6931.0,6946.4,22,21,21,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,8.783192,7.509441,1.328321,-0.728261,21.0,24.0,0.418247,-inf,0.970686,8.783192,6.463070,6842.4,6931.0,13.481179,11.150252,13.481179,9.571053,0,275
2025/09/08-14:25,6919.6,6869.8,6854.0,6854.0,6931.0,6946.4,23,22,22,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,9.571053,7.509441,1.328321,-0.728261,22.0,24.0,0.435048,-inf,0.970686,9.571053,7.249119,6842.4,6931.0,13.481179,11.150252,13.481179,9.220893,0,275
2025/09/08-14:30,6917.2,6869.8,6854.0,6854.0,6931.0,6946.4,24,23,23,-2.2999,0.0000,-2.2999,0.0,7.509441,-6.197649,9.220893,7.509441,1.328321,-0.728261,23.0,24.0,0.400908,-inf,0.970686,9.220893,6.899764,6842.4,6931.0,13.481179,11.150252,13.481179,13.481179,0,275
2025/09/08-14:35,6946.4,6946.4,6854.0,6946.4,6869.8,6946.4,0,24,0,0.0000,13.4812,13.4812,24.0,7.509441,-6.197649,13.481179,-6.197649,1.328321,-0.728261,24.0,24.0,0.561716,0.561717,0.970686,13.481179,11.150252,6842.4,6869.8,13.481179,0.000000,-7.687435,-0.892549,1,276
2025/09/08-14:40,6940.2,6946.4,6854.0,6946.4,6869.8,6893.0,1,25,1,0.0000,13.4812,13.4812,0.0,7.509441,-6.197649,-0.892549,-6.197649,1.328321,-0.728261,1.0,6.0,-0.892549,inf,0.970686,12.576598,-0.892549,6842.4,6869.8,5.690108,-7.687435,-7.687435,-1.324427,0,276
2025/09/08-14:45,6937.2,6946.4,6854.0,6946.4,6869.8,6893.0,2,26,2,0.0000,13.4812,13.4812,0.0,7.509441,-6.197649,-1.324427,-6.197649,1.328321,-0.728261,2.0,6.0,-0.662214,inf,0.970686,12.138897,-1.324427,6842.4,6869.8,5.690108,-7.687435,-7.687435,-1.641138,0,276
2025/09/08-14:50,6935.0,6946.4,6854.0,6946.4,6869.8,6893.0,3,27,3,0.0000,13.4812,13.4812,0.0,7.509441,-6.197649,-1.641138,-6.197649,1.328321,-0.728261,3.0,6.0,-0.547046,inf,0.970686,11.817917,-1.641138,6842.4,6869.8,5.690108,-7.687435,-7.687435,-2.677646,0,276
2025/09/08-14:55,6927.8,6946.4,6854.0,6946.4,6869.8,6893.0,4,28,4,0.0000,13.4812,13.4812,0.0,7.509441,-6.197649,-2.677646,-6.197649,1.328321,-0.728261,4.0,6.0,-0.669411,inf,0.970686,10.767435,-2.677646,6842.4,6869.8,5.690108,-7.687435,-7.687435,-3.685362,0,276
2025/09/08-15:00,6920.8,6946.4,6854.0,6946.4,6869.8,6893.0,5,29,5,0.0000,13.4812,13.4812,0.0,7.509441,-6.197649,-3.685362,-6.197649,1.328321,-0.728261,5.0,6.0,-0.737072,inf,0.970686,9.746134,-3.685362,6842.4,6869.8,5.690108,-7.687435,-7.687435,-7.687435,0,276
2025/09/09-09:35,6893.0,6946.4,6893.0,6893.0,6869.8,6893.0,6,0,0,-7.6874,0.0000,-7.6874,6.0,7.509441,-6.197649,-7.687435,7.509441,1.328321,-0.728261,6.0,6.0,-1.281239,-1.281233,0.970686,5.690108,-7.687435,6854.0,6869.8,0.000000,-7.687435,7.137676,0.348179,1,277
2025/09/09-09:40,6895.4,6946.4,6893.0,6893.0,6869.8,6942.2,7,1,1,-7.6874,0.0000,-7.6874,0.0,7.509441,-6.197649,0.348179,7.509441,1.328321,-0.728261,1.0,8.0,0.348179,-inf,0.970686,0.348179,-7.341933,6854.0,6869.8,7.137676,-0.604630,7.137676,3.452778,0,277
2025/09/09-09:45,6916.8,6946.4,6893.0,6893.0,6869.8,6942.2,8,2,2,-7.6874,0.0000,-7.6874,0.0,7.509441,-6.197649,3.452778,7.509441,1.328321,-0.728261,2.0,8.0,1.726389,-inf,0.970686,3.452778,-4.261200,6854.0,6869.8,7.137676,-0.604630,7.137676,4.178152,0,277
2025/09/09-09:50,6921.8,6946.4,6893.0,6893.0,6869.8,6942.2,9,3,3,-7.6874,0.0000,-7.6874,0.0,7.509441,-6.197649,4.178152,7.509441,1.328321,-0.728261,3.0,8.0,1.392717,-inf,0.970686,4.178152,-3.541403,6854.0,6869.8,7.137676,-0.604630,7.137676,4.700421,0,277
2025/09/09-09:55,6925.4,6946.4,6893.0,6893.0,6869.8,6942.2,10,4,4,-7.6874,0.0000,-7.6874,0.0,7.509441,-6.197649,4.700421,7.509441,1.328321,-0.728261,4.0,8.0,1.175105,-inf,0.970686,4.700421,-3.023149,6854.0,6869.8,7.137676,-0.604630,7.137676,5.948063,0,277
2025/09/09-10:00,6934.0,6946.4,6893.0,6893.0,6869.8,6942.2,11,5,5,-7.6874,0.0000,-7.6874,0.0,7.509441,-6.197649,5.948063,7.509441,1.328321,-0.728261,5.0,8.0,1.189613,-inf,0.970686,5.948063,-1.785097,6854.0,6869.8,7.137676,-0.604630,7.137676,5.077615,0,277
2025/09/09-10:05,6928.0,6946.4,6893.0,6893.0,6869.8,6942.2,12,6,6,-7.6874,0.0000,-7.6874,0.0,7.509441,-6.197649,5.077615,7.509441,1.328321,-0.728261,6.0,8.0,0.846269,-inf,0.970686,5.077615,-2.648854,6854.0,6869.8,7.137676,-0.604630,7.137676,5.802989,0,277
2025/09/09-10:10,6933.0,6946.4,6893.0,6893.0,6869.8,6942.2,13,7,7,-7.6874,0.0000,-7.6874,0.0,7.509441,-6.197649,5.802989,7.509441,1.328321,-0.728261,7.0,8.0,0.828998,-inf,0.970686,5.802989,-1.929057,6854.0,6869.8,7.137676,-0.604630,7.137676,7.137676,0,277
2025/09/09-10:15,6942.2,6942.2,6893.0,6942.2,6946.4,6942.2,0,8,0,0.0000,7.1377,7.1377,8.0,7.509441,-6.197649,7.137676,-6.197649,1.328321,-0.728261,8.0,8.0,0.892209,0.892212,0.970686,7.137676,-0.604630,6854.0,6946.4,7.137676,0.000000,-12.762525,-2.189508,1,278
2025/09/09-10:20,6927.0,6942.2,6893.0,6942.2,6946.4,6853.6,1,9,1,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-2.189508,-6.197649,1.328321,-0.728261,1.0,20.0,-2.189508,inf,0.970686,4.932540,-2.189508,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-0.979517,0,278
2025/09/09-10:25,6935.4,6942.2,6893.0,6942.2,6946.4,6853.6,2,10,2,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-0.979517,-6.197649,1.328321,-0.728261,2.0,20.0,-0.489758,inf,0.970686,6.151168,-0.979517,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-1.901415,0,278
2025/09/09-10:30,6929.0,6942.2,6893.0,6942.2,6946.4,6853.6,3,11,3,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-1.901415,-6.197649,1.328321,-0.728261,3.0,20.0,-0.633805,inf,0.970686,5.222690,-1.901415,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-1.440466,0,278
2025/09/09-10:35,6932.2,6942.2,6893.0,6942.2,6946.4,6853.6,4,12,4,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-1.440466,-6.197649,1.328321,-0.728261,4.0,20.0,-0.360116,inf,0.970686,5.686929,-1.440466,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-2.218317,0,278
2025/09/09-10:40,6926.8,6942.2,6893.0,6942.2,6946.4,6853.6,5,13,5,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-2.218317,-6.197649,1.328321,-0.728261,5.0,20.0,-0.443663,inf,0.970686,4.903525,-2.218317,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-1.123563,0,278
2025/09/09-10:45,6934.4,6942.2,6893.0,6942.2,6946.4,6853.6,6,14,6,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-1.123563,-6.197649,1.328321,-0.728261,6.0,20.0,-0.187261,inf,0.970686,6.006093,-1.123563,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-0.950707,0,278
2025/09/09-10:50,6935.6,6942.2,6893.0,6942.2,6946.4,6853.6,7,15,7,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-0.950707,-6.197649,1.328321,-0.728261,7.0,20.0,-0.135815,inf,0.970686,6.180183,-0.950707,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-3.197834,0,278
2025/09/09-10:55,6920.0,6942.2,6893.0,6942.2,6946.4,6853.6,8,16,8,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-3.197834,-6.197649,1.328321,-0.728261,8.0,20.0,-0.399729,inf,0.970686,3.917017,-3.197834,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-1.613321,0,278
2025/09/09-11:00,6931.0,6942.2,6893.0,6942.2,6946.4,6853.6,9,17,9,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-1.613321,-6.197649,1.328321,-0.728261,9.0,20.0,-0.179258,inf,0.970686,5.512839,-1.613321,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-2.794503,0,278
2025/09/09-11:05,6922.8,6942.2,6893.0,6942.2,6946.4,6853.6,10,18,10,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-2.794503,-6.197649,1.328321,-0.728261,10.0,20.0,-0.279450,inf,0.970686,4.323226,-2.794503,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-4.580680,0,278
2025/09/09-11:10,6910.4,6942.2,6893.0,6942.2,6946.4,6853.6,11,19,11,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-4.580680,-6.197649,1.328321,-0.728261,11.0,20.0,-0.416425,inf,0.970686,2.524300,-4.580680,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-4.868774,0,278
2025/09/09-11:15,6908.4,6942.2,6893.0,6942.2,6946.4,6853.6,12,20,12,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-4.868774,-6.197649,1.328321,-0.728261,12.0,20.0,-0.405731,inf,0.970686,2.234151,-4.868774,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-5.531388,0,278
2025/09/09-11:20,6903.8,6942.2,6893.0,6942.2,6946.4,6853.6,13,21,13,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-5.531388,-6.197649,1.328321,-0.728261,13.0,20.0,-0.425491,inf,0.970686,1.566807,-5.531388,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-5.934718,0,278
2025/09/09-11:25,6901.0,6942.2,6893.0,6942.2,6946.4,6853.6,14,22,14,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-5.934718,-6.197649,1.328321,-0.728261,14.0,20.0,-0.423908,inf,0.970686,1.160598,-5.934718,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-5.214485,0,278
2025/09/09-11:30,6906.0,6942.2,6893.0,6942.2,6946.4,6853.6,15,23,15,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-5.214485,-6.197649,1.328321,-0.728261,15.0,20.0,-0.347632,inf,0.970686,1.885971,-5.214485,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-7.173518,0,278
2025/09/09-13:05,6892.4,6942.2,6893.0,6942.2,6946.4,6853.6,16,24,16,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-7.173518,-6.197649,1.328321,-0.728261,16.0,20.0,-0.448345,inf,0.970686,-0.087045,-7.173518,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-6.568523,0,278
2025/09/09-13:10,6896.6,6942.2,6893.0,6942.2,6946.4,6853.6,17,25,17,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-6.568523,-6.197649,1.328321,-0.728261,17.0,20.0,-0.386384,inf,0.970686,0.522269,-6.568523,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-9.132552,0,278
2025/09/09-13:15,6878.8,6942.2,6893.0,6942.2,6946.4,6853.6,18,26,18,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-9.132552,-6.197649,1.328321,-0.728261,18.0,20.0,-0.507364,inf,0.970686,-2.060061,-9.132552,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-9.535882,0,278
2025/09/09-13:20,6876.0,6942.2,6893.0,6942.2,6946.4,6853.6,19,27,19,0.0000,7.1377,7.1377,0.0,7.509441,-6.197649,-9.535882,-6.197649,1.328321,-0.728261,19.0,20.0,-0.501889,inf,0.970686,-2.466270,-9.535882,6854.0,6946.4,-5.715944,-12.762525,-12.762525,-12.762525,0,278
2025/09/09-13:25,6853.6,6942.2,6853.6,6853.6,6946.4,6853.6,20,0,0,-12.7625,0.0000,-12.7625,20.0,7.509441,-6.197649,-12.762525,7.509441,1.328321,-0.728261,20.0,20.0,-0.638126,-0.638125,0.970686,-5.715944,-12.762525,6893.0,6946.4,0.000000,-12.762525,2.480448,2.480448,1,279
2025/09/09-13:30,6870.6,6870.6,6853.6,6870.6,6942.2,6870.6,0,1,0,0.0000,2.4804,2.4804,1.0,7.509441,-6.197649,2.480448,-6.197649,1.328321,-0.728261,1.0,1.0,2.480448,2.480400,0.970686,2.480448,-10.313733,6893.0,6942.2,2.480448,0.000000,-3.464035,-2.474311,1,280
2025/09/09-13:35,6853.6,6870.6,6853.6,6870.6,6942.2,6846.8,1,2,1,0.0000,2.4804,2.4804,0.0,7.509441,-6.197649,-2.474311,-6.197649,1.328321,-0.728261,1.0,2.0,-2.474311,inf,0.970686,0.000000,-2.474311,6893.0,6942.2,-0.992179,-3.464035,-3.464035,-3.464035,0,280
2025/09/09-13:40,6846.8,6870.6,6846.8,6846.8,6942.2,6846.8,2,0,0,-3.4640,0.0000,-3.4640,2.0,7.509441,-6.197649,-3.464035,7.509441,1.328321,-0.728261,2.0,2.0,-1.732018,-1.732000,0.970686,-0.992179,-3.464035,6853.6,6942.2,0.000000,-3.464035,2.921073,0.934743,1,281
2025/09/09-13:45,6853.2,6870.6,6846.8,6846.8,6942.2,6866.8,3,1,1,-3.4640,0.0000,-3.4640,0.0,7.509441,-6.197649,0.934743,7.509441,1.328321,-0.728261,1.0,3.0,0.934743,-inf,0.970686,0.934743,-2.532530,6853.6,6942.2,2.921073,-0.553081,2.921073,1.256061,0,281
2025/09/09-13:50,6855.4,6870.6,6846.8,6846.8,6942.2,6866.8,4,2,2,-3.4640,0.0000,-3.4640,0.0,7.509441,-6.197649,1.256061,7.509441,1.328321,-0.728261,2.0,3.0,0.628031,-inf,0.970686,1.256061,-2.212325,6853.6,6942.2,2.921073,-0.553081,2.921073,2.921073,0,281
2025/09/09-13:55,6866.8,6866.8,6846.8,6866.8,6870.6,6866.8,0,3,0,0.0000,2.9211,2.9211,3.0,7.509441,-6.197649,2.921073,-6.197649,1.328321,-0.728261,3.0,3.0,0.973691,0.973700,0.970686,2.921073,-0.553081,6853.6,6870.6,2.921073,0.000000,-3.990214,-3.990214,1,282
2025/09/09-14:00,6839.4,6866.8,6839.4,6839.4,6870.6,6839.4,1,0,0,-3.9902,0.0000,-3.9902,1.0,7.509441,-6.197649,-3.990214,7.509441,1.328321,-0.728261,1.0,1.0,-3.990214,-3.990200,0.970686,-1.080797,-3.990214,6846.8,6870.6,0.000000,-3.990214,5.819224,2.836506,1,283
2025/09/09-14:05,6858.8,6866.8,6839.4,6839.4,6870.6,6879.2,2,1,1,-3.9902,0.0000,-3.9902,0.0,7.509441,-6.197649,2.836506,7.509441,1.328321,-0.728261,1.0,3.0,2.836506,-inf,0.970686,2.836506,-1.165026,6846.8,6870.6,5.819224,1.805790,5.819224,2.310144,0,283

In [98]:
base1.loc['2025/09/10-09:50':'2025/09/11-10:30',:][['close2', 'peak2',
       'valley2', 'p_v_value2', 'peak_2nd1','p_v_value_bw2', 'p_pos2', 'v_pos2',
       'z_pos2', 'dw_pct_last2', 'up_pct_last2', 'z_pct_prev2',
       'z_len_prev2', 'up_pct_avg2', 'dw_pct_avg2', 'z_pct_curr2',
       'z_pct_avg2', 'up_pct_avg_k2', 'dw_pct_avg_k2', 'z_len_curr2',
       'z_len_full2', 'z_pct_curr_avg_k2', 'z_pct_prev_avg_k2',
       'z_pct_avg_k2', 'v_pct_curr2', 'p_pct_curr2', 'valley_last2',
       'peak_last2', 'v_pct_bw2', 'p_pct_bw2', 'z_pct_curr_full2',
       'z_pct_curr_next2', 'zig_flag2', 'zig_index2']]

,close2,peak2,valley2,p_v_value2,peak_2nd1,p_v_value_bw2,p_pos2,v_pos2,z_pos2,dw_pct_last2,up_pct_last2,z_pct_prev2,z_len_prev2,up_pct_avg2,dw_pct_avg2,z_pct_curr2,z_pct_avg2,up_pct_avg_k2,dw_pct_avg_k2,z_len_curr2,z_len_full2,z_pct_curr_avg_k2,z_pct_prev_avg_k2,z_pct_avg_k2,v_pct_curr2,p_pct_curr2,valley_last2,peak_last2,v_pct_bw2,p_pct_bw2,z_pct_curr_full2,z_pct_curr_next2,zig_flag2,zig_index2
time,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025/09/10-09:50,6934.4,6879.2,6856.2,6856.2,6866.8,6944.6,13,10,10,-3.3434,0.0000,-3.3434,0.0,10.388698,-8.397042,11.405735,10.388698,1.229735,-0.606308,10.0,11.0,1.140573,-inf,0.847184,11.405735,8.024189,6839.4,6942.2,12.893440,9.506919,12.893440,12.893440,0,183
2025/09/10-09:55,6944.6,6944.6,6856.2,6944.6,6879.2,6944.6,0,11,0,0.0000,12.8934,12.8934,11.0,10.388698,-8.397042,12.893440,-8.397042,1.229735,-0.606308,11.0,11.0,1.172131,1.172127,0.847184,12.893440,9.506919,6839.4,6879.2,12.893440,0.000000,-15.062063,-4.060709,1,184
2025/09/10-10:00,6916.4,6944.6,6856.2,6944.6,6879.2,6840.0,1,12,1,0.0000,12.8934,12.8934,0.0,10.388698,-8.397042,-4.060709,-8.397042,1.229735,-0.606308,1.0,10.0,-4.060709,inf,0.847184,8.780374,-4.060709,6839.4,6879.2,-2.362825,-15.062063,-15.062063,-7.142240,0,184
2025/09/10-10:05,6895.0,6944.6,6856.2,6944.6,6879.2,6840.0,2,13,2,0.0000,12.8934,12.8934,0.0,10.388698,-8.397042,-7.142240,-8.397042,1.229735,-0.606308,2.0,10.0,-3.571120,inf,0.847184,5.659111,-7.142240,6839.4,6879.2,-2.362825,-15.062063,-15.062063,-7.833425,0,184
2025/09/10-10:10,6890.2,6944.6,6856.2,6944.6,6879.2,6840.0,3,14,3,0.0000,12.8934,12.8934,0.0,10.388698,-8.397042,-7.833425,-8.397042,1.229735,-0.606308,3.0,10.0,-2.611142,inf,0.847184,4.959015,-7.833425,6839.4,6879.2,-2.362825,-15.062063,-15.062063,-5.759871,0,184
2025/09/10-10:15,6904.6,6944.6,6856.2,6944.6,6944.6,6840.0,4,15,4,0.0000,12.8934,12.8934,0.0,10.388698,-8.397042,-5.759871,-8.397042,1.229735,-0.606308,4.0,10.0,-1.439968,inf,0.847184,7.059304,-5.759871,6839.4,6879.2,-2.362825,-15.062063,-15.062063,-9.446188,0,184
2025/09/10-10:20,6879.0,6944.6,6856.2,6944.6,6944.6,6840.0,5,16,5,0.0000,12.8934,12.8934,0.0,10.388698,-8.397042,-9.446188,-8.397042,1.229735,-0.606308,5.0,10.0,-1.889238,inf,0.847184,3.325457,-9.446188,6839.4,6879.2,-2.362825,-15.062063,-15.062063,-11.145350,0,184
2025/09/10-10:25,6867.2,6944.6,6856.2,6944.6,6944.6,6840.0,6,17,6,0.0000,12.8934,12.8934,0.0,10.388698,-8.397042,-11.145350,-8.397042,1.229735,-0.606308,6.0,10.0,-1.857558,inf,0.847184,1.604387,-11.145350,6839.4,6879.2,-2.362825,-15.062063,-15.062063,-11.634939,0,184
2025/09/10-10:30,6863.8,6944.6,6856.2,6944.6,6944.6,6840.0,7,18,7,0.0000,12.8934,12.8934,0.0,10.388698,-8.397042,-11.634939,-8.397042,1.229735,-0.606308,7.0,10.0,-1.662134,inf,0.847184,1.108486,-11.634939,6839.4,6879.2,-2.362825,-15.062063,-15.062063,-12.671716,0,184
2025/09/10-10:35,6856.6,6944.6,6856.2,6944.6,6944.6,6840.0,8,19,8,0.0000,12.8934,12.8934,0.0,10.388698,-8.397042,-12.671716,-8.397042,1.229735,-0.606308,8.0,10.0,-1.583965,inf,0.847184,0.058341,-12.671716,6839.4,6879.2,-2.362825,-15.062063,-15.062063,-13.276503,0,184
2025/09/10-10:40,6852.4,6944.6,6856.2,6944.6,6944.6,6840.0,9,20,9,0.0000,12.8934,12.8934,0.0,10.388698,-8.397042,-13.276503,-8.397042,1.229735,-0.606308,9.0,10.0,-1.475167,inf,0.847184,-0.554243,-13.276503,6839.4,6879.2,-2.362825,-15.062063,-15.062063,-15.062063,0,184
2025/09/10-10:45,6840.0,6944.6,6840.0,6840.0,6944.6,6840.0,10,0,0,-15.0621,0.0000,-15.0621,10.0,10.388698,-8.397042,-15.062063,10.388698,1.229735,-0.606308,10.0,10.0,-1.506206,-1.506210,0.847184,-2.362825,-15.062063,6856.2,6879.2,0.000000,-15.062063,9.502924,1.608187,1,185
2025/09/10-10:50,6851.0,6944.6,6840.0,6840.0,6944.6,6905.0,11,1,1,-15.0621,0.0000,-15.0621,0.0,10.388698,-8.397042,1.608187,10.388698,1.229735,-0.606308,1.0,11.0,1.608187,-inf,0.847184,1.608187,-13.478098,6856.2,6879.2,9.502924,-5.702272,9.502924,2.339181,0,185
2025/09/10-10:55,6856.0,6944.6,6840.0,6840.0,6944.6,6905.0,12,2,2,-15.0621,0.0000,-15.0621,0.0,10.388698,-8.397042,2.339181,10.388698,1.229735,-0.606308,2.0,11.0,1.169591,-inf,0.847184,2.339181,-12.758114,6856.2,6879.2,9.502924,-5.702272,9.502924,1.549708,0,185
2025/09/10-11:00,6850.6,6944.6,6840.0,6840.0,6944.6,6905.0,13,3,3,-15.0621,0.0000,-15.0621,0.0,10.388698,-8.397042,1.549708,10.388698,1.229735,-0.606308,3.0,11.0,0.516569,-inf,0.847184,1.549708,-13.535697,6856.2,6879.2,9.502924,-5.702272,9.502924,2.836257,0,185
2025/09/10-11:05,6859.4,6944.6,6840.0,6840.0,6944.6,6905.0,14,4,4,-15.0621,0.0000,-15.0621,0.0,10.388698,-8.397042,2.836257,10.388698,1.229735,-0.606308,4.0,11.0,0.709064,-inf,0.847184,2.836257,-12.268525,6856.2,6879.2,9.502924,-5.702272,9.502924,3.596491,0,185
2025/09/10-11:10,6864.6,6944.6,6840.0,6840.0,6944.6,6905.0,15,5,5,-15.0621,0.0000,-15.0621,0.0,10.388698,-8.397042,3.596491,10.388698,1.229735,-0.606308,5.0,11.0,0.719298,-inf,0.847184,3.596491,-11.519742,6856.2,6879.2,9.502924,-5.702272,9.502924,5.555556,0,185
2025/09/10-11:15,6878.0,6944.6,6840.0,6840.0,6944.6,6905.0,16,6,6,-15.0621,0.0000,-15.0621,0.0,10.388698,-8.397042,5.555556,10.388698,1.229735,-0.606308,6.0,11.0,0.925926,-inf,0.847184,5.555556,-9.590185,6856.2,6879.2,9.502924,-5.702272,9.502924,6.988304,0,185
2025/09/10-11:20,6887.8,6944.6,6840.0,6840.0,6944.6,6905.0,17,7,7,-15.0621,0.0000,-15.0621,0.0,10.388698,-8.397042,6.988304,10.388698,1.229735,-0.606308,7.0,11.0,0.998329,-inf,0.847184,6.988304,-8.179017,6856.2,6879.2,9.502924,-5.702272,9.502924,7.046784,0,185
2025/09/10-11:25,6888.2,6944.6,6840.0,6840.0,6944.6,6905.0,18,8,8,-15.0621,0.0000,-15.0621,0.0,10.388698,-8.397042,7.046784,10.388698,1.229735,-0.606308,8.0,11.0,0.880848,-inf,0.847184,7.046784,-8.121418,6856.2,6879.2,9.502924,-5.702272,9.502924,6.198830,0,185
2025/09/10-11:30,6882.4,6944.6,6840.0,6840.0,6944.6,6905.0,19,9,9,-15.0621,0.0000,-15.0621,0.0,10.388698,-8.397042,6.198830,10.388698,1.229735,-0.606308,9.0,11.0,0.688759,-inf,0.847184,6.198830,-8.956599,6856.2,6879.2,9.502924,-5.702272,9.502924,6.432749,0,185
2025/09/10-13:05,6884.0,6944.6,6840.0,6840.0,6944.6,6905.0,20,10,10,-15.0621,0.0000,-15.0621,0.0,10.388698,-8.397042,6.432749,10.388698,1.229735,-0.606308,10.0,11.0,0.643275,-inf,0.847184,6.432749,-8.726205,6856.2,6879.2,9.502924,-5.702272,9.502924,9.502924,0,185
2025/09/10-13:10,6905.0,6905.0,6840.0,6905.0,6904.6,6905.0,0,11,0,0.0000,9.5029,9.5029,11.0,10.388698,-8.397042,9.502924,-8.397042,1.229735,-0.606308,11.0,11.0,0.863902,0.863900,0.847184,9.502924,-5.702272,6856.2,6944.6,9.502924,0.000000,-9.239681,-2.577842,1,186
2025/09/10-13:15,6887.2,6905.0,6840.0,6905.0,6904.6,6841.2,1,12,1,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-2.577842,-8.397042,1.229735,-0.606308,1.0,23.0,-2.577842,inf,0.847184,6.900585,-2.577842,6856.2,6944.6,0.175439,-9.239681,-9.239681,-3.128168,0,186
2025/09/10-13:20,6883.4,6905.0,6840.0,6905.0,6904.6,6841.2,2,13,2,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-3.128168,-8.397042,1.229735,-0.606308,2.0,23.0,-1.564084,inf,0.847184,6.345029,-3.128168,6856.2,6944.6,0.175439,-9.239681,-9.239681,-1.824765,0,186
2025/09/10-13:25,6892.4,6905.0,6840.0,6905.0,6904.6,6841.2,3,14,3,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-1.824765,-8.397042,1.229735,-0.606308,3.0,23.0,-0.608255,inf,0.847184,7.660819,-1.824765,6856.2,6944.6,0.175439,-9.239681,-9.239681,-1.129616,0,186
2025/09/10-13:30,6897.2,6905.0,6840.0,6905.0,6904.6,6841.2,4,15,4,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-1.129616,-8.397042,1.229735,-0.606308,4.0,23.0,-0.282404,inf,0.847184,8.362573,-1.129616,6856.2,6944.6,0.175439,-9.239681,-9.239681,-1.737871,0,186
2025/09/10-13:35,6893.0,6905.0,6840.0,6905.0,6904.6,6841.2,5,16,5,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-1.737871,-8.397042,1.229735,-0.606308,5.0,23.0,-0.347574,inf,0.847184,7.748538,-1.737871,6856.2,6944.6,0.175439,-9.239681,-9.239681,-2.056481,0,186
2025/09/10-13:40,6890.8,6905.0,6840.0,6905.0,6904.6,6841.2,6,17,6,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-2.056481,-8.397042,1.229735,-0.606308,6.0,23.0,-0.342747,inf,0.847184,7.426901,-2.056481,6856.2,6944.6,0.175439,-9.239681,-9.239681,-2.259232,0,186
2025/09/10-13:45,6889.4,6905.0,6840.0,6905.0,6904.6,6841.2,7,18,7,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-2.259232,-8.397042,1.229735,-0.606308,7.0,23.0,-0.322747,inf,0.847184,7.222222,-2.259232,6856.2,6944.6,0.175439,-9.239681,-9.239681,-1.998552,0,186
2025/09/10-13:50,6891.2,6905.0,6840.0,6905.0,6904.6,6841.2,8,19,8,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-1.998552,-8.397042,1.229735,-0.606308,8.0,23.0,-0.249819,inf,0.847184,7.485380,-1.998552,6856.2,6944.6,0.175439,-9.239681,-9.239681,-2.230268,0,186
2025/09/10-13:55,6889.6,6905.0,6840.0,6905.0,6904.6,6841.2,9,20,9,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-2.230268,-8.397042,1.229735,-0.606308,9.0,23.0,-0.247808,inf,0.847184,7.251462,-2.230268,6856.2,6944.6,0.175439,-9.239681,-9.239681,-1.650978,0,186
2025/09/10-14:00,6893.6,6905.0,6840.0,6905.0,6904.6,6841.2,10,21,10,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-1.650978,-8.397042,1.229735,-0.606308,10.0,23.0,-0.165098,inf,0.847184,7.836257,-1.650978,6856.2,6944.6,0.175439,-9.239681,-9.239681,-0.289645,0,186
2025/09/10-14:05,6903.0,6905.0,6840.0,6905.0,6905.0,6841.2,11,22,11,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-0.289645,-8.397042,1.229735,-0.606308,11.0,23.0,-0.026331,inf,0.847184,9.210526,-0.289645,6856.2,6944.6,0.175439,-9.239681,-9.239681,-0.984794,0,186
2025/09/10-14:10,6898.2,6905.0,6840.0,6905.0,6905.0,6841.2,12,23,12,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-0.984794,-8.397042,1.229735,-0.606308,12.0,23.0,-0.082066,inf,0.847184,8.508772,-0.984794,6856.2,6944.6,0.175439,-9.239681,-9.239681,-1.013758,0,186
2025/09/10-14:15,6898.0,6905.0,6840.0,6905.0,6905.0,6841.2,13,24,13,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-1.013758,-8.397042,1.229735,-0.606308,13.0,23.0,-0.077981,inf,0.847184,8.479532,-1.013758,6856.2,6944.6,0.175439,-9.239681,-9.239681,-2.230268,0,186
2025/09/10-14:20,6889.6,6905.0,6840.0,6905.0,6905.0,6841.2,14,25,14,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-2.230268,-8.397042,1.229735,-0.606308,14.0,23.0,-0.159305,inf,0.847184,7.251462,-2.230268,6856.2,6944.6,0.175439,-9.239681,-9.239681,-0.666184,0,186
2025/09/10-14:25,6900.4,6905.0,6840.0,6905.0,6905.0,6841.2,15,26,15,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-0.666184,-8.397042,1.229735,-0.606308,15.0,23.0,-0.044412,inf,0.847184,8.830409,-0.666184,6856.2,6944.6,0.175439,-9.239681,-9.239681,-1.245474,0,186
2025/09/10-14:30,6896.4,6905.0,6840.0,6905.0,6905.0,6841.2,16,27,16,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-1.245474,-8.397042,1.229735,-0.606308,16.0,23.0,-0.077842,inf,0.847184,8.245614,-1.245474,6856.2,6944.6,0.175439,-9.239681,-9.239681,-2.983345,0,186
2025/09/10-14:35,6884.4,6905.0,6840.0,6905.0,6905.0,6841.2,17,28,17,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-2.983345,-8.397042,1.229735,-0.606308,17.0,23.0,-0.175491,inf,0.847184,6.491228,-2.983345,6856.2,6944.6,0.175439,-9.239681,-9.239681,-3.910210,0,186
2025/09/10-14:40,6878.0,6905.0,6840.0,6905.0,6905.0,6841.2,18,29,18,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-3.910210,-8.397042,1.229735,-0.606308,18.0,23.0,-0.217234,inf,0.847184,5.555556,-3.910210,6856.2,6944.6,0.175439,-9.239681,-9.239681,-3.244026,0,186
2025/09/10-14:45,6882.6,6905.0,6840.0,6905.0,6905.0,6841.2,19,30,19,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-3.244026,-8.397042,1.229735,-0.606308,19.0,23.0,-0.170738,inf,0.847184,6.228070,-3.244026,6856.2,6944.6,0.175439,-9.239681,-9.239681,-4.170891,0,186
2025/09/10-14:50,6876.2,6905.0,6840.0,6905.0,6905.0,6841.2,20,31,20,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-4.170891,-8.397042,1.229735,-0.606308,20.0,23.0,-0.208545,inf,0.847184,5.292398,-4.170891,6856.2,6944.6,0.175439,-9.239681,-9.239681,-4.721217,0,186
2025/09/10-14:55,6872.4,6905.0,6840.0,6905.0,6905.0,6841.2,21,32,21,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-4.721217,-8.397042,1.229735,-0.606308,21.0,23.0,-0.224820,inf,0.847184,4.736842,-4.721217,6856.2,6944.6,0.175439,-9.239681,-9.239681,-6.024620,0,186
2025/09/10-15:00,6863.4,6905.0,6840.0,6905.0,6905.0,6841.2,22,33,22,0.0000,9.5029,9.5029,0.0,10.388698,-8.397042,-6.024620,-8.397042,1.229735,-0.606308,22.0,23.0,-0.273846,inf,0.847184,3.421053,-6.024620,6856.2,6944.6,0.175439,-9.239681,-9.239681,-9.239681,0,186
2025/09/11-09:35,6841.2,6905.0,6841.2,6841.2,6905.0,6841.2,23,0,0,-9.2397,0.0000,-9.2397,23.0,10.388698,-8.397042,-9.239681,10.388698,1.229735,-0.606308,23.0,23.0,-0.401725,-0.401726,0.847184,0.175439,-9.239681,6840.0,6944.6,0.000000,-9.239681,32.275039,1.637140,1,187
2025/09/11-09:40,6852.4,6905.0,6841.2,6841.2,6905.0,7062.0,24,1,1,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,1.637140,10.388698,1.229735,-0.606308,1.0,25.0,1.637140,-inf,0.847184,1.637140,-7.617668,6840.0,6944.6,32.275039,22.737147,32.275039,6.197743,0,187
2025/09/11-09:45,6883.6,6905.0,6841.2,6841.2,6905.0,7062.0,25,2,2,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,6.197743,10.388698,1.229735,-0.606308,2.0,25.0,3.098872,-inf,0.847184,6.197743,-3.099203,6840.0,6944.6,32.275039,22.737147,32.275039,7.542536,0,187
2025/09/11-09:50,6892.8,6905.0,6841.2,6841.2,6903.0,7062.0,26,3,3,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,7.542536,10.388698,1.229735,-0.606308,3.0,25.0,2.514179,-inf,0.847184,7.542536,-1.766836,6840.0,6944.6,32.275039,22.737147,32.275039,5.349939,0,187
2025/09/11-09:55,6877.8,6905.0,6841.2,6841.2,6903.0,7062.0,27,4,4,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,5.349939,10.388698,1.229735,-0.606308,4.0,25.0,1.337485,-inf,0.847184,5.349939,-3.939175,6840.0,6944.6,32.275039,22.737147,32.275039,8.478045,0,187
2025/09/11-10:00,6899.2,6905.0,6841.2,6841.2,6903.0,7062.0,28,5,5,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,8.478045,10.388698,1.229735,-0.606308,5.0,25.0,1.695609,-inf,0.847184,8.478045,-0.839971,6840.0,6944.6,32.275039,22.737147,32.275039,11.430743,0,187
2025/09/11-10:05,6919.4,6905.0,6841.2,6841.2,6903.0,7062.0,29,6,6,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,11.430743,10.388698,1.229735,-0.606308,6.0,25.0,1.905124,-inf,0.847184,11.430743,2.085445,6840.0,6944.6,32.275039,22.737147,32.275039,12.453955,0,187
2025/09/11-10:10,6926.4,6905.0,6841.2,6841.2,6903.0,7062.0,30,7,7,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,12.453955,10.388698,1.229735,-0.606308,7.0,25.0,1.779136,-inf,0.847184,12.453955,3.099203,6840.0,6944.6,32.275039,22.737147,32.275039,13.477168,0,187
2025/09/11-10:15,6933.4,6905.0,6841.2,6841.2,6903.0,7062.0,31,8,8,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,13.477168,10.388698,1.229735,-0.606308,8.0,25.0,1.684646,-inf,0.847184,13.477168,4.112962,6840.0,6944.6,32.275039,22.737147,32.275039,12.717067,0,187
2025/09/11-10:20,6928.2,6905.0,6841.2,6841.2,6903.0,7062.0,32,9,9,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,12.717067,10.388698,1.229735,-0.606308,9.0,25.0,1.413007,-inf,0.847184,12.717067,3.359884,6840.0,6944.6,32.275039,22.737147,32.275039,12.337017,0,187
2025/09/11-10:25,6925.6,6905.0,6841.2,6841.2,6903.0,7062.0,33,10,10,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,12.337017,10.388698,1.229735,-0.606308,10.0,25.0,1.233702,-inf,0.847184,12.337017,2.983345,6840.0,6944.6,32.275039,22.737147,32.275039,14.617319,0,187
2025/09/11-10:30,6941.2,6905.0,6841.2,6841.2,6903.0,7062.0,34,11,11,-9.2397,0.0000,-9.2397,0.0,10.388698,-8.397042,14.617319,10.388698,1.229735,-0.606308,11.0,25.0,1.328847,-inf,0.847184,14.617319,5.242578,6840.0,6944.6,32.275039,22.737147,32.275039,15.085073,0,187