In [1]:
from QUANTAXIS import QA_SU_save_stock_day

In [52]:
import inspect

# 假设你要查看的函数是 my_function
file_path = inspect.getfile(QA_SU_save_stock_day)
print(file_path)

d:\ProgramData\Anaconda3\lib\site-packages\QUANTAXIS\QAUtil\__init__.py

In [14]:
from QUANTAXIS.QAFetch.QATdx import *

In [4]:
from QUANTAXIS import QA_fetch_get_stock_day

In [30]:
from QUANTAXIS.QAFetch.base import _select_market_code, _select_index_code, _select_type, _select_bond_market_code

In [50]:
from QUANTAXIS import QA_SU_save_stock_day

In [5]:
from QUANTAXIS.QAUtil import DATABASE

In [1]:
from QUANTAXIS.QASU import save_tdx_parallelism

In [35]:
from QUANTAXIS.QAFetch import QA_fetch_get_stock_list,QA_fetch_get_stock_day

In [13]:
import pymongo

In [11]:
stock_list

['000001',
 '000002',
 '000004',
 '000006',
 '000007',
 '000008',
 '000009',
 '000010',
 '000011',
 '000012',
 '000014',
 '000016',
 '000017',
 '000019',
 '000020',
 '000021',
 '000025',
 '000026',
 '000027',
 '000028',
 '000029',
 '000030',
 '000031',
 '000032',
 '000034',
 '000035',
 '000036',
 '000037',
 '000039',
 '000042',
 '000045',
 '000048',
 '000049',
 '000050',
 '000055',
 '000056',
 '000058',
 '000059',
 '000060',
 '000061',
 '000062',
 '000063',
 '000065',
 '000066',
 '000068',
 '000069',
 '000070',
 '000078',
 '000088',
 '000089',
 '000090',
 '000096',
 '000099',
 '000100',
 '000151',
 '000153',
 '000155',
 '000156',
 '000157',
 '000158',
 '000159',
 '000166',
 '000301',
 '000333',
 '000338',
 '000400',
 '000401',
 '000402',
 '000403',
 '000404',
 '000407',
 '000408',
 '000409',
 '000410',
 '000411',
 '000415',
 '000417',
 '000419',
 '000420',
 '000421',
 '000422',
 '000423',
 '000425',
 '000426',
 '000428',
 '000429',
 '000430',
 '000488',
 '000498',
 '000501',
 '000503',
 '000504',
 '000505',
 '000506',
 '000507',
 '000509',
 '000510',
 '000513',
 '000514',
 '000516',
 '000517',
 '000518',
 '000519',
 '000520',
 '000521',
 '000523',
 '000524',
 '000525',
 '000526',
 '000528',
 '000529',
 '000530',
 '000531',
 '000532',
 '000533',
 '000534',
 '000536',
 '000537',
 '000538',
 '000539',
 '000541',
 '000543',
 '000544',
 '000545',
 '000546',
 '000547',
 '000548',
 '000550',
 '000551',
 '000552',
 '000553',
 '000554',
 '000555',
 '000557',
 '000558',
 '000559',
 '000560',
 '000561',
 '000563',
 '000564',
 '000565',
 '000566',
 '000567',
 '000568',
 '000570',
 '000571',
 '000572',
 '000573',
 '000576',
 '000581',
 '000582',
 '000586',
 '000589',
 '000590',
 '000591',
 '000592',
 '000593',
 '000595',
 '000596',
 '000597',
 '000598',
 '000599',
 '000600',
 '000601',
 '000603',
 '000605',
 '000607',
 '000608',
 '000609',
 '000610',
 '000612',
 '000615',
 '000617',
 '000619',
 '000620',
 '000623',
 '000625',
 '000626',
 '000628',
 '000629',
 '000630',
 '000631',
 '000632',
 '000633',
 '000635',
 '000636',
 '000637',
 '000639',
 '000650',
 '000651',
 '000652',
 '000655',
 '000656',
 '000657',
 '000659',
 '000661',
 '000663',
 '000665',
 '000668',
 '000669',
 '000670',
 '000672',
 '000676',
 '000677',
 '000678',
 '000679',
 '000680',
 '000681',
 '000682',
 '000683',
 '000685',
 '000686',
 '000688',
 '000690',
 '000691',
 '000692',
 '000695',
 '000697',
 '000698',
 '000700',
 '000701',
 '000702',
 '000703',
 '000705',
 '000707',
 '000708',
 '000709',
 '000710',
 '000711',
 '000712',
 '000713',
 '000715',
 '000716',
 '000717',
 '000718',
 '000719',
 '000720',
 '000721',
 '000722',
 '000723',
 '000725',
 '000726',
 '000727',
 '000728',
 '000729',
 '000731',
 '000733',
 '000735',
 '000736',
 '000737',
 '000738',
 '000739',
 '000750',
 '000751',
 '000752',
 '000753',
 '000755',
 '000756',
 '000757',
 '000758',
 '000759',
 '000761',
 '000762',
 '000766',
 '000767',
 '000768',
 '000776',
 '000777',
 '000778',
 '000779',
 '000782',
 '000783',
 '000785',
 '000786',
 '000788',
 '000789',
 '000790',
 '000791',
 '000792',
 '000793',
 '000795',
 '000796',
 '000797',
 '000798',
 '000799',
 '000800',
 '000801',
 '000802',
 '000803',
 '000807',
 '000809',
 '000810',
 '000811',
 '000812',
 '000813',
 '000815',
 '000816',
 '000818',
 '000819',
 '000820',
 '000821',
 '000822',
 '000823',
 '000825',
 '000826',
 '000828',
 '000829',
 '000830',
 '000831',
 '000833',
 '000837',
 '000838',
 '000839',
 '000848',
 '000850',
 '000852',
 '000856',
 '000858',
 '000859',
 '000860',
 '000862',
 '000863',
 '000868',
 '000869',
 '000875',
 '000876',
 '000877',
 '000878',
 '000880',
 '000881',
 '000882',
 '000883',
 '000885',
 '000886',
 '000887',
 '000888',
 '000889',
 '000890',
 '000892',
 '000893',
 '000895',
 '000897',
 '000898',
 '000899',
 '000900',
 '000901',
 '000902',
 '000903',
 '000905',
 '000906',
 '000908',
 '000909',
 '000910',
 '000911',
 '000912',
 '000913',
 '000915',
 '000917',
 '000919',
 '000920',
 '000921',
 '000922',
 '000923',
 '000925',
 '000926',
 '000927',
 '000928',
 '000929',
 '000930',
 '000931',
 '000932',
 '000933',
 '000935',
 '000936',
 '000937',
 '000938',
 '000948',
 '000949',
 '000950',
 '000951',
 '000952',
 '000953',
 '000955',
 '000957',
 '000958',
 '000959',
 '000960',
 '000962',
 '000963',
 '000965',
 '000966',
 '000967',
 '000968',
 '000969',
 '000970',
 '000972',
 '000973',
 '000975',
 '000977',
 '000978',
 '000980',
 '000981',
 '000983',
 '000985',
 '000987',
 '000988',
 '000989',
 '000990',
 '000993',
 '000995',
 '000997',
 '000998',
 '000999',
 '001201',
 '001202',
 '001203',
 '001205',
 '001206',
 '001207',
 '001208',
 '001209',
 '001210',
 '001211',
 '001212',
 '001213',
 '001215',
 '001216',
 '001217',
 '001218',
 '001219',
 '001220',
 '001221',
 '001222',
 '001223',
 '001225',
 '001226',
 '001227',
 '001228',
 '001229',
 '001230',
 '001231',
 '001233',
 '001234',
 '001236',
 '001237',
 '001238',
 '001239',
 '001248',
 '001255',
 '001256',
 '001257',
 '001258',
 '001259',
 '001260',
 '001266',
 '001267',
 '001268',
 '001269',
 '001270',
 '001277',
 '001278',
 '001279',
 '001280',
 '001282',
 '001283',
 '001285',
 '001286',
 '001287',
 '001288',
 '001289',
 '001296',
 '001298',
 '001299',
 '001300',
 '001301',
 '001306',
 '001308',
 '001309',
 '001311',
 '001312',
 '001313',
 '001314',
 '001316',
 '001317',
 '001318',
 '001319',
 '001322',
 '001323',
 '001324',
 '001325',
 '001326',
 '001328',
 '001330',
 '001331',
 '001332',
 '001333',
 '001335',
 '001336',
 '001337',
 '001338',
 '001339',
 '001356',
 '001358',
 '001359',
 '001360',
 '001365',
 '001366',
 '001367',
 '001368',
 '001369',
 '001373',
 '001376',
 '001378',
 '001379',
 '001380',
 '001382',
 '001386',
 '001387',
 '001388',
 '001389',
 '001390',
 '001391',
 '001393',
 '001395',
 '001396',
 '001399',
 '001400',
 '001696',
 '001872',
 '001896',
 '001914',
 '001965',
 '001979',
 '002001',
 '002003',
 '002004',
 '002005',
 '002006',
 '002007',
 '002008',
 '002009',
 '002010',
 '002011',
 '002012',
 '002014',
 '002015',
 '002016',
 '002017',
 '002019',
 '002020',
 '002021',
 '002022',
 '002023',
 '002024',
 '002025',
 '002026',
 '002027',
 '002028',
 '002029',
 '002030',
 '002031',
 '002032',
 '002033',
 '002034',
 '002035',
 '002036',
 '002037',
 '002038',
 '002039',
 '002040',
 '002041',
 '002042',
 '002043',
 '002044',
 '002045',
 '002046',
 '002047',
 '002048',
 '002049',
 '002050',
 '002051',
 '002052',
 '002053',
 '002054',
 '002055',
 '002056',
 '002057',
 '002058',
 '002059',
 '002060',
 '002061',
 '002062',
 '002063',
 '002064',
 '002065',
 '002066',
 '002067',
 '002068',
 '002069',
 '002072',
 '002073',
 '002074',
 '002075',
 '002076',
 '002077',
 '002078',
 '002079',
 '002080',
 '002081',
 '002082',
 '002083',
 '002084',
 '002085',
 '002086',
 '002088',
 '002090',
 '002091',
 '002092',
 '002093',
 '002094',
 '002095',
 '002096',
 '002097',
 '002098',
 '002099',
 '002100',
 '002101',
 '002102',
 '002103',
 '002104',
 '002105',
 '002106',
 '002107',
 '002108',
 '002109',
 '002110',
 '002111',
 '002112',
 '002114',
 '002115',
 '002116',
 '002117',
 '002119',
 '002120',
 '002121',
 '002122',
 '002123',
 '002124',
 '002125',
 '002126',
 '002127',
 '002128',
 '002129',
 '002130',
 '002131',
 '002132',
 '002133',
 '002134',
 '002135',
 '002136',
 '002137',
 '002138',
 '002139',
 '002140',
 '002141',
 '002142',
 '002144',
 '002145',
 '002146',
 '002148',
 '002149',
 '002150',
 '002151',
 '002152',
 '002153',
 '002154',
 '002155',
 '002156',
 '002157',
 '002158',
 '002159',
 '002160',
 '002161',
 '002162',
 '002163',
 '002164',
 '002165',
 '002166',
 '002167',
 '002168',
 '002169',
 '002170',
 '002171',
 '002172',
 '002173',
 '002174',
 '002175',
 '002176',
 '002177',
 '002178',
 '002179',
 '002180',
 '002181',
 '002182',
 '002183',
 '002184',
 '002185',
 '002186',
 '002187',
 '002188',
 '002189',
 '002190',
 '002191',
 '002192',
 '002193',
 '002194',
 '002195',
 '002196',
 '002197',
 '002198',
 '002199',
 '002200',
 '002201',
 '002202',
 '002203',
 '002204',
 '002205',
 '002206',
 '002207',
 '002208',
 '002209',
 '002210',
 '002211',
 '002212',
 '002213',
 '002214',
 '002215',
 '002216',
 '002217',
 '002218',
 '002219',
 '002221',
 '002222',
 '002223',
 '002224',
 '002225',
 '002226',
 '002227',
 '002228',
 '002229',
 '002230',
 '002232',
 '002233',
 '002234',
 '002235',
 '002236',
 '002237',
 '002238',
 '002239',
 '002240',
 '002241',
 '002242',
 '002243',
 '002244',
 '002245',
 '002246',
 '002247',
 '002248',
 '002249',
 '002250',
 '002251',
 '002252',
 '002253',
 '002254',
 '002255',
 '002256',
 '002258',
 '002259',
 '002261',
 '002262',
 '002263',
 '002264',
 '002265',
 '002266',
 '002267',
 '002268',
 '002269',
 '002270',
 '002271',
 '002272',
 '002273',
 '002274',
 '002275',
 '002276',
 '002277',
 '002278',
 '002279',
 '002281',
 '002282',
 '002283',
 '002284',
 '002285',
 '002286',
 '002287',
 '002289',
 '002290',
 '002291',
 '002292',
 '002293',
 '002294',
 '002295',
 '002296',
 '002297',
 '002298',
 '002299',
 '002300',
 '002301',
 '002302',
 '002303',
 '002304',
 '002305',
 '002306',
 '002307',
 '002309',
 '002310',
 '002311',
 '002312',
 '002313',
 '002314',
 '002315',
 '002316',
 '002317',
 '002318',
 '002319',
 '002320',
 '002321',
 '002322',
 '002323',
 '002324',
 '002326',
 '002327',
 '002328',
 '002329',
 '002330',
 '002331',
 '002332',
 '002333',
 '002334',
 '002335',
 '002337',
 '002338',
 '002339',
 '002340',
 '002342',
 '002343',
 '002344',
 '002345',
 '002346',
 '002347',
 '002348',
 '002349',
 '002350',
 '002351',
 '002352',
 '002353',
 '002354',
 '002355',
 '002356',
 '002357',
 '002358',
 '002360',
 '002361',
 '002362',
 '002363',
 '002364',
 '002365',
 '002366',
 '002367',
 '002368',
 '002369',
 '002370',
 '002371',
 '002372',
 '002373',
 '002374',
 '002375',
 '002376',
 '002377',
 '002378',
 '002379',
 '002380',
 '002381',
 '002382',
 '002383',
 '002384',
 '002385',
 '002386',
 '002387',
 '002388',
 '002389',
 '002390',
 '002391',
 '002392',
 '002393',
 '002394',
 '002395',
 '002396',
 '002397',
 '002398',
 '002399',
 '002400',
 '002401',
 '002402',
 '002403',
 '002404',
 '002405',
 '002406',
 '002407',
 '002408',
 '002409',
 '002410',
 '002412',
 '002413',
 '002414',
 '002415',
 '002416',
 '002418',
 '002419',
 '002420',
 '002421',
 '002422',
 '002423',
 '002424',
 '002425',
 '002426',
 '002427',
 '002428',
 '002429',
 '002430',
 '002431',
 '002432',
 '002434',
 '002436',
 '002437',
 '002438',
 '002439',
 '002440',
 '002441',
 '002442',
 '002443',
 '002444',
 '002445',
 '002446',
 '002448',
 '002449',
 '002451',
 '002452',
 '002453',
 '002454',
 '002455',
 '002456',
 '002457',
 '002458',
 '002459',
 '002460',
 '002461',
 '002462',
 '002463',
 '002465',
 '002466',
 '002467',
 '002468',
 '002469',
 '002470',
 '002471',
 '002472',
 '002474',
 '002475',
 '002476',
 '002478',
 '002479',
 '002480',
 '002481',
 '002482',
 '002483',
 '002484',
 '002485',
 '002486',
 '002487',
 '002488',
 '002489',
 '002490',
 '002491',
 '002492',
 '002493',
 '002494',
 '002495',
 '002496',
 '002497',
 '002498',
 ...]

In [18]:
from QUANTAXIS.QAFetch.QATdx import (
    get_ip_list_by_multi_process_ping,
    stock_ip_list,
    QA_fetch_get_stock_xdxr
)
from multiprocessing import cpu_count

In [25]:
from QUANTAXIS.QAUtil import (
    DATABASE,
    QA_util_get_next_day,
    QA_util_log_info,
    QA_util_to_json_from_pandas
)
from QUANTAXIS.QASU.save_tdx import now_time

In [30]:
from QUANTAXIS.QASU import save_tdx_parallelism

In [57]:
search_cond = {'Code':'000001'}
ref = coll_stock_day.find(search_cond)
ref_count = coll_stock_day.count_documents(search_cond)

In [64]:
coll_stock_day.count(search_cond)

<ipython-input-64-1b1470099900>:1: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere
  coll_stock_day.count(search_cond)

0

In [33]:
param

[('000001',
  '2025-05-23',
  '2026-07-07',
  '00',
  'day',
  '180.153.18.170',
  7709,
  0,
  2,
  None,
  None),
 ('000002',
  '2025-05-23',
  '2026-07-07',
  '00',
  'day',
  'jstdx.gtjas.com',
  7709,
  1,
  2,
  None,
  None)]

In [51]:
QA_SU_save_stock_day('tdx')

QUANTAXIS>> The 0 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000001
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000001 from 2025-05-23 to 2026-07-07
QUANTAXIS>> The 1 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000002
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000002 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000004
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000004 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.05% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000006 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.07% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000007 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.09% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000008 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 6 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.11% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000009 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 7 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.13% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000010
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000010 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 8 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.15% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000011 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 9 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.17% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000012
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000012 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 10 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.19% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000014
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000014 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 11 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.21% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000016 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 12 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.23% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000017
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000017 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 13 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000019
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000019 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 14 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000020 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 15 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000021
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000021 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 16 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.30% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000025
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000025 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 17 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.32% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000026
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000026 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 18 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.34% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000027
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000027 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 19 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.36% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000028
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000028 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 20 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.38% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000029
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000029 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 21 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.40% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000030
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000030 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 22 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.42% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000031
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000031 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 23 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.44% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000032
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000032 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 24 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.46% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000034
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000034 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 25 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.48% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000035
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000035 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 26 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000036
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000036 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 27 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000037
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000037 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 28 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.53% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000039
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000039 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 29 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.55% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000042
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000042 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 30 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.57% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000045
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000045 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 31 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.59% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000048
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000048 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 32 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.61% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000049
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000049 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 33 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.63% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000050
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000050 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 34 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.65% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000055
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000055 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 35 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.67% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000056
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000056 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 36 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.69% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000058
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000058 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 37 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.71% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000059
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000059 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 38 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.73% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000060
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000060 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 39 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000061
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000061 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 40 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.76% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000062
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000062 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 41 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.78% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000063
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000063 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 42 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.80% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000065
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000065 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 43 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.82% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000066
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000066 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 44 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.84% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000068
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000068 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 45 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.86% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000069
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000069 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 46 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.88% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000070
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000070 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 47 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.90% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000078
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000078 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 48 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.92% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000088
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000088 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 49 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.94% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000089
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000089 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 50 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.96% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000090
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000090 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 51 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000096
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000096 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 52 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000099
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000099 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 53 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000100
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000100 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 54 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000151
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000151 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 55 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.05% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000153
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000153 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 56 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.07% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000155
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000155 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 57 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.09% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000156
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000156 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 58 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.11% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000157
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000157 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 59 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.13% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000158
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000158 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 60 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.15% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000159
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000159 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 61 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.17% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000166
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000166 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 62 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.19% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000301
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000301 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 63 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.21% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000333 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 64 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.22% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000338
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000338 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 65 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000400
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000400 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 66 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000401
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000401 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 67 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000402
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000402 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 68 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.30% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000403
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000403 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 69 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.32% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000404
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000404 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 70 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.34% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000407
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000407 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 71 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.36% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000408
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000408 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 72 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.38% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000409
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000409 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 73 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.40% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000410
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000410 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 74 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.42% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000411
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000411 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 75 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.44% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000415
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000415 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 76 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.46% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000417
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000417 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 77 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.47% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000419
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000419 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 78 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000420
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000420 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 79 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000421
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000421 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 80 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.53% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000422
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000422 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 81 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.55% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000423
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000423 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 82 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.57% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000425
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000425 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 83 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.59% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000426
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000426 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 84 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.61% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000428
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000428 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 85 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.63% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000429
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000429 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 86 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.65% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000430
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000430 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 87 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.67% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000488
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000488 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 88 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.69% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000498
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000498 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 89 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.70% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000501
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000501 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 90 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.72% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000503
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000503 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 91 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000504
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000504 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 92 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.76% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000505
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000505 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 93 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.78% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000506
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000506 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 94 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.80% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000507
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000507 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 95 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.82% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000509
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000509 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 96 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.84% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000510
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000510 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 97 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.86% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000513
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000513 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 98 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.88% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000514
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000514 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 99 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.90% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000516
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000516 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 100 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.92% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000517
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000517 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 101 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.94% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000518
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000518 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 102 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.95% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000519
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000519 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 103 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000520
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000520 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 104 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000521
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000521 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 105 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000523
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000523 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 106 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000524
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000524 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 107 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.05% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000525
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000525 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 108 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.07% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000526
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000526 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 109 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.09% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000528
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000528 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 110 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.11% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000529
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000529 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 111 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.13% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000530
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000530 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 112 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.15% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000531
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000531 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 113 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.17% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000532
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000532 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 114 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.19% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000533
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000533 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 115 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.20% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000534
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000534 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 116 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.22% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000536
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000536 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 117 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000537
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000537 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 118 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000538
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000538 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 119 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000539
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000539 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 120 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.30% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000541
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000541 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 121 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.32% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000543
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000543 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 122 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.34% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000544
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000544 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 123 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.36% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000545
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000545 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 124 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.38% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000546
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000546 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 125 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.40% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000547
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000547 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 126 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.42% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000548
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000548 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 127 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.43% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000550
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000550 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 128 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.45% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000551
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000551 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 129 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.47% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000552
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000552 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 130 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000553
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000553 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 131 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000554
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000554 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 132 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.53% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000555
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000555 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 133 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.55% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000557
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000557 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 134 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.57% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000558
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000558 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 135 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.59% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000559
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000559 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 136 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.61% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000560
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000560 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 137 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.63% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000561
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000561 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 138 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.65% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000563
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000563 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 139 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.67% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000564
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000564 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 140 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.68% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000565
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000565 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 141 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.70% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000566
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000566 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 142 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.72% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000567
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000567 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 143 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000568
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000568 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 144 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.76% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000570
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000570 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 145 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.78% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000571
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000571 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 146 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.80% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000572
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000572 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 147 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.82% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000573
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000573 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 148 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.84% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000576
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000576 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 149 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.86% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000581
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000581 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 150 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.88% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000582
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000582 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 151 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.90% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000586
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000586 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 152 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.92% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000589
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000589 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 153 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.93% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000590
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000590 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 154 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.95% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000591
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000591 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 155 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000592
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000592 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 156 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 2.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000593
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000593 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 157 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000595
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000595 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 158 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000596
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000596 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 159 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.05% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000597
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000597 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 160 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.07% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000598
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000598 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 161 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.09% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000599
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000599 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 162 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.11% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000600
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000600 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 163 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.13% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000601
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000601 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 164 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.15% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000603
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000603 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 165 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.17% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000605
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000605 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 166 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.18% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000607
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000607 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 167 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.20% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000608
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000608 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 168 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.22% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000609
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000609 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 169 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000610
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000610 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 170 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000612
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000612 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 171 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000615
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000615 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 172 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.30% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000617
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000617 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 173 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.32% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000619
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000619 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 174 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.34% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000620
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000620 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 175 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.36% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000623
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000623 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 176 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.38% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000625
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000625 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 177 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.40% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000626
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000626 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 178 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.41% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000628
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000628 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 179 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.43% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000629
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000629 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 180 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.45% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000630
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000630 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 181 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.47% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000631
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000631 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 182 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000632
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000632 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 183 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000633
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000633 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 184 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.53% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000635
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000635 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 185 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.55% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000636
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000636 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 186 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.57% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000637
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000637 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 187 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.59% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000639
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000639 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 188 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.61% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000650
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000650 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 189 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.63% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000651
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000651 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 190 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.65% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000652
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000652 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 191 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.66% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000655
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000655 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 192 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.68% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000656
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000656 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 193 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.70% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000657
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000657 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 194 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.72% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000659
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000659 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 195 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000661
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000661 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 196 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.76% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000663
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000663 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 197 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.78% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000665
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000665 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 198 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.80% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000668
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000668 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 199 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.82% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000669
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000669 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 200 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.84% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000670
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000670 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 201 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.86% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000672
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000672 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 202 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.88% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000676
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000676 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 203 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.90% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000677
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000677 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 204 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.91% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000678
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000678 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 205 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.93% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000679
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000679 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 206 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.95% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000680
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000680 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 207 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000681
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000681 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 208 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 3.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000682
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000682 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 209 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000683
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000683 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 210 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000685
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000685 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 211 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.05% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000686
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000686 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 212 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.07% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000688
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000688 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 213 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.09% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000690
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000690 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 214 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.11% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000691
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000691 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 215 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.13% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000692
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000692 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 216 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.14% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000695
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000695 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 217 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.16% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000697
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000697 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 218 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.18% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000698
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000698 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 219 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.20% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000700
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000700 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 220 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.22% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000701
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000701 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 221 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000702
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000702 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 222 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000703
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000703 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 223 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000705
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000705 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 224 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.30% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000707
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000707 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 225 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.32% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000708
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000708 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 226 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.34% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000709
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000709 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 227 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.36% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000710
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000710 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 228 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.38% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000711
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000711 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 229 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.39% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000712
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000712 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 230 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.41% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000713
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000713 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 231 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.43% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000715
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000715 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 232 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.45% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000716
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000716 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 233 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.47% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000717
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000717 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 234 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000718
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000718 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 235 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000719
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000719 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 236 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.53% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000720
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000720 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 237 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.55% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000721
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000721 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 238 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.57% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000722
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000722 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 239 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.59% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000723
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000723 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 240 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.61% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000725
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000725 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 241 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.63% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000726
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000726 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 242 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.64% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000727
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000727 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 243 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.66% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000728
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000728 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 244 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.68% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000729
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000729 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 245 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.70% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000731
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000731 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 246 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.72% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000733
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000733 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 247 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000735
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000735 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 248 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.76% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000736
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000736 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 249 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.78% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000737
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000737 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 250 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.80% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000738
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000738 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 251 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.82% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000739
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000739 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 252 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.84% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000750
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000750 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 253 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.86% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000751
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000751 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 254 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.87% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000752
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000752 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 255 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.89% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000753
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000753 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 256 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.91% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000755
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000755 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 257 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.93% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000756
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000756 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 258 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.95% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000757
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000757 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 259 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000758
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000758 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 260 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 4.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000759
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000759 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 261 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000761
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000761 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 262 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000762
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000762 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 263 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.05% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000766
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000766 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 264 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.07% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000767
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000767 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 265 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.09% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000768
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000768 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 266 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.11% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000776
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000776 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 267 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.12% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000777
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000777 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 268 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.14% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000778
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000778 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 269 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.16% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000779
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000779 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 270 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.18% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000782
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000782 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 271 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.20% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000783
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000783 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 272 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.22% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000785
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000785 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 273 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000786
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000786 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 274 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000788
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000788 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 275 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000789
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000789 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 276 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.30% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000790
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000790 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 277 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.32% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000791
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000791 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 278 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.34% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000792
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000792 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 279 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.36% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000793
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000793 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 280 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.37% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000795
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000795 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 281 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.39% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000796
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000796 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 282 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.41% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000797
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000797 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 283 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.43% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000798
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000798 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 284 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.45% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000799
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000799 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 285 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.47% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000800
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000800 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 286 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000801
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000801 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 287 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000802
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000802 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 288 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.53% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000803
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000803 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 289 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.55% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000807
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000807 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 290 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.57% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000809
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000809 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 291 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.59% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000810
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000810 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 292 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.60% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000811
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000811 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 293 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.62% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000812
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000812 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 294 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.64% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000813
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000813 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 295 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.66% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000815
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000815 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 296 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.68% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000816
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000816 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 297 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.70% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000818
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000818 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 298 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.72% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000819
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000819 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 299 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000820
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000820 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 300 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.76% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000821
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000821 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 301 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.78% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000822
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000822 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 302 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.80% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000823
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000823 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 303 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.82% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000825
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000825 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 304 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.84% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000826
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000826 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 305 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.85% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000828
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000828 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 306 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.87% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000829
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000829 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 307 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.89% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000830
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000830 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 308 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.91% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000831
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000831 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 309 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.93% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000833
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000833 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 310 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.95% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000837
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000837 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 311 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000838
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000838 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 312 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 5.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000839
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000839 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 313 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000848
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000848 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 314 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000850
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000850 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 315 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.05% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000852
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000852 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 316 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.07% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000856
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000856 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 317 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.09% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000858
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000858 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 318 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.10% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000859
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000859 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 319 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.12% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000860
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000860 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 320 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.14% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000862
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000862 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 321 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.16% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000863
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000863 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 322 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.18% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000868
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000868 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 323 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.20% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000869
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000869 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 324 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.22% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000875
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000875 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 325 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000876
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000876 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 326 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000877
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000877 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 327 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000878
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000878 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 328 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.30% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000880
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000880 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 329 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.32% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000881
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000881 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 330 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.34% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000882
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000882 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 331 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.35% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000883
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000883 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 332 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.37% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000885
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000885 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 333 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.39% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000886
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000886 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 334 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.41% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000887
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000887 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 335 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.43% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000888
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000888 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 336 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.45% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000889
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000889 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 337 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.47% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000890
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000890 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 338 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000892
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000892 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 339 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000893
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000893 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 340 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.53% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000895
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000895 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 341 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.55% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000897
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000897 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 342 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.57% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000898
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000898 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 343 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.58% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000899
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000899 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 344 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.60% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000900
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000900 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 345 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.62% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000901
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000901 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 346 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.64% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000902
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000902 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 347 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.66% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000903
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000903 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 348 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.68% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000905
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000905 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 349 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.70% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000906
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000906 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 350 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.72% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000908
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000908 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 351 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000909
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000909 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 352 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.76% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000910
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000910 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 353 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.78% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000911
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000911 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 354 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.80% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000912
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000912 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 355 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.82% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000913
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000913 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 356 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.83% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000915
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000915 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 357 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.85% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000917
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000917 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 358 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.87% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000919
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000919 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 359 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.89% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000920
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000920 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 360 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.91% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000921
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000921 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 361 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.93% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000922
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000922 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 362 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.95% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000923
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000923 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 363 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000925
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000925 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 364 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 6.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000926
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000926 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 365 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000927
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000927 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 366 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000928
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000928 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 367 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.05% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000929
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000929 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 368 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.07% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000930
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000930 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 369 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.08% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000931
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000931 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 370 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.10% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000932
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000932 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 371 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.12% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000933
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000933 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 372 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.14% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000935
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000935 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 373 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.16% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000936
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000936 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 374 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.18% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000937
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000937 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 375 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.20% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000938
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000938 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 376 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.22% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000948
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000948 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 377 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000949
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000949 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 378 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000950
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000950 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 379 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000951
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000951 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 380 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.30% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000952
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000952 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 381 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.31% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000953
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000953 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 382 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.33% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000955
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000955 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 383 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.35% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000957
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000957 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 384 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.37% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000958
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000958 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 385 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.39% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000959
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000959 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 386 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.41% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000960
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000960 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 387 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.43% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000962
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000962 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 388 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.45% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000963
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000963 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 389 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.47% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000965
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000965 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 390 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000966
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000966 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 391 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000967
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000967 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 392 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.53% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000968
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000968 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 393 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.55% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000969
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000969 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 394 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.56% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000970
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000970 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 395 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.58% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000972
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000972 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 396 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.60% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000973
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000973 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 397 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.62% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000975
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000975 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 398 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.64% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000977
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000977 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 399 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.66% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000978
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000978 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 400 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.68% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000980
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000980 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 401 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.70% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000981
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000981 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 402 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.72% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000983
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000983 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 403 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000985
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000985 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 404 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.76% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000987
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000987 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 405 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.78% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000988
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000988 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 406 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.80% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000989
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000989 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 407 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.81% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000990
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000990 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 408 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.83% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000993
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000993 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 409 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.85% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000995
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000995 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 410 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.87% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000997
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000997 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 411 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.89% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000998
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000998 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 412 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.91% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000999
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000999 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 413 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.93% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001201
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001201 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 414 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.95% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001202
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001202 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 415 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001203
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001203 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 416 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 7.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001205
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001205 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 417 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001206
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001206 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 418 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001207
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001207 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 419 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.04% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001208
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001208 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 420 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.06% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001209
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001209 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 421 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.08% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001210
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001210 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 422 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.10% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001211
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001211 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 423 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.12% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001212
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001212 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 424 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.14% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001213
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001213 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 425 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.16% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001215
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001215 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 426 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.18% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001216
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001216 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 427 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.20% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001217
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001217 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 428 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.22% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001218
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001218 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 429 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001219
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001219 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 430 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001220
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001220 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 431 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001221
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001221 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 432 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.29% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001222
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001222 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 433 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.31% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001223
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001223 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 434 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.33% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001225
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001225 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 435 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.35% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001226
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001226 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 436 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.37% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001227
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001227 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 437 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.39% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001228
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001228 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 438 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.41% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001229
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001229 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 439 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.43% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001230
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001230 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 440 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.45% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001231
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001231 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 441 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.47% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001233
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001233 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 442 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001234
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001234 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 443 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001236
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001236 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 444 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.53% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001237
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001237 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 445 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.54% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001238
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001238 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 446 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.56% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001239
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001239 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 447 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.58% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001248
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001248 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 448 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.60% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001255
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001255 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 449 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.62% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001256
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001256 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 450 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.64% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001257
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001257 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 451 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.66% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001258
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001258 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 452 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.68% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001259
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001259 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 453 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.70% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001260
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001260 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 454 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.72% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001266
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001266 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 455 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001267
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001267 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 456 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.76% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001268
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001268 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 457 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.78% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001269
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001269 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 458 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.79% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001270
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001270 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 459 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.81% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001277
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001277 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 460 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.83% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001278
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001278 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 461 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.85% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001279
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001279 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 462 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.87% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001280
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001280 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 463 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.89% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001282
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001282 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 464 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.91% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001283
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001283 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 465 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.93% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001285
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001285 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 466 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.95% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001286
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001286 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 467 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001287
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001287 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 468 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 8.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001288
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001288 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 469 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001289
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001289 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 470 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.02% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001296
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001296 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 471 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.04% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001298
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001298 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 472 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.06% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001299
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001299 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 473 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.08% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001300
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001300 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 474 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.10% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001301
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001301 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 475 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.12% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001306
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001306 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 476 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.14% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001308
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001308 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 477 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.16% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001309
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001309 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 478 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.18% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001311
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001311 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 479 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.20% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001312
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001312 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 480 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.22% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001313
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001313 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 481 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001314
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001314 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 482 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001316
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001316 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 483 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.27% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001317
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001317 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 484 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.29% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001318
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001318 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 485 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.31% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001319
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001319 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 486 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.33% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001322
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001322 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 487 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.35% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001323
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001323 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 488 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.37% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001324
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001324 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 489 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.39% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001325
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001325 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 490 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.41% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001326
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001326 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 491 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.43% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001328
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001328 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 492 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.45% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001330
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001330 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 493 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.47% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001331
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001331 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 494 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001332
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001332 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 495 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001333 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 496 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.52% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001335
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001335 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 497 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.54% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001336
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001336 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 498 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.56% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001337
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001337 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 499 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.58% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001338
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001338 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 500 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.60% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001339
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001339 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 501 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.62% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001356
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001356 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 502 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.64% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001358
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001358 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 503 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.66% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001359
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001359 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 504 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.68% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001360
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001360 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 505 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.70% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001365
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001365 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 506 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.72% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001366
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001366 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 507 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001367
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001367 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 508 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.75% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001368
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001368 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 509 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.77% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001369
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001369 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 510 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.79% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001373
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001373 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 511 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.81% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001376
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001376 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 512 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.83% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001378
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001378 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 513 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.85% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001379
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001379 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 514 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.87% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001380
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001380 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 515 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.89% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001382
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001382 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 516 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.91% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001386
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001386 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 517 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.93% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001387
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001387 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 518 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.95% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001388
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001388 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 519 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001389
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001389 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 520 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 9.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001390
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001390 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 521 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001391
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001391 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 522 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001393
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001393 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 523 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001395
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001395 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 524 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001396
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001396 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 525 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001399
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001399 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 526 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001400
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001400 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 527 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001696
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001696 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 528 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001872
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001872 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 529 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001896
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001896 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 530 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001914
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001914 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 531 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001965
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001965 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 532 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 001979
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 001979 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 533 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002001
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002001 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 534 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002003
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002003 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 535 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002004
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002004 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 536 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002005
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002005 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 537 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002006 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 538 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002007 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 539 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002008 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 540 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002009 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 541 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002010
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002010 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 542 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002011 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 543 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002012
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002012 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 544 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002014
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002014 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 545 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002015
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002015 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 546 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002016 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 547 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002017
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002017 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 548 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002019
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002019 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 549 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002020 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 550 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002021
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002021 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 551 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002022
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002022 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 552 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002023
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002023 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 553 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002024
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002024 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 554 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002025
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002025 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 555 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002026
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002026 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 556 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002027
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002027 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 557 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002028
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002028 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 558 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002029
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002029 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 559 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002030
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002030 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 560 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002031
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002031 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 561 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002032
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002032 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 562 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002033
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002033 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 563 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002034
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002034 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 564 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002035
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002035 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 565 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002036
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002036 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 566 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002037
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002037 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 567 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002038
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002038 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 568 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002039
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002039 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 569 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002040
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002040 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 570 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002041
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002041 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 571 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002042
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002042 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 572 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 10.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002043
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002043 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 573 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002044
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002044 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 574 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002045
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002045 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 575 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002046
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002046 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 576 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002047
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002047 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 577 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002048
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002048 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 578 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002049
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002049 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 579 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002050
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002050 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 580 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002051
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002051 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 581 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002052
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002052 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 582 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002053
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002053 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 583 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002054
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002054 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 584 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002055
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002055 from 2025-05-23 to 2026-07-07

__enter__
'NoneType' object has no attribute 'columns'

QUANTAXIS>> The 585 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002056
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002056 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 586 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002057
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002057 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 587 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002058
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002058 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 588 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002059
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002059 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 589 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002060
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002060 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 590 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002061
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002061 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 591 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002062
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002062 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 592 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002063
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002063 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 593 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002064
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002064 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 594 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002065
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002065 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 595 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002066
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002066 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 596 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002067
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002067 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 597 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002068
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002068 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 598 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002069
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002069 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 599 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002072
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002072 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 600 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002073
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002073 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 601 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002074
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002074 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 602 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002075
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002075 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 603 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002076
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002076 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 604 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002077
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002077 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 605 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002078
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002078 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 606 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002079
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002079 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 607 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002080
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002080 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 608 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002081
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002081 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 609 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002082
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002082 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 610 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002083
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002083 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 611 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002084
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002084 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 612 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002085
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002085 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 613 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002086
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002086 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 614 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002088
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002088 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 615 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002090
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002090 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 616 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002091
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002091 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 617 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002092
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002092 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 618 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002093
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002093 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 619 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002094
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002094 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 620 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002095
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002095 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 621 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002096
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002096 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 622 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002097
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002097 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 623 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002098
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002098 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 624 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 11.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002099
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002099 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 625 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002100
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002100 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 626 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002101
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002101 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 627 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002102
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002102 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 628 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002103
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002103 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 629 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002104
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002104 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 630 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002105
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002105 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 631 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002106
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002106 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 632 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002107
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002107 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 633 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002108
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002108 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 634 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002109
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002109 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 635 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002110
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002110 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 636 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002111
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002111 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 637 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002112
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002112 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 638 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002114
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002114 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 639 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002115
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002115 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 640 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002116
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002116 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 641 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002117
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002117 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 642 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002119
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002119 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 643 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002120
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002120 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 644 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002121
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002121 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 645 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002122
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002122 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 646 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002123
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002123 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 647 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002124
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002124 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 648 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002125
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002125 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 649 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002126
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002126 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 650 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002127
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002127 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 651 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002128
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002128 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 652 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002129
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002129 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 653 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002130
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002130 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 654 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002131
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002131 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 655 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002132
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002132 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 656 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002133
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002133 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 657 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002134
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002134 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 658 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002135
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002135 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 659 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002136
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002136 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 660 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002137
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002137 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 661 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002138
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002138 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 662 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002139
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002139 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 663 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002140
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002140 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 664 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002141
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002141 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 665 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002142
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002142 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 666 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002144
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002144 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 667 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002145
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002145 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 668 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002146
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002146 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 669 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002148
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002148 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 670 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002149
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002149 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 671 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002150
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002150 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 672 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002151
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002151 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 673 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002152
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002152 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 674 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002153
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002153 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 675 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002154
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002154 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 676 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 12.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002155
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002155 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 677 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002156
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002156 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 678 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002157
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002157 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 679 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002158
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002158 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 680 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002159
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002159 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 681 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002160
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002160 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 682 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002161
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002161 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 683 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002162
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002162 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 684 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002163
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002163 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 685 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002164
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002164 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 686 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002165
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002165 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 687 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002166
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002166 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 688 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002167
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002167 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 689 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002168
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002168 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 690 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002169
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002169 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 691 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002170
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002170 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 692 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002171
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002171 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 693 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002172
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002172 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 694 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002173
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002173 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 695 of Total 5205

name 'date' is not defined

QUANTAXIS>> DOWNLOAD PROGRESS 13.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002174
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002174 from 2025-05-23 to 2026-07-07
QUANTAXIS>> The 696 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002175
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002175 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 697 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002176
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002176 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 698 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002177
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002177 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 699 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002178
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002178 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 700 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002179
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002179 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 701 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002180
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002180 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 702 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002181
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002181 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 703 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002182
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002182 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 704 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002183
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002183 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 705 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002184
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002184 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 706 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002185
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002185 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 707 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002186
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002186 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 708 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002187
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002187 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 709 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002188
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002188 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 710 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002189
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002189 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 711 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002190
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002190 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 712 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002191
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002191 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 713 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002192
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002192 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 714 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002193
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002193 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 715 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002194
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002194 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 716 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002195
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002195 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 717 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002196
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002196 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 718 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002197
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002197 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 719 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002198
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002198 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 720 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002199
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002199 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 721 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002200
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002200 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 722 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002201
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002201 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 723 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002202
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002202 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 724 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002203
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002203 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 725 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002204
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002204 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 726 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002205
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002205 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 727 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002206
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002206 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 728 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 13.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002207
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002207 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 729 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002208
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002208 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 730 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002209
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002209 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 731 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002210
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002210 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 732 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002211
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002211 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 733 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002212
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002212 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 734 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002213
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002213 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 735 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002214
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002214 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 736 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002215
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002215 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 737 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002216
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002216 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 738 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002217
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002217 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 739 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002218
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002218 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 740 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002219
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002219 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 741 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002221
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002221 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 742 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002222
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002222 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 743 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002223
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002223 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 744 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002224
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002224 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 745 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002225
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002225 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 746 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002226
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002226 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 747 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002227
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002227 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 748 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002228
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002228 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 749 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002229
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002229 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 750 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002230
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002230 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 751 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002232
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002232 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 752 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002233
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002233 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 753 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002234
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002234 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 754 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002235
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002235 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 755 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002236
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002236 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 756 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002237
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002237 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 757 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002238
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002238 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 758 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002239
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002239 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 759 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002240
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002240 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 760 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002241
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002241 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 761 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002242
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002242 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 762 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002243
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002243 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 763 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002244
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002244 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 764 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002245
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002245 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 765 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002246
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002246 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 766 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002247
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002247 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 767 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002248
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002248 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 768 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002249
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002249 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 769 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002250
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002250 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 770 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002251
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002251 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 771 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002252
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002252 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 772 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002253
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002253 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 773 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002254
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002254 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 774 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002255
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002255 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 775 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002256
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002256 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 776 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002258
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002258 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 777 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002259
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002259 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 778 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002261
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002261 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 779 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002262
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002262 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 780 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 14.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002263
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002263 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 781 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002264
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002264 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 782 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002265
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002265 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 783 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002266
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002266 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 784 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002267
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002267 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 785 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002268
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002268 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 786 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002269
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002269 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 787 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002270
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002270 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 788 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002271
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002271 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 789 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002272
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002272 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 790 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002273
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002273 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 791 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002274
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002274 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 792 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002275
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002275 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 793 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002276
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002276 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 794 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002277
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002277 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 795 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002278
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002278 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 796 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002279
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002279 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 797 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002281
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002281 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 798 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002282
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002282 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 799 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002283
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002283 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 800 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002284
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002284 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 801 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002285
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002285 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 802 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002286
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002286 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 803 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002287
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002287 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 804 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002289
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002289 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 805 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002290
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002290 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 806 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002291
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002291 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 807 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002292
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002292 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 808 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002293
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002293 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 809 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002294
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002294 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 810 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002295
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002295 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 811 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002296
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002296 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 812 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002297
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002297 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 813 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002298
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002298 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 814 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002299
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002299 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 815 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002300
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002300 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 816 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002301
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002301 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 817 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002302
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002302 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 818 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002303
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002303 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 819 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002304
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002304 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 820 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002305
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002305 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 821 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002306
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002306 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 822 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002307
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002307 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 823 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002309
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002309 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 824 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002310
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002310 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 825 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002311
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002311 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 826 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002312
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002312 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 827 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002313
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002313 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 828 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002314
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002314 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 829 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002315
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002315 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 830 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002316
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002316 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 831 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002317
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002317 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 832 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 15.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002318
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002318 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 833 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002319
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002319 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 834 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002320
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002320 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 835 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002321
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002321 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 836 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002322
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002322 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 837 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002323
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002323 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 838 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002324
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002324 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 839 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002326
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002326 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 840 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002327
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002327 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 841 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002328
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002328 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 842 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002329
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002329 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 843 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002330
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002330 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 844 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002331
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002331 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 845 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002332
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002332 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 846 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002333 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 847 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002334
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002334 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 848 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002335
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002335 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 849 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002337
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002337 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 850 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002338
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002338 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 851 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002339
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002339 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 852 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002340
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002340 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 853 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002342
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002342 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 854 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002343
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002343 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 855 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002344
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002344 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 856 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002345
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002345 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 857 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002346
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002346 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 858 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002347
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002347 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 859 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002348
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002348 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 860 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002349
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002349 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 861 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002350
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002350 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 862 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002351
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002351 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 863 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002352
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002352 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 864 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002353
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002353 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 865 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002354
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002354 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 866 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002355
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002355 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 867 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002356
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002356 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 868 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002357
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002357 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 869 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002358
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002358 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 870 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002360
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002360 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 871 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002361
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002361 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 872 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002362
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002362 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 873 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002363
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002363 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 874 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002364
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002364 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 875 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002365
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002365 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 876 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002366
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002366 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 877 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002367
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002367 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 878 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002368
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002368 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 879 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002369
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002369 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 880 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002370
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002370 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 881 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002371
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002371 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 882 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002372
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002372 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 883 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002373
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002373 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 884 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 16.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002374
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002374 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 885 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002375
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002375 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 886 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002376
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002376 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 887 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002377
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002377 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 888 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002378
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002378 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 889 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002379
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002379 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 890 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002380
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002380 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 891 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002381
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002381 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 892 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002382
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002382 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 893 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002383
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002383 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 894 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002384
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002384 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 895 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002385
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002385 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 896 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002386
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002386 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 897 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002387
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002387 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 898 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002388
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002388 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 899 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002389
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002389 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 900 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002390
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002390 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 901 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002391
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002391 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 902 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002392
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002392 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 903 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002393
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002393 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 904 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002394
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002394 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 905 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002395
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002395 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 906 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002396
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002396 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 907 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002397
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002397 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 908 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002398
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002398 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 909 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002399
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002399 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 910 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002400
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002400 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 911 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002401
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002401 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 912 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002402
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002402 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 913 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002403
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002403 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 914 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002404
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002404 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 915 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002405
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002405 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 916 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002406
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002406 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 917 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002407
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002407 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 918 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002408
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002408 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 919 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002409
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002409 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 920 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002410
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002410 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 921 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002412
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002412 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 922 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002413
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002413 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 923 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002414
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002414 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 924 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002415
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002415 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 925 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002416
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002416 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 926 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002418
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002418 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 927 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002419
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002419 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 928 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002420
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002420 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 929 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002421
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002421 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 930 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002422
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002422 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 931 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002423
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002423 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 932 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002424
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002424 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 933 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002425
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002425 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 934 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002426
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002426 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 935 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002427
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002427 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 936 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 17.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002428
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002428 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 937 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002429
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002429 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 938 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002430
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002430 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 939 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002431
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002431 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 940 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002432
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002432 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 941 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002434
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002434 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 942 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002436
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002436 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 943 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002437
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002437 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 944 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002438
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002438 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 945 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002439
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002439 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 946 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002440
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002440 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 947 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002441
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002441 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 948 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002442
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002442 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 949 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002443
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002443 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 950 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002444
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002444 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 951 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002445
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002445 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 952 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002446
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002446 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 953 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002448
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002448 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 954 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002449
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002449 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 955 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002451
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002451 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 956 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002452
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002452 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 957 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002453
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002453 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 958 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002454
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002454 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 959 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002455
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002455 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 960 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002456
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002456 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 961 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002457
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002457 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 962 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002458
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002458 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 963 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002459
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002459 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 964 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002460
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002460 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 965 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002461
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002461 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 966 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002462
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002462 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 967 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002463
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002463 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 968 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002465
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002465 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 969 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002466
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002466 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 970 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002467
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002467 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 971 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002468
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002468 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 972 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002469
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002469 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 973 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002470
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002470 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 974 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002471
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002471 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 975 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002472
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002472 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 976 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002474
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002474 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 977 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002475
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002475 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 978 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002476
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002476 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 979 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002478
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002478 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 980 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002479
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002479 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 981 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002480
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002480 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 982 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002481
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002481 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 983 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002482
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002482 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 984 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002483
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002483 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 985 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002484
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002484 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 986 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002485
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002485 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 987 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002486
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002486 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 988 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 18.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002487
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002487 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 989 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002488
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002488 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 990 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002489
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002489 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 991 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002490
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002490 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 992 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002491
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002491 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 993 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002492
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002492 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 994 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002493
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002493 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 995 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002494
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002494 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 996 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002495
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002495 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 997 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002496
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002496 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 998 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002497
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002497 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 999 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002498
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002498 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1000 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002500
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002500 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1001 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002501
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002501 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1002 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002506
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002506 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1003 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002507
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002507 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1004 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002508
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002508 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1005 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002510
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002510 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1006 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002511
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002511 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1007 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002512
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002512 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1008 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002513
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002513 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1009 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002514
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002514 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1010 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002515
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002515 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1011 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002516
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002516 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1012 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002517
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002517 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1013 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002518
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002518 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1014 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002519
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002519 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1015 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002520
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002520 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1016 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002521
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002521 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1017 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002522
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002522 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1018 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002523
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002523 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1019 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002524
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002524 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1020 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002526
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002526 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1021 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002527
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002527 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1022 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002528
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002528 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1023 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002529
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002529 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1024 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002530
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002530 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1025 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002531
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002531 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1026 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002532
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002532 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1027 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002533
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002533 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1028 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002534
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002534 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1029 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002535
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002535 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1030 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002536
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002536 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1031 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002537
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002537 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1032 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002538
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002538 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1033 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002539
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002539 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1034 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002540
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002540 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1035 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002541
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002541 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1036 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002542
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002542 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1037 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002543
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002543 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1038 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002544
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002544 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1039 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002545
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002545 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1040 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 19.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002546
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002546 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1041 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002547
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002547 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1042 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002548
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002548 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1043 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002549
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002549 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1044 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002550
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002550 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1045 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002551
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002551 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1046 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002552
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002552 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1047 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002553
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002553 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1048 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002554
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002554 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1049 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002555
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002555 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1050 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002556
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002556 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1051 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002557
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002557 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1052 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002558
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002558 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1053 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002559
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002559 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1054 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002560
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002560 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1055 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002561
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002561 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1056 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002562
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002562 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1057 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002563
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002563 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1058 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002564
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002564 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1059 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002565
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002565 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1060 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002566
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002566 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1061 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002567
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002567 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1062 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002568
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002568 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1063 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002569
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002569 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1064 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002570
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002570 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1065 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002571
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002571 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1066 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002572
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002572 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1067 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002573
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002573 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1068 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002574
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002574 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1069 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002575
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002575 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1070 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002576
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002576 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1071 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002577
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002577 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1072 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002578
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002578 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1073 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002579
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002579 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1074 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002580
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002580 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1075 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002581
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002581 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1076 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002582
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002582 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1077 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002583
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002583 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1078 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002584
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002584 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1079 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002585
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002585 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1080 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002586
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002586 from 2025-05-09 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1081 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002587
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002587 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1082 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002588
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002588 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1083 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002589
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002589 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1084 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002590
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002590 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1085 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002591
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002591 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1086 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002592
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002592 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1087 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002593
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002593 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1088 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002594
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002594 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1089 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002595
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002595 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1090 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002596
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002596 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1091 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002597
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002597 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1092 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002598
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002598 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1093 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 20.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002599
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002599 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1094 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002600
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002600 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1095 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002601
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002601 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1096 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002602
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002602 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1097 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002603
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002603 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1098 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002605
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002605 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1099 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002606
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002606 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1100 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002607
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002607 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1101 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002608
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002608 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1102 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002609
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002609 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1103 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002611
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002611 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1104 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002612
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002612 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1105 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002613
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002613 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1106 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002614
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002614 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1107 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002615
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002615 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1108 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002616
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002616 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1109 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002617
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002617 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1110 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002620
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002620 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1111 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002622
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002622 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1112 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002623
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002623 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1113 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002624
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002624 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1114 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002625
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002625 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1115 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002626
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002626 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1116 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002627
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002627 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1117 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002628
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002628 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1118 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002629
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002629 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1119 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002630
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002630 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1120 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002631
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002631 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1121 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002632
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002632 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1122 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002633
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002633 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1123 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002634
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002634 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1124 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002635
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002635 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1125 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002636
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002636 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1126 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002637
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002637 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1127 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002638
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002638 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1128 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002639
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002639 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1129 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002640
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002640 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1130 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002641
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002641 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1131 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002642
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002642 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1132 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002643
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002643 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1133 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002644
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002644 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1134 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002645
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002645 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1135 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002646
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002646 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1136 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002647
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002647 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1137 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002648
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002648 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1138 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002649
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002649 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1139 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002650
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002650 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1140 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002651
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002651 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1141 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002652
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002652 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1142 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002653
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002653 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1143 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002654
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002654 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1144 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002655
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002655 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1145 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 21.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002656
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002656 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1146 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002657
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002657 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1147 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002658
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002658 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1148 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002659
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002659 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1149 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002660
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002660 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1150 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002661
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002661 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1151 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002662
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002662 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1152 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002663
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002663 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1153 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002664
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002664 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1154 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002666
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002666 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1155 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002667
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002667 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1156 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002668
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002668 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1157 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002669
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002669 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1158 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002670
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002670 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1159 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002671
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002671 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1160 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002672
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002672 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1161 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002673
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002673 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1162 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002674
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002674 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1163 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002675
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002675 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1164 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002676
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002676 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1165 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002677
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002677 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1166 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002678
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002678 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1167 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002679
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002679 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1168 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002681
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002681 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1169 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002682
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002682 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1170 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002683
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002683 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1171 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002685
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002685 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1172 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002686
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002686 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1173 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002687
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002687 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1174 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002688
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002688 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1175 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002689
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002689 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1176 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002690
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002690 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1177 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002691
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002691 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1178 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002692
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002692 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1179 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002693
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002693 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1180 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002694
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002694 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1181 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002695
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002695 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1182 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002696
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002696 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1183 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002697
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002697 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1184 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002698
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002698 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1185 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002700
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002700 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1186 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002701
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002701 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1187 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002702
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002702 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1188 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002703
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002703 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1189 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002705
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002705 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1190 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002706
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002706 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1191 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002707
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002707 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1192 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002708
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002708 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1193 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002709
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002709 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1194 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002712
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002712 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1195 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002713
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002713 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1196 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002714
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002714 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1197 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 22.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002715
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002715 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1198 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002716
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002716 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1199 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002717
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002717 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1200 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002718
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002718 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1201 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002719
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002719 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1202 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002721
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002721 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1203 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002722
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002722 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1204 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002723
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002723 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1205 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002724
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002724 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1206 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002725
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002725 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1207 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002726
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002726 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1208 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002727
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002727 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1209 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002728
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002728 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1210 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002729
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002729 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1211 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002730
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002730 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1212 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002731
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002731 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1213 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002732
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002732 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1214 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002733
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002733 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1215 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002734
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002734 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1216 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002735
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002735 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1217 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002736
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002736 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1218 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002737
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002737 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1219 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002738
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002738 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1220 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002739
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002739 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1221 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002741
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002741 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1222 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002742
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002742 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1223 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002743
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002743 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1224 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002745
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002745 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1225 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002746
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002746 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1226 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002747
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002747 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1227 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002748
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002748 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1228 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002749
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002749 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1229 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002752
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002752 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1230 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002753
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002753 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1231 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002755
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002755 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1232 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002756
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002756 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1233 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002757
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002757 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1234 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002758
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002758 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1235 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002759
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002759 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1236 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002760
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002760 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1237 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002761
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002761 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1238 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002762
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002762 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1239 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002763
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002763 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1240 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002765
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002765 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1241 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002766
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002766 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1242 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002767
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002767 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1243 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002768
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002768 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1244 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002769
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002769 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1245 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002771
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002771 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1246 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002772
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002772 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1247 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002773
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002773 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1248 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002774
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002774 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1249 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 23.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002775
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002775 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1250 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002777
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002777 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1251 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002778
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002778 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1252 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002779
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002779 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1253 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002780
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002780 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1254 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002782
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002782 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1255 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002783
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002783 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1256 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002785
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002785 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1257 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002786
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002786 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1258 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002787
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002787 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1259 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002788
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002788 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1260 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002789
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002789 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1261 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002790
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002790 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1262 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002791
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002791 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1263 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002792
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002792 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1264 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002793
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002793 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1265 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002795
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002795 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1266 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002796
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002796 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1267 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002797
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002797 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1268 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002798
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002798 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1269 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002799
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002799 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1270 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002800
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002800 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1271 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002801
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002801 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1272 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002802
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002802 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1273 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002803
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002803 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1274 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002805
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002805 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1275 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002806
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002806 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1276 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002807
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002807 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1277 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002808
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002808 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1278 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002809
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002809 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1279 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002810
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002810 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1280 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002811
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002811 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1281 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002812
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002812 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1282 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002813
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002813 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1283 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002815
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002815 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1284 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002816
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002816 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1285 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002817
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002817 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1286 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002818
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002818 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1287 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002819
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002819 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1288 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002820
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002820 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1289 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002821
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002821 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1290 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002822
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002822 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1291 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002823
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002823 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1292 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002824
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002824 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1293 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002825
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002825 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1294 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002826
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002826 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1295 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002827
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002827 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1296 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002828
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002828 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1297 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002829
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002829 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1298 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002830
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002830 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1299 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002831
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002831 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1300 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002832
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002832 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1301 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 24.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002833
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002833 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1302 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002835
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002835 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1303 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002836
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002836 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1304 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002837
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002837 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1305 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002838
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002838 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1306 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002839
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002839 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1307 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002840
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002840 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1308 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002841
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002841 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1309 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002842
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002842 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1310 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002843
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002843 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1311 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002845
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002845 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1312 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002846
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002846 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1313 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002847
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002847 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1314 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002848
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002848 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1315 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002849
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002849 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1316 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002850
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002850 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1317 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002851
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002851 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1318 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002852
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002852 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1319 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002853
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002853 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1320 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002855
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002855 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1321 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002856
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002856 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1322 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002857
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002857 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1323 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002858
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002858 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1324 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002859
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002859 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1325 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002860
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002860 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1326 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002861
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002861 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1327 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002862
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002862 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1328 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002863
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002863 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1329 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002864
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002864 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1330 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002865
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002865 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1331 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002866
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002866 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1332 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002867
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002867 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1333 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002868
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002868 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1334 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002869
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002869 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1335 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002870
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002870 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1336 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002871
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002871 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1337 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002872
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002872 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1338 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002873
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002873 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1339 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002875
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002875 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1340 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002876
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002876 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1341 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002877
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002877 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1342 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002878
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002878 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1343 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002879
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002879 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1344 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002880
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002880 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1345 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002881
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002881 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1346 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002882
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002882 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1347 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002883
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002883 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1348 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002884
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002884 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1349 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002885
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002885 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1350 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002886
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002886 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1351 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002887
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002887 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1352 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002888
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002888 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1353 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 25.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002889
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002889 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1354 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002890
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002890 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1355 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002891
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002891 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1356 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002892
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002892 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1357 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002893
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002893 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1358 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002895
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002895 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1359 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002896
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002896 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1360 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002897
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002897 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1361 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002898
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002898 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1362 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002899
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002899 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1363 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002900
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002900 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1364 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002901
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002901 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1365 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002902
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002902 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1366 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002903
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002903 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1367 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002905
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002905 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1368 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002906
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002906 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1369 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002907
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002907 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1370 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002908
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002908 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1371 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002909
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002909 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1372 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002910
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002910 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1373 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002911
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002911 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1374 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002912
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002912 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1375 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002913
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002913 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1376 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002915
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002915 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1377 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002916
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002916 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1378 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002917
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002917 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1379 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002918
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002918 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1380 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002919
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002919 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1381 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002920
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002920 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1382 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002921
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002921 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1383 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002922
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002922 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1384 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002923
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002923 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1385 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002925
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002925 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1386 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002926
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002926 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1387 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002927
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002927 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1388 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002928
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002928 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1389 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002929
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002929 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1390 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002930
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002930 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1391 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002931
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002931 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1392 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002932
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002932 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1393 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002933
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002933 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1394 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002935
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002935 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1395 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002936
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002936 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1396 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002937
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002937 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1397 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002938
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002938 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1398 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002939
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002939 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1399 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002940
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002940 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1400 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002941
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002941 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1401 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002942
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002942 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1402 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002943
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002943 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1403 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002945
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002945 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1404 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002946
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002946 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1405 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 26.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002947
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002947 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1406 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002948
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002948 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1407 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002949
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002949 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1408 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002950
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002950 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1409 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002951
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002951 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1410 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002952
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002952 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1411 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002953
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002953 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1412 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002955
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002955 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1413 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002956
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002956 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1414 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002957
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002957 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1415 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002958
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002958 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1416 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002959
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002959 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1417 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002960
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002960 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1418 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002961
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002961 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1419 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002962
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002962 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1420 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002963
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002963 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1421 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002965
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002965 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1422 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002966
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002966 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1423 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002967
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002967 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1424 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002968
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002968 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1425 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002969
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002969 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1426 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002970
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002970 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1427 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002971
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002971 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1428 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002972
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002972 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1429 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002973
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002973 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1430 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002975
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002975 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1431 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002976
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002976 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1432 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002977
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002977 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1433 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002978
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002978 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1434 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002979
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002979 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1435 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002980
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002980 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1436 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002981
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002981 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1437 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002982
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002982 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1438 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002983
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002983 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1439 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002984
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002984 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1440 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002985
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002985 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1441 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002986
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002986 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1442 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002987
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002987 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1443 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002988
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002988 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1444 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002989
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002989 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1445 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002990
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002990 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1446 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002991
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002991 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1447 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002992
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002992 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1448 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002993
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002993 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1449 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002995
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002995 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1450 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002996
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002996 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1451 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002997
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002997 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1452 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002998
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002998 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1453 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 002999
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 002999 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1454 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003000
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003000 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1455 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003001
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003001 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1456 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003002
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003002 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1457 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 27.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003003
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003003 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1458 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003004
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003004 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1459 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003005
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003005 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1460 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003006 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1461 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003007 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1462 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003008 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1463 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003009 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1464 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003010
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003010 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1465 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003011 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1466 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003012
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003012 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1467 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003013
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003013 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1468 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003015
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003015 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1469 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003016 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1470 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003017
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003017 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1471 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003018
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003018 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1472 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003019
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003019 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1473 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003020 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1474 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003021
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003021 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1475 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003022
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003022 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1476 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003023
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003023 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1477 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003025
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003025 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1478 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003026
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003026 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1479 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003027
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003027 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1480 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003028
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003028 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1481 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003029
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003029 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1482 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003030
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003030 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1483 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003031
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003031 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1484 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003032
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003032 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1485 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003033
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003033 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1486 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003035
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003035 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1487 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003036
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003036 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1488 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003037
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003037 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1489 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003038
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003038 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1490 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003039
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003039 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1491 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003040
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003040 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1492 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003041
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003041 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1493 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003042
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003042 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1494 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003043
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003043 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1495 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 003816
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 003816 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1496 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300001
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300001 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1497 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300002
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300002 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1498 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300003
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300003 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1499 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300004
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300004 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1500 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300005
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300005 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1501 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300006 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1502 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300007 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1503 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300008 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1504 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300009 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1505 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300010
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300010 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1506 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300011 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1507 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300012
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300012 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1508 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300013
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300013 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1509 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 28.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300014
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300014 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1510 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300015
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300015 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1511 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300016 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1512 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300017
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300017 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1513 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300018
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300018 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1514 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300019
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300019 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1515 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300020 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1516 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300021
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300021 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1517 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300022
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300022 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1518 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300024
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300024 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1519 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300025
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300025 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1520 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300026
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300026 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1521 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300027
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300027 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1522 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300029
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300029 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1523 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300030
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300030 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1524 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300031
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300031 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1525 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300032
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300032 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1526 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300033
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300033 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1527 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300034
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300034 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1528 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300035
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300035 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1529 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300036
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300036 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1530 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300037
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300037 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1531 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300039
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300039 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1532 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300040
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300040 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1533 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300041
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300041 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1534 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300042
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300042 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1535 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300043
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300043 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1536 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300044
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300044 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1537 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300045
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300045 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1538 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300046
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300046 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1539 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300047
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300047 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1540 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300048
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300048 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1541 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300049
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300049 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1542 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300050
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300050 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1543 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300051
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300051 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1544 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300052
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300052 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1545 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300053
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300053 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1546 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300054
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300054 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1547 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300055
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300055 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1548 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300056
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300056 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1549 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300057
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300057 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1550 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300058
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300058 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1551 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300059
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300059 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1552 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300061
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300061 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1553 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300062
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300062 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1554 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300063
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300063 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1555 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300065
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300065 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1556 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300066
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300066 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1557 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300067
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300067 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1558 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300068
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300068 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1559 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300069
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300069 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1560 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300070
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300070 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1561 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 29.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300071
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300071 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1562 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300072
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300072 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1563 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300073
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300073 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1564 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300074
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300074 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1565 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300075
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300075 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1566 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300076
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300076 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1567 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300077
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300077 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1568 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300078
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300078 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1569 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300079
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300079 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1570 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300080
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300080 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1571 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300081
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300081 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1572 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300082
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300082 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1573 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300083
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300083 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1574 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300084
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300084 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1575 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300085
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300085 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1576 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300086
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300086 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1577 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300087
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300087 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1578 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300088
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300088 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1579 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300091
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300091 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1580 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300092
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300092 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1581 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300093
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300093 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1582 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300094
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300094 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1583 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300095
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300095 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1584 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300096
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300096 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1585 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300097
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300097 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1586 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300098
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300098 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1587 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300099
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300099 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1588 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300100
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300100 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1589 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300101
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300101 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1590 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300102
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300102 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1591 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300103
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300103 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1592 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300105
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300105 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1593 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300106
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300106 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1594 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300107
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300107 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1595 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300109
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300109 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1596 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300110
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300110 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1597 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300111
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300111 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1598 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300112
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300112 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1599 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300113
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300113 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1600 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300115
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300115 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1601 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300118
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300118 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1602 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300119
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300119 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1603 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300120
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300120 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1604 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300121
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300121 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1605 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300122
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300122 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1606 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300123
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300123 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1607 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300124
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300124 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1608 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300125
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300125 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1609 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300126
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300126 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1610 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300127
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300127 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1611 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300128
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300128 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1612 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300129
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300129 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1613 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 30.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300130
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300130 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1614 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300131
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300131 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1615 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300132
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300132 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1616 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300133
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300133 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1617 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300134
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300134 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1618 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300135
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300135 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1619 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300136
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300136 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1620 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300137
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300137 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1621 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300138
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300138 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1622 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300139
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300139 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1623 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300140
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300140 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1624 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300141
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300141 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1625 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300142
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300142 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1626 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300143
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300143 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1627 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300144
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300144 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1628 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300145
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300145 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1629 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300146
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300146 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1630 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300147
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300147 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1631 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300148
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300148 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1632 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300149
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300149 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1633 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300150
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300150 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1634 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300151
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300151 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1635 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300152
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300152 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1636 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300153
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300153 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1637 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300154
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300154 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1638 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300155
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300155 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1639 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300157
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300157 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1640 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300158
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300158 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1641 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300159
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300159 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1642 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300160
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300160 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1643 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300161
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300161 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1644 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300162
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300162 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1645 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300163
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300163 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1646 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300164
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300164 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1647 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300165
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300165 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1648 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300166
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300166 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1649 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300167
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300167 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1650 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300168
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300168 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1651 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300169
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300169 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1652 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300170
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300170 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1653 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300171
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300171 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1654 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300172
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300172 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1655 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300173
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300173 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1656 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300174
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300174 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1657 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300175
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300175 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1658 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300176
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300176 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1659 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300177
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300177 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1660 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300179
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300179 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1661 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300180
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300180 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1662 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300181
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300181 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1663 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300182
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300182 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1664 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300183
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300183 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1665 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 31.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300184
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300184 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1666 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300185
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300185 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1667 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300187
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300187 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1668 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300188
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300188 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1669 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300189
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300189 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1670 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300190
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300190 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1671 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300191
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300191 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1672 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300192
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300192 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1673 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300193
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300193 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1674 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300194
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300194 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1675 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300195
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300195 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1676 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300196
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300196 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1677 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300197
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300197 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1678 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300198
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300198 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1679 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300199
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300199 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1680 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300200
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300200 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1681 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300201
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300201 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1682 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300203
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300203 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1683 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300204
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300204 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1684 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300205
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300205 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1685 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300206
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300206 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1686 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300207
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300207 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1687 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300209
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300209 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1688 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300210
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300210 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1689 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300211
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300211 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1690 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300212
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300212 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1691 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300213
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300213 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1692 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300214
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300214 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1693 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300215
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300215 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1694 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300217
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300217 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1695 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300218
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300218 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1696 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300219
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300219 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1697 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300220
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300220 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1698 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300221
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300221 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1699 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300222
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300222 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1700 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300223
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300223 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1701 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300224
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300224 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1702 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300225
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300225 from 2025-04-30 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1703 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300226
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300226 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1704 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300227
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300227 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1705 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300228
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300228 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1706 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300229
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300229 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1707 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300230
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300230 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1708 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300231
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300231 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1709 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300232
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300232 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1710 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300233
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300233 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1711 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300234
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300234 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1712 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300235
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300235 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1713 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300236
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300236 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1714 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300237
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300237 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1715 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300238
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300238 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1716 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300239
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300239 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1717 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 32.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300240
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300240 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1718 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300241
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300241 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1719 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300242
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300242 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1720 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300243
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300243 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1721 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300244
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300244 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1722 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300245
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300245 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1723 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300246
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300246 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1724 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300247
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300247 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1725 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300248
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300248 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1726 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300249
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300249 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1727 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300250
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300250 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1728 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300251
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300251 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1729 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300252
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300252 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1730 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300253
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300253 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1731 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300254
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300254 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1732 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300255
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300255 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1733 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300256
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300256 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1734 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300257
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300257 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1735 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300258
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300258 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1736 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300259
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300259 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1737 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300260
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300260 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1738 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300261
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300261 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1739 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300263
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300263 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1740 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300264
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300264 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1741 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300265
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300265 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1742 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300266
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300266 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1743 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300267
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300267 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1744 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300268
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300268 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1745 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300269
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300269 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1746 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300270
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300270 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1747 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300271
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300271 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1748 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300272
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300272 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1749 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300274
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300274 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1750 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300275
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300275 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1751 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300276
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300276 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1752 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300277
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300277 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1753 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300278
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300278 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1754 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300279
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300279 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1755 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300281
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300281 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1756 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300283
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300283 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1757 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300284
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300284 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1758 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300285
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300285 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1759 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300286
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300286 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1760 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300287
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300287 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1761 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300288
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300288 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1762 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300289
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300289 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1763 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300290
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300290 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1764 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300291
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300291 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1765 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300292
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300292 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1766 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300293
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300293 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1767 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300294
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300294 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1768 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300295
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300295 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1769 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 33.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300296
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300296 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1770 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300298
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300298 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1771 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300299
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300299 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1772 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300300
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300300 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1773 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300301
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300301 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1774 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300302
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300302 from 2025-05-23 to 2026-07-07

__enter__
'NoneType' object has no attribute 'columns'

QUANTAXIS>> The 1775 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300303
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300303 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1776 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300304
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300304 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1777 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300305
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300305 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1778 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300306
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300306 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1779 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300307
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300307 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1780 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300308
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300308 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1781 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300310
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300310 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1782 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300311
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300311 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1783 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300313
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300313 from 2025-05-23 to 2026-07-07

__enter__
'NoneType' object has no attribute 'columns'

QUANTAXIS>> The 1784 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300314
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300314 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1785 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300315
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300315 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1786 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300316
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300316 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1787 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300317
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300317 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1788 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300318
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300318 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1789 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300319
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300319 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1790 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300320
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300320 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1791 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300321
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300321 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1792 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300322
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300322 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1793 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300323
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300323 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1794 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300324
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300324 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1795 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300326
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300326 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1796 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300327
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300327 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1797 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300328
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300328 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1798 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300329
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300329 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1799 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300331
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300331 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1800 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300332
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300332 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1801 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300333 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1802 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300334
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300334 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1803 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300335
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300335 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1804 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300337
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300337 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1805 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300338
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300338 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1806 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300339
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300339 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1807 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300340
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300340 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1808 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300341
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300341 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1809 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300342
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300342 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1810 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300343
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300343 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1811 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300345
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300345 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1812 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300346
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300346 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1813 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300347
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300347 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1814 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300348
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300348 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1815 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300349
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300349 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1816 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300350
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300350 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1817 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300351
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300351 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1818 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300352
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300352 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1819 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300353
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300353 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1820 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300354
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300354 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1821 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 34.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300355
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300355 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1822 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300357
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300357 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1823 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300358
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300358 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1824 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300359
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300359 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1825 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300360
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300360 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1826 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300363
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300363 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1827 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300364
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300364 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1828 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300365
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300365 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1829 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300366
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300366 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1830 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300368
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300368 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1831 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300369
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300369 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1832 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300370
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300370 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1833 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300371
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300371 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1834 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300373
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300373 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1835 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300374
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300374 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1836 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300375
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300375 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1837 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300376
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300376 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1838 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300377
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300377 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1839 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300378
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300378 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1840 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300380
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300380 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1841 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300381
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300381 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1842 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300382
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300382 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1843 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300383
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300383 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1844 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300384
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300384 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1845 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300385
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300385 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1846 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300386
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300386 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1847 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300387
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300387 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1848 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300388
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300388 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1849 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300389
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300389 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1850 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300390
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300390 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1851 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300393
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300393 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1852 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300394
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300394 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1853 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300395
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300395 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1854 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300396
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300396 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1855 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300397
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300397 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1856 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300398
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300398 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1857 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300399
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300399 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1858 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300400
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300400 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1859 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300401
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300401 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1860 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300402
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300402 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1861 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300403
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300403 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1862 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300404
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300404 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1863 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300405
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300405 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1864 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300406
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300406 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1865 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300407
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300407 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1866 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300408
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300408 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1867 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300409
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300409 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1868 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300410
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300410 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1869 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300411
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300411 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1870 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300412
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300412 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1871 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300413
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300413 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1872 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300414
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300414 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1873 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 35.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300415
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300415 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1874 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300416
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300416 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1875 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300417
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300417 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1876 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300418
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300418 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1877 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300419
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300419 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1878 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300420
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300420 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1879 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300421
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300421 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1880 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300422
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300422 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1881 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300423
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300423 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1882 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300424
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300424 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1883 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300425
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300425 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1884 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300426
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300426 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1885 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300427
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300427 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1886 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300428
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300428 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1887 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300429
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300429 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1888 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300430
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300430 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1889 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300432
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300432 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1890 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300433
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300433 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1891 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300434
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300434 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1892 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300435
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300435 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1893 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300436
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300436 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1894 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300437
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300437 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1895 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300438
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300438 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1896 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300439
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300439 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1897 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300440
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300440 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1898 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300441
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300441 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1899 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300442
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300442 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1900 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300443
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300443 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1901 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300444
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300444 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1902 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300445
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300445 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1903 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300446
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300446 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1904 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300447
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300447 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1905 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300448
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300448 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1906 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300449
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300449 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1907 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300450
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300450 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1908 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300451
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300451 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1909 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300452
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300452 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1910 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300453
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300453 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1911 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300454
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300454 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1912 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300455
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300455 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1913 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300456
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300456 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1914 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300457
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300457 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1915 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300458
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300458 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1916 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300459
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300459 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1917 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300460
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300460 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1918 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300461
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300461 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1919 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300462
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300462 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1920 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300463
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300463 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1921 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300464
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300464 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1922 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300465
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300465 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1923 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300466
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300466 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1924 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300467
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300467 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1925 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 36.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300468
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300468 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1926 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300469
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300469 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1927 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300470
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300470 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1928 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300471
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300471 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1929 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300472
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300472 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1930 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300473
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300473 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1931 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300474
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300474 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1932 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300475
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300475 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1933 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300476
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300476 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1934 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300477
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300477 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1935 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300478
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300478 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1936 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300479
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300479 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1937 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300480
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300480 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1938 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300481
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300481 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1939 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300482
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300482 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1940 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300483
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300483 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1941 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300484
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300484 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1942 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300485
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300485 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1943 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300486
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300486 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1944 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300487
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300487 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1945 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300488
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300488 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1946 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300489
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300489 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1947 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300490
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300490 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1948 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300491
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300491 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1949 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300492
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300492 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1950 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300493
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300493 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1951 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300494
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300494 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1952 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300496
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300496 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1953 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300497
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300497 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1954 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300498
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300498 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1955 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300499
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300499 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1956 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300500
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300500 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1957 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300501
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300501 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1958 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300502
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300502 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1959 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300503
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300503 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1960 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300504
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300504 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1961 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300505
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300505 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1962 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300506
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300506 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1963 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300507
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300507 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1964 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300508
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300508 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1965 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300509
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300509 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1966 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300510
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300510 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1967 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300511
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300511 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1968 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300512
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300512 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1969 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300513
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300513 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1970 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300514
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300514 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1971 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300515
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300515 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1972 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300516
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300516 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1973 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300517
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300517 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1974 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300518
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300518 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1975 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300519
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300519 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1976 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300520
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300520 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1977 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 37.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300521
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300521 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1978 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300522
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300522 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1979 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300523
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300523 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1980 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300525
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300525 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1981 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300527
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300527 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1982 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300528
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300528 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1983 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300529
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300529 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1984 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300530
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300530 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1985 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300531
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300531 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1986 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300532
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300532 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1987 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300533
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300533 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1988 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300534
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300534 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1989 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300535
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300535 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1990 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300536
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300536 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1991 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300537
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300537 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1992 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300538
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300538 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1993 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300539
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300539 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1994 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300540
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300540 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1995 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300541
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300541 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1996 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300542
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300542 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1997 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300543
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300543 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1998 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300545
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300545 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 1999 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300546
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300546 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2000 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300547
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300547 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2001 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300548
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300548 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2002 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300549
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300549 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2003 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300550
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300550 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2004 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300551
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300551 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2005 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300552
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300552 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2006 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300553
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300553 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2007 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300554
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300554 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2008 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300555
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300555 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2009 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300556
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300556 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2010 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300557
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300557 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2011 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300558
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300558 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2012 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300559
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300559 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2013 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300560
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300560 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2014 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300561
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300561 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2015 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300562
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300562 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2016 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300563
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300563 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2017 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300564
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300564 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2018 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300565
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300565 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2019 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300566
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300566 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2020 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300567
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300567 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2021 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300568
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300568 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2022 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300569
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300569 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2023 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300570
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300570 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2024 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300571
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300571 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2025 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300572
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300572 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2026 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300573
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300573 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2027 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300575
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300575 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2028 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300576
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300576 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2029 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 38.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300577
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300577 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2030 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300578
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300578 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2031 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300579
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300579 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2032 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300580
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300580 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2033 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300581
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300581 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2034 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300582
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300582 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2035 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300583
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300583 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2036 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300584
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300584 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2037 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300585
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300585 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2038 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300586
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300586 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2039 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300587
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300587 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2040 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300588
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300588 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2041 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300589
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300589 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2042 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300590
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300590 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2043 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300591
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300591 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2044 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300592
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300592 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2045 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300593
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300593 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2046 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300594
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300594 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2047 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300595
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300595 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2048 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300596
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300596 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2049 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300597
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300597 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2050 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300598
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300598 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2051 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300599
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300599 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2052 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300600
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300600 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2053 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300601
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300601 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2054 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300602
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300602 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2055 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300603
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300603 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2056 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300604
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300604 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2057 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300605
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300605 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2058 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300606
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300606 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2059 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300607
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300607 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2060 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300608
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300608 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2061 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300609
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300609 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2062 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300610
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300610 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2063 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300611
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300611 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2064 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300612
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300612 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2065 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300613
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300613 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2066 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300614
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300614 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2067 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300615
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300615 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2068 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300616
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300616 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2069 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300617
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300617 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2070 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300618
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300618 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2071 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300619
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300619 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2072 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300620
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300620 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2073 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300621
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300621 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2074 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300622
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300622 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2075 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300623
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300623 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2076 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300624
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300624 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2077 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300625
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300625 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2078 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300626
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300626 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2079 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300627
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300627 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2080 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300628
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300628 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2081 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 39.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300629
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300629 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2082 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300631
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300631 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2083 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300632
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300632 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2084 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300633
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300633 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2085 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300634
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300634 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2086 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300635
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300635 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2087 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300636
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300636 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2088 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300637
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300637 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2089 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300638
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300638 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2090 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300639
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300639 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2091 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300640
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300640 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2092 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300641
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300641 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2093 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300642
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300642 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2094 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300643
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300643 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2095 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300644
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300644 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2096 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300645
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300645 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2097 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300647
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300647 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2098 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300648
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300648 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2099 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300649
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300649 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2100 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300650
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300650 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2101 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300651
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300651 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2102 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300652
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300652 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2103 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300653
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300653 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2104 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300654
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300654 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2105 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300655
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300655 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2106 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300656
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300656 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2107 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300657
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300657 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2108 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300658
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300658 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2109 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300659
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300659 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2110 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300660
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300660 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2111 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300661
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300661 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2112 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300662
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300662 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2113 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300663
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300663 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2114 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300664
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300664 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2115 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300665
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300665 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2116 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300666
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300666 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2117 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300667
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300667 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2118 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300668
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300668 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2119 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300669
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300669 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2120 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300670
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300670 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2121 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300671
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300671 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2122 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300672
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300672 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2123 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300673
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300673 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2124 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300674
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300674 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2125 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300675
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300675 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2126 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300676
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300676 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2127 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300677
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300677 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2128 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300678
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300678 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2129 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300679
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300679 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2130 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300680
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300680 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2131 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300681
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300681 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2132 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300682
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300682 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2133 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300683
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300683 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2134 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 40.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300684
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300684 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2135 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300685
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300685 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2136 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300686
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300686 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2137 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300687
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300687 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2138 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300688
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300688 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2139 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300689
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300689 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2140 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300690
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300690 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2141 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300691
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300691 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2142 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300692
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300692 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2143 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300693
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300693 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2144 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300694
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300694 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2145 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300695
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300695 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2146 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300696
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300696 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2147 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300697
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300697 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2148 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300698
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300698 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2149 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300699
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300699 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2150 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300700
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300700 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2151 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300701
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300701 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2152 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300702
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300702 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2153 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300703
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300703 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2154 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300705
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300705 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2155 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300706
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300706 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2156 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300707
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300707 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2157 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300708
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300708 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2158 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300709
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300709 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2159 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300710
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300710 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2160 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300711
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300711 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2161 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300712
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300712 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2162 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300713
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300713 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2163 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300715
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300715 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2164 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300716
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300716 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2165 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300717
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300717 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2166 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300718
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300718 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2167 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300719
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300719 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2168 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300720
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300720 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2169 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300721
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300721 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2170 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300722
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300722 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2171 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300723
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300723 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2172 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300724
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300724 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2173 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300725
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300725 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2174 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300726
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300726 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2175 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300727
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300727 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2176 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300729
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300729 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2177 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300730
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300730 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2178 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300731
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300731 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2179 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300732
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300732 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2180 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300733
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300733 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2181 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300735
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300735 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2182 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300736
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300736 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2183 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300737
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300737 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2184 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300738
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300738 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2185 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300739
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300739 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2186 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 41.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300740
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300740 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2187 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300741
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300741 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2188 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300743
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300743 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2189 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300745
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300745 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2190 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300746
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300746 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2191 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300747
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300747 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2192 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300748
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300748 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2193 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300749
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300749 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2194 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300750
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300750 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2195 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300751
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300751 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2196 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300752
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300752 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2197 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300753
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300753 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2198 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300755
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300755 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2199 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300756
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300756 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2200 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300757
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300757 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2201 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300758
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300758 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2202 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300759
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300759 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2203 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300760
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300760 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2204 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300761
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300761 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2205 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300762
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300762 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2206 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300763
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300763 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2207 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300765
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300765 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2208 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300766
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300766 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2209 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300767
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300767 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2210 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300768
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300768 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2211 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300769
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300769 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2212 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300770
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300770 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2213 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300771
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300771 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2214 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300772
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300772 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2215 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300773
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300773 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2216 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300774
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300774 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2217 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300775
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300775 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2218 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300776
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300776 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2219 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300777
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300777 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2220 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300778
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300778 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2221 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300779
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300779 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2222 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300780
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300780 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2223 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300781
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300781 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2224 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300782
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300782 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2225 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300783
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300783 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2226 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300784
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300784 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2227 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300785
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300785 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2228 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300786
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300786 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2229 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300787
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300787 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2230 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300788
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300788 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2231 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300789
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300789 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2232 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300790
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300790 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2233 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300791
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300791 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2234 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300792
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300792 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2235 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300793
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300793 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2236 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300795
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300795 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2237 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300796
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300796 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2238 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 42.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300797
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300797 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2239 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300798
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300798 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2240 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300800
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300800 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2241 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300801
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300801 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2242 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300802
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300802 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2243 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300803
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300803 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2244 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300804
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300804 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2245 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300805
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300805 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2246 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300806
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300806 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2247 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300807
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300807 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2248 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300808
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300808 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2249 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300809
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300809 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2250 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300810
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300810 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2251 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300811
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300811 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2252 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300812
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300812 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2253 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300813
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300813 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2254 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300814
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300814 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2255 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300815
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300815 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2256 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300816
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300816 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2257 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300817
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300817 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2258 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300818
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300818 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2259 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300819
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300819 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2260 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300820
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300820 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2261 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300821
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300821 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2262 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300822
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300822 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2263 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300823
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300823 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2264 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300824
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300824 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2265 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300825
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300825 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2266 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300826
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300826 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2267 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300827
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300827 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2268 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300828
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300828 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2269 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300829
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300829 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2270 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300830
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300830 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2271 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300831
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300831 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2272 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300832
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300832 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2273 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300833
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300833 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2274 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300834
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300834 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2275 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300835
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300835 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2276 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300836
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300836 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2277 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300837
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300837 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2278 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300838
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300838 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2279 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300839
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300839 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2280 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300840
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300840 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2281 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300841
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300841 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2282 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300842
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300842 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2283 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300843
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300843 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2284 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300844
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300844 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2285 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300845
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300845 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2286 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300846
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300846 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2287 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300847
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300847 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2288 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300848
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300848 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2289 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300849
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300849 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2290 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 43.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300850
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300850 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2291 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300851
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300851 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2292 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300852
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300852 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2293 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300853
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300853 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2294 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300854
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300854 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2295 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300855
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300855 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2296 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300856
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300856 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2297 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300857
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300857 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2298 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300858
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300858 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2299 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300859
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300859 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2300 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300860
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300860 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2301 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300861
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300861 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2302 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300862
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300862 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2303 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300863
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300863 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2304 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300864
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300864 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2305 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300865
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300865 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2306 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300866
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300866 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2307 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300867
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300867 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2308 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300868
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300868 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2309 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300869
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300869 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2310 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300870
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300870 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2311 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300871
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300871 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2312 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300872
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300872 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2313 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300873
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300873 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2314 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300875
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300875 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2315 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300876
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300876 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2316 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300877
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300877 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2317 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300878
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300878 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2318 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300879
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300879 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2319 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300880
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300880 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2320 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300881
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300881 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2321 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300882
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300882 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2322 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300883
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300883 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2323 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300884
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300884 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2324 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300885
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300885 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2325 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300886
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300886 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2326 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300887
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300887 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2327 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300888
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300888 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2328 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300889
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300889 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2329 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300890
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300890 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2330 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300891
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300891 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2331 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300892
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300892 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2332 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300893
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300893 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2333 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300894
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300894 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2334 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300895
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300895 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2335 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300896
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300896 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2336 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300897
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300897 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2337 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300898
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300898 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2338 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300899
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300899 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2339 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300900
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300900 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2340 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300901
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300901 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2341 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300902
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300902 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2342 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 44.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300903
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300903 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2343 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300904
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300904 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2344 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300905
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300905 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2345 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300906
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300906 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2346 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300907
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300907 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2347 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300908
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300908 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2348 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300909
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300909 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2349 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300910
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300910 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2350 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300911
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300911 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2351 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300912
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300912 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2352 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300913
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300913 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2353 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300915
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300915 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2354 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300916
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300916 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2355 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300917
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300917 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2356 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300918
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300918 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2357 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300919
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300919 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2358 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300920
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300920 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2359 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300921
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300921 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2360 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300922
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300922 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2361 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300923
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300923 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2362 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300925
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300925 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2363 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300926
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300926 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2364 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300927
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300927 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2365 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300928
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300928 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2366 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300929
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300929 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2367 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300930
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300930 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2368 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300931
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300931 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2369 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300932
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300932 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2370 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300933
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300933 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2371 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300935
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300935 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2372 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300936
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300936 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2373 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300937
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300937 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2374 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300938
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300938 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2375 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300939
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300939 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2376 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300940
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300940 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2377 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300941
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300941 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2378 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300942
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300942 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2379 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300943
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300943 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2380 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300945
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300945 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2381 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300946
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300946 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2382 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300947
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300947 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2383 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300948
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300948 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2384 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300949
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300949 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2385 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300950
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300950 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2386 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300951
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300951 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2387 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300952
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300952 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2388 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300953
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300953 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2389 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300955
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300955 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2390 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300956
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300956 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2391 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300957
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300957 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2392 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300958
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300958 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2393 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300959
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300959 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2394 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 45.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300960
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300960 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2395 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300961
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300961 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2396 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300962
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300962 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2397 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300963
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300963 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2398 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300964
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300964 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2399 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300965
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300965 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2400 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300966
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300966 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2401 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300967
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300967 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2402 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300968
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300968 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2403 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300969
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300969 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2404 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300970
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300970 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2405 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300971
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300971 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2406 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300972
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300972 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2407 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300973
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300973 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2408 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300975
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300975 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2409 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300976
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300976 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2410 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300977
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300977 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2411 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300978
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300978 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2412 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300979
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300979 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2413 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300980
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300980 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2414 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300981
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300981 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2415 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300982
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300982 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2416 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300983
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300983 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2417 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300984
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300984 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2418 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300985
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300985 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2419 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300986
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300986 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2420 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300987
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300987 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2421 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300988
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300988 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2422 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300989
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300989 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2423 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300990
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300990 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2424 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300991
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300991 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2425 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300992
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300992 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2426 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300993
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300993 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2427 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300994
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300994 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2428 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300995
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300995 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2429 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300996
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300996 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2430 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300997
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300997 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2431 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300998
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300998 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2432 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 300999
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 300999 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2433 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301000
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301000 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2434 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301001
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301001 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2435 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301002
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301002 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2436 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301003
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301003 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2437 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301004
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301004 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2438 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301005
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301005 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2439 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301006 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2440 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301007 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2441 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301008 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2442 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301009 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2443 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301010
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301010 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2444 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301011 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2445 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301012
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301012 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2446 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 46.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301013
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301013 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2447 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301015
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301015 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2448 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301016 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2449 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301017
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301017 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2450 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301018
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301018 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2451 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301019
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301019 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2452 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301020 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2453 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301021
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301021 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2454 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301022
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301022 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2455 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301023
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301023 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2456 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301024
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301024 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2457 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301025
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301025 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2458 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301026
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301026 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2459 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301027
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301027 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2460 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301028
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301028 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2461 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301029
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301029 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2462 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301030
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301030 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2463 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301031
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301031 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2464 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301032
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301032 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2465 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301033
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301033 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2466 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301035
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301035 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2467 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301036
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301036 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2468 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301037
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301037 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2469 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301038
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301038 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2470 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301039
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301039 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2471 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301040
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301040 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2472 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301041
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301041 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2473 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301042
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301042 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2474 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301043
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301043 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2475 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301045
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301045 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2476 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301046
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301046 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2477 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301047
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301047 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2478 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301048
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301048 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2479 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301049
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301049 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2480 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301050
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301050 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2481 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301051
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301051 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2482 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301052
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301052 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2483 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301053
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301053 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2484 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301055
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301055 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2485 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301056
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301056 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2486 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301057
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301057 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2487 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301058
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301058 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2488 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301059
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301059 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2489 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301060
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301060 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2490 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301061
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301061 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2491 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301062
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301062 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2492 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301063
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301063 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2493 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301065
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301065 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2494 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301066
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301066 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2495 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301067
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301067 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2496 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301068
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301068 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2497 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301069
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301069 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2498 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 47.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301070
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301070 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2499 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301071
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301071 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2500 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301072
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301072 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2501 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301073
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301073 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2502 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301075
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301075 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2503 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301076
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301076 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2504 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301077
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301077 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2505 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301078
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301078 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2506 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301079
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301079 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2507 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301080
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301080 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2508 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301081
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301081 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2509 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301082
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301082 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2510 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301083
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301083 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2511 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301085
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301085 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2512 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301086
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301086 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2513 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301087
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301087 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2514 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301088
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301088 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2515 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301089
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301089 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2516 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301090
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301090 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2517 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301091
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301091 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2518 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301092
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301092 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2519 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301093
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301093 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2520 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301095
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301095 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2521 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301096
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301096 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2522 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301097
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301097 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2523 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301098
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301098 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2524 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301099
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301099 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2525 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301100
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301100 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2526 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301101
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301101 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2527 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301102
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301102 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2528 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301103
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301103 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2529 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301105
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301105 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2530 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301106
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301106 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2531 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301107
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301107 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2532 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301108
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301108 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2533 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301109
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301109 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2534 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301110
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301110 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2535 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301111
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301111 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2536 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301112
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301112 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2537 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301113
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301113 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2538 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301115
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301115 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2539 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301116
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301116 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2540 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301117
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301117 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2541 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301118
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301118 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2542 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301119
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301119 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2543 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301120
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301120 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2544 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301121
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301121 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2545 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301122
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301122 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2546 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301123
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301123 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2547 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301125
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301125 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2548 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301126
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301126 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2549 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301127
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301127 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2550 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 48.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301128
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301128 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2551 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301129
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301129 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2552 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301130
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301130 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2553 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301131
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301131 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2554 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301132
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301132 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2555 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301133
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301133 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2556 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301135
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301135 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2557 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301136
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301136 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2558 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301137
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301137 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2559 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301138
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301138 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2560 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301139
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301139 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2561 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301141
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301141 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2562 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301148
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301148 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2563 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301149
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301149 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2564 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301150
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301150 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2565 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301151
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301151 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2566 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301152
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301152 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2567 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301153
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301153 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2568 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301155
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301155 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2569 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301156
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301156 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2570 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301157
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301157 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2571 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301158
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301158 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2572 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301159
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301159 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2573 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301160
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301160 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2574 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301161
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301161 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2575 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301162
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301162 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2576 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301163
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301163 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2577 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301165
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301165 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2578 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301166
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301166 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2579 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301167
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301167 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2580 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301168
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301168 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2581 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301169
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301169 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2582 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301170
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301170 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2583 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301171
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301171 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2584 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301172
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301172 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2585 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301173
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301173 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2586 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301175
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301175 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2587 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301176
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301176 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2588 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301177
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301177 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2589 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301178
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301178 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2590 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301179
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301179 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2591 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301180
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301180 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2592 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301181
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301181 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2593 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301182
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301182 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2594 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301183
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301183 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2595 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301185
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301185 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2596 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301186
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301186 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2597 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301187
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301187 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2598 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301188
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301188 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2599 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301189
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301189 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2600 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301190
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301190 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2601 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301191
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301191 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2602 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 49.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301192
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301192 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2603 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301193
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301193 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2604 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301195
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301195 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2605 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301196
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301196 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2606 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301197
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301197 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2607 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301198
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301198 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2608 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301199
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301199 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2609 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301200
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301200 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2610 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301201
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301201 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2611 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301202
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301202 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2612 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301203
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301203 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2613 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301205
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301205 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2614 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301206
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301206 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2615 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301207
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301207 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2616 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301208
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301208 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2617 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301209
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301209 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2618 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301210
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301210 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2619 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301211
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301211 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2620 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301212
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301212 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2621 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301213
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301213 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2622 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301215
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301215 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2623 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301216
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301216 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2624 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301217
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301217 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2625 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301218
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301218 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2626 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301219
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301219 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2627 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301220
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301220 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2628 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301221
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301221 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2629 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301222
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301222 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2630 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301223
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301223 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2631 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301225
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301225 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2632 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301226
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301226 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2633 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301227
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301227 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2634 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301228
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301228 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2635 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301229
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301229 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2636 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301230
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301230 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2637 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301231
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301231 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2638 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301232
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301232 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2639 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301233
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301233 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2640 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301234
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301234 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2641 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301235
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301235 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2642 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301236
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301236 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2643 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301237
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301237 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2644 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301238
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301238 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2645 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301239
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301239 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2646 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301246
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301246 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2647 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301248
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301248 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2648 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301251
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301251 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2649 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301252
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301252 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2650 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301255
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301255 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2651 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301256
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301256 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2652 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301257
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301257 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2653 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301258
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301258 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2654 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 50.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301259
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301259 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2655 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301260
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301260 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2656 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301261
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301261 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2657 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301262
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301262 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2658 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301263
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301263 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2659 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301265
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301265 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2660 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301266
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301266 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2661 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301267
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301267 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2662 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301268
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301268 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2663 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301269
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301269 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2664 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301270
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301270 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2665 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301272
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301272 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2666 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301273
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301273 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2667 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301275
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301275 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2668 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301276
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301276 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2669 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301277
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301277 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2670 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301278
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301278 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2671 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301279
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301279 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2672 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301280
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301280 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2673 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301281
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301281 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2674 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301282
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301282 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2675 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301283
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301283 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2676 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301285
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301285 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2677 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301286
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301286 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2678 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301287
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301287 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2679 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301288
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301288 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2680 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301289
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301289 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2681 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301290
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301290 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2682 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301291
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301291 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2683 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301292
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301292 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2684 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301293
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301293 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2685 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301295
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301295 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2686 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301296
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301296 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2687 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301297
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301297 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2688 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301298
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301298 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2689 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301299
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301299 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2690 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301300
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301300 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2691 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301301
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301301 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2692 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301302
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301302 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2693 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301303
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301303 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2694 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301305
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301305 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2695 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301306
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301306 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2696 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301307
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301307 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2697 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301308
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301308 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2698 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301309
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301309 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2699 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301310
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301310 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2700 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301311
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301311 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2701 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301312
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301312 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2702 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301313
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301313 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2703 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301314
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301314 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2704 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301315
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301315 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2705 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301316
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301316 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2706 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 51.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301317
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301317 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2707 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301318
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301318 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2708 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301319
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301319 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2709 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301320
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301320 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2710 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301321
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301321 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2711 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301322
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301322 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2712 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301323
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301323 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2713 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301325
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301325 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2714 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301326
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301326 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2715 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301327
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301327 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2716 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301328
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301328 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2717 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301329
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301329 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2718 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301330
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301330 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2719 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301331
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301331 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2720 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301332
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301332 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2721 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301333 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2722 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301335
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301335 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2723 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301336
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301336 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2724 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301337
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301337 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2725 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301338
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301338 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2726 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301339
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301339 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2727 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301345
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301345 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2728 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301348
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301348 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2729 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301349
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301349 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2730 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301353
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301353 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2731 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301355
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301355 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2732 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301356
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301356 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2733 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301357
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301357 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2734 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301358
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301358 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2735 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301359
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301359 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2736 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301360
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301360 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2737 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301361
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301361 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2738 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301362
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301362 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2739 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301363
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301363 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2740 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301365
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301365 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2741 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301366
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301366 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2742 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301367
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301367 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2743 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301368
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301368 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2744 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301369
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301369 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2745 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301370
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301370 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2746 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301371
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301371 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2747 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301372
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301372 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2748 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301373
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301373 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2749 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301376
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301376 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2750 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301377
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301377 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2751 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301378
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301378 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2752 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301379
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301379 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2753 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301380
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301380 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2754 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301381
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301381 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2755 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301382
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301382 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2756 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301383
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301383 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2757 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301386
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301386 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2758 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 52.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301387
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301387 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2759 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301388
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301388 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2760 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301389
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301389 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2761 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301390
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301390 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2762 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301391
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301391 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2763 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301392
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301392 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2764 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301393
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301393 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2765 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301395
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301395 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2766 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301396
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301396 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2767 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301397
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301397 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2768 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301398
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301398 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2769 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301399
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301399 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2770 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301408
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301408 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2771 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301413
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301413 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2772 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301418
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301418 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2773 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301419
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301419 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2774 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301421
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301421 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2775 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301428
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301428 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2776 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301429
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301429 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2777 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301439
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301439 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2778 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301446
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301446 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2779 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301448
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301448 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2780 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301449
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301449 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2781 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301456
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301456 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2782 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301458
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301458 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2783 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301459
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301459 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2784 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301468
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301468 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2785 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301469
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301469 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2786 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301479
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301479 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2787 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301486
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301486 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2788 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301487
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301487 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2789 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301488
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301488 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2790 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301489
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301489 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2791 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301491
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301491 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2792 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301498
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301498 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2793 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301499
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301499 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2794 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301500
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301500 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2795 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301501
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301501 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2796 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301502
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301502 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2797 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301503
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301503 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2798 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301505
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301505 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2799 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301507
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301507 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2800 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301508
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301508 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2801 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301509
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301509 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2802 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301510
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301510 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2803 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301511
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301511 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2804 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301512
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301512 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2805 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301513
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301513 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2806 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301515
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301515 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2807 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301516
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301516 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2808 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301517
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301517 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2809 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301518
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301518 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2810 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 53.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301519
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301519 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2811 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301520
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301520 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2812 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301522
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301522 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2813 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301525
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301525 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2814 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301526
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301526 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2815 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301528
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301528 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2816 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301529
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301529 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2817 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301531
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301531 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2818 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301533
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301533 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2819 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301535
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301535 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2820 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301536
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301536 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2821 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301538
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301538 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2822 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301539
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301539 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2823 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301548
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301548 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2824 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301550
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301550 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2825 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301551
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301551 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2826 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301552
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301552 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2827 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301555
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301555 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2828 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301556
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301556 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2829 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301557
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301557 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2830 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301558
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301558 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2831 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301559
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301559 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2832 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301560
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301560 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2833 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301563
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301563 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2834 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301565
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301565 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2835 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301566
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301566 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2836 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301567
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301567 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2837 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301568
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301568 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2838 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301571
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301571 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2839 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301575
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301575 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2840 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301577
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301577 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2841 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301578
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301578 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2842 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301580
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301580 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2843 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301581
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301581 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2844 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301583
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301583 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2845 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301584
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301584 from 1990-01-01 to 2026-07-07

'NoneType' object has no attribute 'columns'

QUANTAXIS>> The 2846 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301585
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301585 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2847 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301586
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301586 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2848 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301587
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301587 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2849 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301588
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301588 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2850 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301589
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301589 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2851 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301590
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301590 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2852 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301591
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301591 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2853 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301592
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301592 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2854 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301595
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301595 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2855 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301596
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301596 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2856 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301598
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301598 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2857 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301599
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301599 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2858 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301600
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301600 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2859 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301601
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301601 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2860 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301602
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301602 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2861 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301603
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301603 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2862 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 54.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301606
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301606 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2863 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301607
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301607 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2864 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301608
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301608 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2865 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301609
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301609 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2866 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301611
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301611 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2867 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301613
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301613 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2868 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301616
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301616 from 2025-05-23 to 2026-07-07
QUANTAXIS>> The 2869 of Total 5205

name 'date' is not defined
name 'date' is not defined

QUANTAXIS>> DOWNLOAD PROGRESS 55.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301617
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301617 from 2025-05-23 to 2026-07-07
QUANTAXIS>> The 2870 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301618
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301618 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2871 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301622
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301622 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2872 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301626
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301626 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2873 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301628
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301628 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2874 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301629
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301629 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2875 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301630
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301630 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2876 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301631
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301631 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2877 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301632
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301632 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2878 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301633
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301633 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2879 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301636
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301636 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2880 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301638
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301638 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2881 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301656
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301656 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2882 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301658
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301658 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2883 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301662
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301662 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2884 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301665
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301665 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2885 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301666
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301666 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2886 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301667
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301667 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2887 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301668
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301668 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2888 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301669
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301669 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2889 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301678
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301678 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2890 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301680
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301680 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2891 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301682
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301682 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2892 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301683
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301683 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2893 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301687
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301687 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2894 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 301696
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 301696 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2895 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 302132
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 302132 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2896 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600000
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600000 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2897 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600004
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600004 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2898 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600006 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2899 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600007 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2900 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600008 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2901 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600009 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2902 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600010
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600010 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2903 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600011 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2904 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600012
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600012 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2905 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600015
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600015 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2906 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600016 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2907 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600017
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600017 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2908 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600018
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600018 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2909 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600019
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600019 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2910 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600020 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2911 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600021
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600021 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2912 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600022
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600022 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2913 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600023
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600023 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2914 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 55.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600025
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600025 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2915 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600026
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600026 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2916 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600027
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600027 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2917 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600028
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600028 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2918 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600029
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600029 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2919 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600030
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600030 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2920 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600031
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600031 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2921 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600032
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600032 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2922 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600033
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600033 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2923 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600035
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600035 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2924 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600036
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600036 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2925 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600037
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600037 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2926 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600038
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600038 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2927 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600039
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600039 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2928 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600048
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600048 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2929 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600050
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600050 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2930 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600051
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600051 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2931 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600052
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600052 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2932 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600053
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600053 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2933 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600054
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600054 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2934 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600055
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600055 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2935 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600056
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600056 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2936 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600057
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600057 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2937 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600058
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600058 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2938 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600059
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600059 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2939 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600060
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600060 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2940 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600061
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600061 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2941 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600062
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600062 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2942 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600063
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600063 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2943 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600064
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600064 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2944 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600066
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600066 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2945 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600067
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600067 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2946 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600071
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600071 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2947 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600072
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600072 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2948 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600073
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600073 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2949 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600075
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600075 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2950 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600076
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600076 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2951 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600078
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600078 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2952 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600079
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600079 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2953 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600080
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600080 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2954 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600081
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600081 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2955 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600082
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600082 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2956 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600084
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600084 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2957 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600085
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600085 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2958 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600088
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600088 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2959 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600089
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600089 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2960 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600094
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600094 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2961 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600095
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600095 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2962 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600096
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600096 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2963 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600097
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600097 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2964 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600098
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600098 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2965 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600099
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600099 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2966 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 56.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600100
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600100 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2967 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600101
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600101 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2968 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600103
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600103 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2969 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600104
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600104 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2970 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600105
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600105 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2971 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600106
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600106 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2972 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600107
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600107 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2973 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600108
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600108 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2974 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600109
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600109 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2975 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600110
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600110 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2976 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600111
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600111 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2977 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600113
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600113 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2978 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600114
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600114 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2979 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600115
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600115 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2980 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600116
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600116 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2981 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600117
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600117 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2982 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600118
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600118 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2983 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600119
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600119 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2984 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600120
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600120 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2985 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600121
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600121 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2986 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600123
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600123 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2987 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600125
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600125 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2988 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600126
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600126 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2989 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600127
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600127 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2990 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600128
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600128 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2991 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600129
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600129 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2992 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600130
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600130 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2993 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600131
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600131 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2994 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600132
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600132 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2995 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600133
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600133 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2996 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600135
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600135 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2997 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600136
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600136 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2998 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600137
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600137 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 2999 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600138
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600138 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3000 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600141
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600141 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3001 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600143
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600143 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3002 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600148
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600148 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3003 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600149
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600149 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3004 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600150
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600150 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3005 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600151
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600151 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3006 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600152
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600152 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3007 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600153
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600153 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3008 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600155
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600155 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3009 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600156
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600156 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3010 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600157
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600157 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3011 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600158
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600158 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3012 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600159
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600159 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3013 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600160
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600160 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3014 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600161
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600161 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3015 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600162
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600162 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3016 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600163
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600163 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3017 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600165
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600165 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3018 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 57.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600166
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600166 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3019 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600167
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600167 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3020 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600168
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600168 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3021 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600169
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600169 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3022 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600170
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600170 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3023 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600171
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600171 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3024 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600172
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600172 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3025 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600173
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600173 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3026 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600176
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600176 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3027 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600177
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600177 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3028 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600178
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600178 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3029 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600179
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600179 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3030 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600180
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600180 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3031 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600182
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600182 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3032 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600183
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600183 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3033 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600184
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600184 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3034 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600185
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600185 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3035 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600186
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600186 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3036 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600187
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600187 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3037 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600188
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600188 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3038 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600189
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600189 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3039 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600191
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600191 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3040 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600192
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600192 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3041 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600195
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600195 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3042 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600196
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600196 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3043 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600197
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600197 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3044 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600198
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600198 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3045 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600199
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600199 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3046 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600201
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600201 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3047 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600202
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600202 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3048 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600203
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600203 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3049 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600206
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600206 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3050 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600207
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600207 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3051 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600208
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600208 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3052 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600210
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600210 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3053 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600211
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600211 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3054 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600212
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600212 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3055 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600215
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600215 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3056 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600216
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600216 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3057 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600217
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600217 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3058 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600218
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600218 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3059 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600219
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600219 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3060 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600221
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600221 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3061 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600222
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600222 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3062 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600223
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600223 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3063 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600226
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600226 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3064 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600227
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600227 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3065 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600228
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600228 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3066 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600229
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600229 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3067 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600230
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600230 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3068 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600231
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600231 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3069 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600232
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600232 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3070 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 58.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600233
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600233 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3071 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600234
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600234 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3072 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600235
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600235 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3073 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600236
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600236 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3074 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600237
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600237 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3075 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600238
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600238 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3076 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600239
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600239 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3077 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600241
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600241 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3078 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600243
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600243 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3079 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600246
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600246 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3080 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600248
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600248 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3081 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600249
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600249 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3082 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600250
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600250 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3083 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600251
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600251 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3084 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600252
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600252 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3085 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600255
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600255 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3086 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600256
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600256 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3087 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600257
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600257 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3088 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600258
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600258 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3089 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600259
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600259 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3090 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600261
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600261 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3091 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600262
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600262 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3092 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600265
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600265 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3093 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600266
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600266 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3094 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600267
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600267 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3095 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600268
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600268 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3096 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600269
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600269 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3097 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600271
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600271 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3098 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600272
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600272 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3099 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600273
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600273 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3100 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600276
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600276 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3101 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600278
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600278 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3102 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600279
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600279 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3103 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600280
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600280 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3104 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600281
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600281 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3105 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600282
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600282 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3106 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600283
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600283 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3107 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600284
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600284 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3108 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600285
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600285 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3109 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600287
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600287 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3110 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600288
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600288 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3111 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600289
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600289 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3112 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600292
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600292 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3113 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600293
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600293 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3114 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600295
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600295 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3115 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600298
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600298 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3116 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600299
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600299 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3117 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600300
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600300 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3118 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600301
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600301 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3119 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600302
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600302 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3120 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600303
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600303 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3121 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600305
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600305 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3122 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 59.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600307
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600307 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3123 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600308
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600308 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3124 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600309
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600309 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3125 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600310
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600310 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3126 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600312
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600312 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3127 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600313
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600313 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3128 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600315
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600315 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3129 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600316
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600316 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3130 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600318
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600318 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3131 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600319
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600319 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3132 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600320
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600320 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3133 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600322
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600322 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3134 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600323
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600323 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3135 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600325
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600325 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3136 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600326
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600326 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3137 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600327
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600327 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3138 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600328
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600328 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3139 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600329
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600329 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3140 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600330
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600330 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3141 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600331
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600331 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3142 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600332
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600332 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3143 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600333 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3144 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600335
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600335 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3145 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600336
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600336 from 2025-05-23 to 2026-07-07

timed out
'NoneType' object has no attribute 'columns'

QUANTAXIS>> The 3146 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600337
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600337 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3147 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600338
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600338 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3148 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600339
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600339 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3149 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600340
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600340 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3150 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600343
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600343 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3151 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600345
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600345 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3152 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600346
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600346 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3153 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600348
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600348 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3154 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600350
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600350 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3155 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600351
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600351 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3156 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600352
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600352 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3157 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600353
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600353 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3158 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600354
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600354 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3159 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600356
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600356 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3160 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600358
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600358 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3161 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600359
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600359 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3162 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600360
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600360 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3163 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600361
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600361 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3164 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600362
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600362 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3165 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600363
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600363 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3166 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600365
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600365 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3167 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600366
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600366 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3168 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600367
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600367 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3169 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600368
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600368 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3170 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600369
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600369 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3171 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600370
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600370 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3172 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600371
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600371 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3173 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600372
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600372 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3174 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600373
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600373 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3175 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 60.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600375
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600375 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3176 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600376
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600376 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3177 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600377
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600377 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3178 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600378
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600378 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3179 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600379
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600379 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3180 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600380
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600380 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3181 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600381
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600381 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3182 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600382
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600382 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3183 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600383
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600383 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3184 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600386
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600386 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3185 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600388
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600388 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3186 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600389
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600389 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3187 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600390
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600390 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3188 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600391
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600391 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3189 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600392
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600392 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3190 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600395
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600395 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3191 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600396
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600396 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3192 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600397
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600397 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3193 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600398
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600398 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3194 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600399
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600399 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3195 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600400
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600400 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3196 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600403
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600403 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3197 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600405
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600405 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3198 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600406
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600406 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3199 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600408
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600408 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3200 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600409
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600409 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3201 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600410
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600410 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3202 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600415
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600415 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3203 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600416
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600416 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3204 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600418
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600418 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3205 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600419
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600419 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3206 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600420
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600420 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3207 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600422
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600422 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3208 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600423
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600423 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3209 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600425
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600425 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3210 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600426
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600426 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3211 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600428
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600428 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3212 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600429
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600429 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3213 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600433
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600433 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3214 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600435
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600435 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3215 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600436
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600436 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3216 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600438
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600438 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3217 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600439
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600439 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3218 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600444
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600444 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3219 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600446
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600446 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3220 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600448
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600448 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3221 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600449
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600449 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3222 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600452
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600452 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3223 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600455
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600455 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3224 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600456
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600456 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3225 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600458
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600458 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3226 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600459
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600459 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3227 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 61.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600460
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600460 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3228 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600461
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600461 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3229 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600463
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600463 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3230 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600467
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600467 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3231 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600468
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600468 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3232 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600469
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600469 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3233 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600470
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600470 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3234 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600475
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600475 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3235 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600476
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600476 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3236 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600477
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600477 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3237 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600478
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600478 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3238 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600479
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600479 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3239 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600480
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600480 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3240 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600481
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600481 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3241 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600482
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600482 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3242 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600483
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600483 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3243 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600486
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600486 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3244 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600487
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600487 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3245 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600488
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600488 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3246 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600489
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600489 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3247 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600490
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600490 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3248 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600491
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600491 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3249 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600493
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600493 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3250 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600495
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600495 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3251 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600496
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600496 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3252 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600497
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600497 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3253 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600498
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600498 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3254 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600499
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600499 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3255 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600500
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600500 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3256 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600501
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600501 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3257 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600502
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600502 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3258 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600503
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600503 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3259 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600505
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600505 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3260 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600506
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600506 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3261 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600507
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600507 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3262 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600508
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600508 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3263 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600509
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600509 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3264 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600510
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600510 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3265 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600511
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600511 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3266 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600512
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600512 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3267 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600513
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600513 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3268 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600515
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600515 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3269 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600516
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600516 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3270 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600517
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600517 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3271 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600518
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600518 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3272 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600519
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600519 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3273 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600520
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600520 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3274 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600521
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600521 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3275 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600522
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600522 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3276 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600523
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600523 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3277 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600525
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600525 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3278 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600526
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600526 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3279 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 62.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600527
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600527 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3280 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600528
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600528 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3281 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600529
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600529 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3282 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600530
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600530 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3283 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600531
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600531 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3284 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600533
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600533 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3285 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600535
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600535 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3286 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600536
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600536 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3287 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600537
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600537 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3288 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600538
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600538 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3289 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600539
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600539 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3290 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600540
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600540 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3291 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600543
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600543 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3292 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600545
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600545 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3293 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600546
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600546 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3294 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600547
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600547 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3295 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600548
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600548 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3296 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600549
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600549 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3297 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600550
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600550 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3298 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600551
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600551 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3299 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600552
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600552 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3300 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600556
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600556 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3301 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600557
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600557 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3302 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600558
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600558 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3303 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600559
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600559 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3304 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600560
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600560 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3305 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600561
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600561 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3306 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600562
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600562 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3307 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600563
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600563 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3308 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600566
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600566 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3309 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600567
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600567 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3310 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600568
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600568 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3311 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600569
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600569 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3312 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600570
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600570 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3313 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600571
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600571 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3314 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600572
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600572 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3315 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600573
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600573 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3316 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600575
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600575 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3317 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600576
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600576 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3318 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600577
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600577 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3319 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600578
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600578 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3320 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600579
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600579 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3321 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600580
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600580 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3322 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600581
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600581 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3323 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600582
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600582 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3324 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600583
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600583 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3325 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600584
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600584 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3326 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600585
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600585 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3327 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600586
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600586 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3328 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600587
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600587 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3329 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600588
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600588 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3330 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600589
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600589 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3331 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 63.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600590
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600590 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3332 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600592
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600592 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3333 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600593
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600593 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3334 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600594
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600594 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3335 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600595
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600595 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3336 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600596
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600596 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3337 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600597
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600597 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3338 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600598
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600598 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3339 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600600
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600600 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3340 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600601
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600601 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3341 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600602
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600602 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3342 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600603
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600603 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3343 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600604
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600604 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3344 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600605
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600605 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3345 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600606
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600606 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3346 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600609
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600609 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3347 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600610
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600610 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3348 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600611
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600611 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3349 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600612
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600612 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3350 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600613
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600613 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3351 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600615
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600615 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3352 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600616
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600616 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3353 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600617
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600617 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3354 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600618
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600618 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3355 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600619
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600619 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3356 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600620
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600620 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3357 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600621
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600621 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3358 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600622
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600622 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3359 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600623
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600623 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3360 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600624
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600624 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3361 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600626
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600626 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3362 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600628
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600628 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3363 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600629
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600629 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3364 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600630
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600630 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3365 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600633
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600633 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3366 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600635
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600635 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3367 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600637
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600637 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3368 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600638
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600638 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3369 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600639
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600639 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3370 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600640
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600640 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3371 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600641
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600641 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3372 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600642
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600642 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3373 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600643
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600643 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3374 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600644
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600644 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3375 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600645
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600645 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3376 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600648
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600648 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3377 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600649
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600649 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3378 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600650
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600650 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3379 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600651
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600651 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3380 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600653
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600653 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3381 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600654
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600654 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3382 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600655
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600655 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3383 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 64.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600657
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600657 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3384 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600658
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600658 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3385 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600660
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600660 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3386 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600661
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600661 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3387 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600662
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600662 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3388 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600663
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600663 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3389 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600664
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600664 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3390 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600665
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600665 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3391 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600666
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600666 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3392 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600667
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600667 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3393 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600668
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600668 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3394 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600671
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600671 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3395 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600673
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600673 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3396 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600674
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600674 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3397 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600675
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600675 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3398 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600676
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600676 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3399 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600678
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600678 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3400 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600679
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600679 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3401 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600681
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600681 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3402 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600682
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600682 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3403 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600683
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600683 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3404 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600684
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600684 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3405 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600685
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600685 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3406 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600686
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600686 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3407 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600688
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600688 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3408 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600689
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600689 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3409 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600690
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600690 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3410 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600691
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600691 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3411 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600692
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600692 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3412 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600693
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600693 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3413 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600694
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600694 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3414 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600697
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600697 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3415 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600698
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600698 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3416 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600699
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600699 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3417 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600702
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600702 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3418 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600703
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600703 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3419 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600704
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600704 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3420 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600706
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600706 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3421 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600707
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600707 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3422 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600708
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600708 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3423 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600710
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600710 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3424 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600711
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600711 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3425 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600712
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600712 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3426 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600713
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600713 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3427 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600714
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600714 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3428 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600715
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600715 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3429 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600716
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600716 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3430 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600717
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600717 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3431 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600718
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600718 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3432 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600719
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600719 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3433 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600720
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600720 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3434 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600721
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600721 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3435 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 65.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600722
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600722 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3436 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600724
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600724 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3437 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600725
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600725 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3438 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600726
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600726 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3439 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600727
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600727 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3440 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600728
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600728 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3441 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600729
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600729 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3442 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600730
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600730 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3443 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600731
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600731 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3444 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600732
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600732 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3445 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600733
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600733 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3446 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600734
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600734 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3447 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600735
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600735 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3448 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600736
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600736 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3449 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600737
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600737 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3450 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600738
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600738 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3451 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600739
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600739 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3452 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600740
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600740 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3453 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600741
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600741 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3454 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600742
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600742 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3455 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600743
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600743 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3456 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600744
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600744 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3457 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600745
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600745 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3458 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600746
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600746 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3459 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600748
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600748 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3460 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600749
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600749 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3461 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600750
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600750 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3462 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600751
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600751 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3463 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600753
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600753 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3464 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600754
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600754 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3465 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600755
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600755 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3466 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600756
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600756 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3467 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600757
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600757 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3468 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600758
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600758 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3469 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600759
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600759 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3470 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600760
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600760 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3471 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600761
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600761 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3472 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600763
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600763 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3473 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600764
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600764 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3474 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600765
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600765 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3475 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600768
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600768 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3476 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600769
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600769 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3477 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600770
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600770 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3478 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600771
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600771 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3479 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600773
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600773 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3480 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600774
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600774 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3481 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600775
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600775 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3482 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600776
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600776 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3483 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600777
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600777 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3484 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600778
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600778 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3485 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600779
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600779 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3486 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600780
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600780 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3487 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 66.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600782
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600782 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3488 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600783
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600783 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3489 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600784
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600784 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3490 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600785
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600785 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3491 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600787
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600787 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3492 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600789
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600789 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3493 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600790
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600790 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3494 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600791
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600791 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3495 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600792
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600792 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3496 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600793
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600793 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3497 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600794
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600794 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3498 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600795
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600795 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3499 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600796
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600796 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3500 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600797
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600797 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3501 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600798
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600798 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3502 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600800
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600800 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3503 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600801
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600801 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3504 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600802
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600802 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3505 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600803
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600803 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3506 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600805
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600805 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3507 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600807
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600807 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3508 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600808
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600808 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3509 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600809
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600809 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3510 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600810
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600810 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3511 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600812
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600812 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3512 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600814
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600814 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3513 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600815
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600815 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3514 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600816
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600816 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3515 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600817
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600817 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3516 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600818
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600818 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3517 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600819
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600819 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3518 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600820
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600820 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3519 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600821
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600821 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3520 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600822
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600822 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3521 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600824
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600824 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3522 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600825
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600825 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3523 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600826
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600826 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3524 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600827
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600827 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3525 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600828
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600828 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3526 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600829
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600829 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3527 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600830
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600830 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3528 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600831
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600831 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3529 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600833
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600833 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3530 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600834
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600834 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3531 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600835
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600835 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3532 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600838
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600838 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3533 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600839
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600839 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3534 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600841
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600841 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3535 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600843
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600843 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3536 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600844
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600844 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3537 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600845
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600845 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3538 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600846
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600846 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3539 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 67.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600847
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600847 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3540 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600848
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600848 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3541 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600850
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600850 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3542 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600851
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600851 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3543 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600853
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600853 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3544 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600854
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600854 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3545 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600855
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600855 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3546 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600857
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600857 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3547 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600858
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600858 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3548 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600859
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600859 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3549 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600860
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600860 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3550 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600861
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600861 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3551 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600862
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600862 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3552 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600863
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600863 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3553 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600864
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600864 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3554 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600865
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600865 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3555 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600866
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600866 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3556 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600867
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600867 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3557 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600868
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600868 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3558 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600869
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600869 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3559 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600871
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600871 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3560 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600872
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600872 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3561 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600873
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600873 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3562 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600874
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600874 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3563 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600875
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600875 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3564 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600876
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600876 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3565 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600877
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600877 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3566 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600879
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600879 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3567 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600880
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600880 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3568 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600881
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600881 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3569 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600882
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600882 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3570 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600883
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600883 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3571 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600884
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600884 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3572 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600885
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600885 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3573 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600886
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600886 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3574 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600887
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600887 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3575 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600888
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600888 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3576 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600889
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600889 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3577 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600892
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600892 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3578 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600893
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600893 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3579 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600894
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600894 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3580 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600895
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600895 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3581 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600897
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600897 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3582 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600900
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600900 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3583 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600901
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600901 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3584 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600903
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600903 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3585 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600905
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600905 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3586 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600906
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600906 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3587 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600908
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600908 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3588 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600909
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600909 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3589 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600916
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600916 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3590 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600917
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600917 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3591 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 68.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600918
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600918 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3592 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600919
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600919 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3593 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600925
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600925 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3594 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600926
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600926 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3595 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600927
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600927 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3596 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600928
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600928 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3597 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600929
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600929 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3598 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600930
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600930 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3599 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600933
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600933 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3600 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600935
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600935 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3601 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600936
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600936 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3602 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600938
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600938 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3603 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600939
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600939 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3604 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600941
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600941 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3605 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600955
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600955 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3606 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600956
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600956 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3607 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600958
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600958 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3608 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600959
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600959 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3609 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600960
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600960 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3610 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600961
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600961 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3611 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600962
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600962 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3612 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600963
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600963 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3613 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600965
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600965 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3614 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600966
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600966 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3615 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600967
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600967 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3616 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600968
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600968 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3617 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600969
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600969 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3618 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600970
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600970 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3619 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600971
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600971 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3620 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600973
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600973 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3621 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600975
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600975 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3622 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600976
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600976 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3623 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600977
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600977 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3624 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600979
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600979 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3625 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600980
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600980 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3626 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600981
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600981 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3627 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600982
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600982 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3628 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600983
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600983 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3629 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600984
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600984 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3630 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600985
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600985 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3631 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600986
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600986 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3632 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600987
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600987 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3633 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600988
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600988 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3634 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600989
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600989 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3635 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600990
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600990 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3636 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600992
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600992 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3637 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600993
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600993 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3638 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600995
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600995 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3639 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600996
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600996 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3640 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600997
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600997 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3641 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600998
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600998 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3642 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 600999
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 600999 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3643 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 69.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601000
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601000 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3644 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601001
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601001 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3645 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601002
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601002 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3646 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601003
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601003 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3647 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601005
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601005 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3648 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601006 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3649 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601007 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3650 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601008 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3651 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601009 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3652 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601010
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601010 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3653 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601011 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3654 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601012
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601012 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3655 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601015
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601015 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3656 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601016 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3657 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601018
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601018 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3658 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601019
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601019 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3659 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601020 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3660 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601021
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601021 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3661 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601022
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601022 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3662 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601026
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601026 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3663 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601033
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601033 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3664 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601038
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601038 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3665 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601058
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601058 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3666 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601059
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601059 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3667 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601061
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601061 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3668 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601065
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601065 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3669 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601066
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601066 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3670 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601068
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601068 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3671 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601069
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601069 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3672 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601077
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601077 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3673 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601083
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601083 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3674 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601086
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601086 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3675 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601088
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601088 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3676 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601089
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601089 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3677 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601096
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601096 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3678 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601098
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601098 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3679 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601099
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601099 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3680 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601100
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601100 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3681 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601101
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601101 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3682 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601106
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601106 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3683 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601107
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601107 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3684 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601108
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601108 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3685 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601111
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601111 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3686 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601112
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601112 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3687 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601113
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601113 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3688 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601116
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601116 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3689 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601117
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601117 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3690 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601118
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601118 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3691 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601121
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601121 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3692 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601126
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601126 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3693 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601127
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601127 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3694 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601128
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601128 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3695 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 70.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601133
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601133 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3696 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601136
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601136 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3697 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601137
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601137 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3698 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601138
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601138 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3699 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601139
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601139 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3700 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601155
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601155 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3701 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601156
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601156 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3702 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601158
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601158 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3703 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601162
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601162 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3704 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601163
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601163 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3705 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601166
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601166 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3706 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601168
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601168 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3707 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601169
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601169 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3708 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601177
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601177 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3709 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601179
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601179 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3710 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601186
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601186 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3711 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601187
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601187 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3712 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601188
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601188 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3713 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601198
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601198 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3714 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601199
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601199 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3715 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601200
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601200 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3716 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601208
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601208 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3717 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601211
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601211 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3718 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601212
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601212 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3719 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601216
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601216 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3720 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601218
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601218 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3721 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601222
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601222 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3722 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601225
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601225 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3723 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601226
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601226 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3724 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601228
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601228 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3725 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601229
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601229 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3726 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601231
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601231 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3727 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601233
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601233 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3728 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601236
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601236 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3729 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601238
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601238 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3730 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601279
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601279 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3731 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601288
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601288 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3732 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601298
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601298 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3733 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601311
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601311 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3734 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601318
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601318 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3735 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601319
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601319 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3736 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601326
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601326 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3737 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601328
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601328 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3738 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601330
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601330 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3739 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601333 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3740 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601336
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601336 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3741 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601339
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601339 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3742 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601360
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601360 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3743 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601366
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601366 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3744 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601368
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601368 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3745 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601369
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601369 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3746 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601375
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601375 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3747 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 71.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601377
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601377 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3748 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601388
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601388 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3749 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601390
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601390 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3750 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601398
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601398 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3751 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601399
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601399 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3752 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601456
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601456 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3753 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601500
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601500 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3754 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601512
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601512 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3755 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601515
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601515 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3756 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601518
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601518 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3757 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601519
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601519 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3758 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601528
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601528 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3759 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601555
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601555 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3760 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601566
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601566 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3761 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601567
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601567 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3762 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601568
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601568 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3763 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601577
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601577 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3764 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601579
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601579 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3765 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601588
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601588 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3766 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601595
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601595 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3767 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601598
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601598 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3768 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601599
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601599 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3769 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601600
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601600 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3770 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601601
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601601 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3771 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601606
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601606 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3772 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601607
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601607 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3773 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601608
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601608 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3774 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601609
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601609 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3775 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601611
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601611 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3776 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601615
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601615 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3777 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601616
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601616 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3778 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601618
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601618 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3779 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601619
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601619 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3780 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601628
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601628 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3781 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601633
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601633 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3782 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601636
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601636 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3783 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601658
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601658 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3784 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601665
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601665 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3785 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601666
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601666 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3786 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601668
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601668 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3787 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601669
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601669 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3788 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601677
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601677 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3789 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601678
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601678 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3790 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601686
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601686 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3791 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601688
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601688 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3792 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601689
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601689 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3793 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601696
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601696 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3794 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601698
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601698 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3795 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601699
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601699 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3796 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601700
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601700 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3797 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601702
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601702 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3798 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601717
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601717 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3799 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 72.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601718
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601718 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3800 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601727
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601727 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3801 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601728
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601728 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3802 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601766
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601766 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3803 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601777
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601777 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3804 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601778
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601778 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3805 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601788
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601788 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3806 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601789
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601789 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3807 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601798
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601798 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3808 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601799
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601799 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3809 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601800
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601800 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3810 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601801
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601801 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3811 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601808
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601808 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3812 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601811
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601811 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3813 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601816
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601816 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3814 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601818
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601818 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3815 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601825
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601825 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3816 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601827
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601827 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3817 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601828
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601828 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3818 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601838
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601838 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3819 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601857
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601857 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3820 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601858
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601858 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3821 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601860
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601860 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3822 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601865
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601865 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3823 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601866
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601866 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3824 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601868
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601868 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3825 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601869
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601869 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3826 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601872
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601872 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3827 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601877
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601877 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3828 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601878
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601878 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3829 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601880
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601880 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3830 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601881
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601881 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3831 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601882
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601882 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3832 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601886
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601886 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3833 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601888
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601888 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3834 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601890
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601890 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3835 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601898
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601898 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3836 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601899
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601899 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3837 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601900
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601900 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3838 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601901
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601901 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3839 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601908
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601908 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3840 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601916
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601916 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3841 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601918
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601918 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3842 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601919
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601919 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3843 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601921
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601921 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3844 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601928
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601928 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3845 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601929
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601929 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3846 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601933
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601933 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3847 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601939
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601939 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3848 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601949
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601949 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3849 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601952
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601952 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3850 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601956
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601956 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3851 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 73.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601958
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601958 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3852 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601963
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601963 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3853 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601965
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601965 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3854 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601966
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601966 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3855 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601968
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601968 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3856 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601969
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601969 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3857 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601975
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601975 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3858 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601985
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601985 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3859 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601988
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601988 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3860 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601990
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601990 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3861 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601991
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601991 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3862 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601992
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601992 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3863 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601995
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601995 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3864 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601996
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601996 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3865 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601997
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601997 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3866 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601998
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601998 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3867 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 601999
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 601999 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3868 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603000
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603000 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3869 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603001
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603001 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3870 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603002
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603002 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3871 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603004
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603004 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3872 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603005
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603005 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3873 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603006 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3874 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603007 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3875 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603008 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3876 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603009 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3877 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603010
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603010 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3878 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603011 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3879 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603012
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603012 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3880 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603013
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603013 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3881 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603014
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603014 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3882 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603015
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603015 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3883 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603016 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3884 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603017
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603017 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3885 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603018
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603018 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3886 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603019
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603019 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3887 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603020 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3888 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603021
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603021 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3889 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603022
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603022 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3890 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603023
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603023 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3891 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603025
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603025 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3892 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603026
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603026 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3893 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603027
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603027 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3894 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603028
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603028 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3895 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603029
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603029 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3896 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603030
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603030 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3897 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603031
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603031 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3898 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603032
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603032 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3899 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603033
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603033 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3900 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603035
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603035 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3901 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603036
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603036 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3902 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603037
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603037 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3903 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 74.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603038
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603038 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3904 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603039
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603039 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3905 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603040
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603040 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3906 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603041
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603041 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3907 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603042
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603042 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3908 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603043
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603043 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3909 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603045
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603045 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3910 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603048
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603048 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3911 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603049
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603049 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3912 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603050
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603050 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3913 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603051
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603051 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3914 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603052
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603052 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3915 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603053
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603053 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3916 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603055
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603055 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3917 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603057
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603057 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3918 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603058
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603058 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3919 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603059
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603059 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3920 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603060
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603060 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3921 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603061
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603061 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3922 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603062
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603062 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3923 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603063
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603063 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3924 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603065
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603065 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3925 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603066
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603066 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3926 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603067
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603067 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3927 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603068
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603068 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3928 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603069
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603069 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3929 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603070
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603070 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3930 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603071
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603071 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3931 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603072
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603072 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3932 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603073
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603073 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3933 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603075
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603075 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3934 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603076
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603076 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3935 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603077
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603077 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3936 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603078
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603078 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3937 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603079
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603079 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3938 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603080
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603080 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3939 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603081
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603081 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3940 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603082
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603082 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3941 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603083
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603083 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3942 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603085
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603085 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3943 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603086
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603086 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3944 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603087
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603087 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3945 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603088
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603088 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3946 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603089
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603089 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3947 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603090
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603090 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3948 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603091
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603091 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3949 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603092
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603092 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3950 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603093
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603093 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3951 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603095
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603095 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3952 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603096
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603096 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3953 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603097
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603097 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3954 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603098
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603098 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3955 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 75.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603099
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603099 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3956 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603100
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603100 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3957 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603101
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603101 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3958 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603102
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603102 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3959 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603103
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603103 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3960 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603105
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603105 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3961 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603106
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603106 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3962 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603107
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603107 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3963 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603108
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603108 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3964 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603109
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603109 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3965 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603110
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603110 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3966 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603111
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603111 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3967 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603112
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603112 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3968 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603113
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603113 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3969 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603115
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603115 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3970 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603116
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603116 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3971 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603117
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603117 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3972 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603118
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603118 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3973 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603119
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603119 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3974 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603120
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603120 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3975 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603121
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603121 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3976 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603122
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603122 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3977 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603123
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603123 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3978 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603124
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603124 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3979 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603125
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603125 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3980 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603126
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603126 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3981 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603127
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603127 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3982 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603128
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603128 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3983 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603129
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603129 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3984 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603130
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603130 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3985 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603131
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603131 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3986 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603132
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603132 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3987 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603135
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603135 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3988 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603136
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603136 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3989 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603137
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603137 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3990 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603138
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603138 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3991 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603139
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603139 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3992 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603150
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603150 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3993 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603151
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603151 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3994 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603153
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603153 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3995 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603155
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603155 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3996 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603156
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603156 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3997 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603158
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603158 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3998 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603159
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603159 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 3999 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603160
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603160 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4000 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603161
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603161 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4001 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603162
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603162 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4002 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603163
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603163 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4003 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603165
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603165 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4004 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603166
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603166 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4005 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603167
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603167 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4006 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603168
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603168 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4007 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 76.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603169
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603169 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4008 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603170
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603170 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4009 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603171
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603171 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4010 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603172
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603172 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4011 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603173
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603173 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4012 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603175
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603175 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4013 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603176
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603176 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4014 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603177
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603177 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4015 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603178
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603178 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4016 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603179
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603179 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4017 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603180
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603180 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4018 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603181
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603181 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4019 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603182
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603182 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4020 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603183
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603183 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4021 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603185
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603185 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4022 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603186
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603186 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4023 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603187
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603187 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4024 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603188
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603188 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4025 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603189
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603189 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4026 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603190
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603190 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4027 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603191
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603191 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4028 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603192
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603192 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4029 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603193
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603193 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4030 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603194
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603194 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4031 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603195
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603195 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4032 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603196
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603196 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4033 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603197
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603197 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4034 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603198
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603198 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4035 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603199
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603199 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4036 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603200
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603200 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4037 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603201
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603201 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4038 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603202
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603202 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4039 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603203
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603203 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4040 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603205
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603205 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4041 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603206
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603206 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4042 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603207
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603207 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4043 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603208
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603208 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4044 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603209
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603209 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4045 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603210
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603210 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4046 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603211
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603211 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4047 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603212
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603212 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4048 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603213
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603213 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4049 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603214
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603214 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4050 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603215
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603215 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4051 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603216
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603216 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4052 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603217
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603217 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4053 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603218
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603218 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4054 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603219
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603219 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4055 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603220
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603220 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4056 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603221
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603221 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4057 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603222
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603222 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4058 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603223
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603223 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4059 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 77.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603225
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603225 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4060 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603226
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603226 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4061 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603227
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603227 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4062 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603228
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603228 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4063 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603229
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603229 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4064 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603230
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603230 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4065 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603231
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603231 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4066 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603232
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603232 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4067 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603233
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603233 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4068 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603235
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603235 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4069 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603236
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603236 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4070 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603237
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603237 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4071 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603238
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603238 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4072 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603239
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603239 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4073 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603248
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603248 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4074 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603255
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603255 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4075 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603256
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603256 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4076 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603257
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603257 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4077 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603258
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603258 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4078 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603259
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603259 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4079 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603260
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603260 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4080 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603261
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603261 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4081 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603262
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603262 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4082 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603266
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603266 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4083 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603267
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603267 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4084 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603268
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603268 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4085 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603269
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603269 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4086 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603270
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603270 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4087 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603271
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603271 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4088 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603272
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603272 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4089 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603273
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603273 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4090 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603275
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603275 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4091 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603276
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603276 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4092 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603277
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603277 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4093 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603278
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603278 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4094 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603279
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603279 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4095 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603280
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603280 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4096 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603281
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603281 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4097 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603282
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603282 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4098 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603283
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603283 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4099 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603284
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603284 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4100 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603285
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603285 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4101 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603286
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603286 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4102 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603288
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603288 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4103 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603289
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603289 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4104 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603290
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603290 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4105 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603291
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603291 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4106 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603293
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603293 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4107 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603296
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603296 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4108 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603297
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603297 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4109 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603298
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603298 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4110 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603299
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603299 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4111 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 78.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603300
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603300 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4112 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603301
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603301 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4113 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603303
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603303 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4114 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603305
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603305 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4115 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603306
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603306 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4116 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603307
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603307 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4117 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603308
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603308 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4118 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603309
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603309 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4119 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603310
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603310 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4120 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603311
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603311 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4121 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603312
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603312 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4122 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603313
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603313 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4123 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603315
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603315 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4124 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603316
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603316 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4125 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603317
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603317 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4126 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603318
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603318 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4127 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603319
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603319 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4128 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603320
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603320 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4129 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603321
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603321 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4130 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603322
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603322 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4131 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603323
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603323 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4132 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603324
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603324 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4133 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603325
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603325 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4134 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603326
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603326 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4135 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603327
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603327 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4136 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603328
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603328 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4137 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603329
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603329 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4138 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603330
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603330 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4139 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603331
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603331 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4140 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603332
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603332 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4141 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603333 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4142 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603334
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603334 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4143 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603335
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603335 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4144 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603336
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603336 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4145 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603337
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603337 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4146 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603338
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603338 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4147 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603339
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603339 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4148 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603341
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603341 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4149 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603344
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603344 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4150 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603345
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603345 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4151 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603348
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603348 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4152 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603350
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603350 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4153 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603351
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603351 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4154 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603352
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603352 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4155 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603353
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603353 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4156 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603355
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603355 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4157 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603356
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603356 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4158 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603357
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603357 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4159 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603358
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603358 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4160 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603359
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603359 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4161 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603360
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603360 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4162 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603363
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603363 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4163 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 79.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603365
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603365 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4164 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603366
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603366 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4165 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603367
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603367 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4166 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603368
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603368 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4167 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603369
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603369 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4168 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603370
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603370 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4169 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603373
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603373 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4170 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603375
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603375 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4171 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603376
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603376 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4172 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603377
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603377 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4173 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603378
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603378 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4174 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603379
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603379 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4175 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603380
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603380 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4176 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603381
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603381 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4177 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603382
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603382 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4178 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603383
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603383 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4179 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603385
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603385 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4180 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603386
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603386 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4181 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603387
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603387 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4182 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603389
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603389 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4183 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603390
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603390 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4184 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603391
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603391 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4185 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603392
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603392 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4186 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603393
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603393 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4187 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603395
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603395 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4188 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603396
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603396 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4189 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603398
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603398 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4190 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603399
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603399 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4191 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603400
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603400 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4192 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603402
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603402 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4193 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603406
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603406 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4194 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603407
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603407 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4195 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603408
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603408 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4196 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603409
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603409 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4197 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603416
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603416 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4198 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603418
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603418 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4199 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603421
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603421 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4200 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603429
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603429 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4201 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603435
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603435 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4202 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603439
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603439 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4203 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603444
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603444 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4204 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603456
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603456 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4205 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603458
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603458 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4206 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603459
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603459 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4207 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603466
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603466 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4208 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603477
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603477 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4209 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603486
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603486 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4210 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603488
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603488 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4211 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603489
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603489 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4212 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603496
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603496 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4213 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603499
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603499 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4214 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603500
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603500 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4215 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603501
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603501 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4216 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 80.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603505
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603505 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4217 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603506
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603506 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4218 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603507
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603507 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4219 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603508
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603508 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4220 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603511
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603511 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4221 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603515
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603515 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4222 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603516
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603516 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4223 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603517
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603517 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4224 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603518
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603518 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4225 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603519
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603519 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4226 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603520
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603520 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4227 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603527
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603527 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4228 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603528
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603528 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4229 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603529
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603529 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4230 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603530
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603530 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4231 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603533
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603533 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4232 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603535
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603535 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4233 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603536
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603536 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4234 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603538
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603538 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4235 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603551
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603551 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4236 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603556
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603556 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4237 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603557
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603557 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4238 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603558
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603558 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4239 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603559
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603559 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4240 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603565
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603565 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4241 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603566
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603566 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4242 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603567
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603567 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4243 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603568
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603568 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4244 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603569
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603569 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4245 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603577
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603577 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4246 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603578
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603578 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4247 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603579
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603579 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4248 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603580
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603580 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4249 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603583
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603583 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4250 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603585
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603585 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4251 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603586
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603586 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4252 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603587
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603587 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4253 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603588
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603588 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4254 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603589
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603589 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4255 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603590
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603590 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4256 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603595
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603595 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4257 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603596
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603596 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4258 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603598
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603598 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4259 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603599
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603599 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4260 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603600
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603600 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4261 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603601
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603601 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4262 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603602
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603602 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4263 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603605
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603605 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4264 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603606
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603606 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4265 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603607
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603607 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4266 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603608
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603608 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4267 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603609
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603609 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4268 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 81.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603610
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603610 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4269 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603611
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603611 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4270 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603612
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603612 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4271 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603613
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603613 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4272 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603615
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603615 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4273 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603616
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603616 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4274 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603617
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603617 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4275 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603618
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603618 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4276 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603619
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603619 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4277 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603626
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603626 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4278 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603628
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603628 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4279 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603629
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603629 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4280 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603630
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603630 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4281 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603633
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603633 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4282 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603636
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603636 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4283 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603637
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603637 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4284 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603638
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603638 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4285 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603639
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603639 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4286 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603648
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603648 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4287 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603650
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603650 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4288 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603655
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603655 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4289 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603656
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603656 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4290 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603657
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603657 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4291 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603658
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603658 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4292 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603659
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603659 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4293 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603660
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603660 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4294 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603661
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603661 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4295 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603662
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603662 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4296 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603663
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603663 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4297 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603665
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603665 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4298 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603666
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603666 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4299 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603667
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603667 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4300 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603668
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603668 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4301 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603669
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603669 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4302 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603676
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603676 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4303 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603677
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603677 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4304 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603678
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603678 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4305 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603679
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603679 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4306 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603680
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603680 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4307 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603681
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603681 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4308 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603682
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603682 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4309 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603683
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603683 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4310 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603685
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603685 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4311 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603686
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603686 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4312 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603687
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603687 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4313 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603688
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603688 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4314 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603689
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603689 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4315 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603690
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603690 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4316 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603693
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603693 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4317 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603696
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603696 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4318 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603697
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603697 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4319 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603698
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603698 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4320 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 82.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603699
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603699 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4321 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603700
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603700 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4322 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603701
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603701 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4323 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603703
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603703 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4324 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603706
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603706 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4325 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603707
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603707 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4326 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603708
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603708 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4327 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603709
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603709 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4328 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603711
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603711 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4329 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603712
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603712 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4330 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603713
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603713 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4331 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603716
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603716 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4332 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603717
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603717 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4333 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603718
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603718 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4334 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603719
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603719 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4335 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603721
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603721 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4336 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603722
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603722 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4337 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603725
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603725 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4338 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603726
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603726 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4339 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603727
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603727 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4340 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603728
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603728 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4341 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603729
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603729 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4342 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603730
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603730 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4343 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603733
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603733 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4344 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603737
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603737 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4345 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603738
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603738 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4346 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603739
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603739 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4347 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603755
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603755 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4348 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603757
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603757 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4349 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603758
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603758 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4350 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603759
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603759 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4351 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603766
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603766 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4352 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603767
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603767 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4353 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603768
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603768 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4354 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603773
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603773 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4355 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603776
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603776 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4356 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603777
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603777 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4357 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603778
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603778 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4358 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603779
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603779 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4359 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603786
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603786 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4360 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603787
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603787 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4361 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603788
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603788 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4362 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603789
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603789 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4363 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603790
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603790 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4364 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603797
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603797 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4365 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603798
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603798 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4366 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603799
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603799 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4367 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603800
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603800 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4368 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603801
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603801 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4369 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603803
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603803 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4370 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603806
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603806 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4371 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603808
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603808 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4372 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 83.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603809
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603809 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4373 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603810
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603810 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4374 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603811
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603811 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4375 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603813
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603813 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4376 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603815
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603815 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4377 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603816
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603816 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4378 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603817
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603817 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4379 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603818
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603818 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4380 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603819
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603819 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4381 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603822
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603822 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4382 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603823
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603823 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4383 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603825
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603825 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4384 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603826
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603826 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4385 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603828
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603828 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4386 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603829
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603829 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4387 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603833
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603833 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4388 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603836
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603836 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4389 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603838
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603838 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4390 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603839
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603839 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4391 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603843
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603843 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4392 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603848
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603848 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4393 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603855
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603855 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4394 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603856
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603856 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4395 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603858
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603858 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4396 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603859
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603859 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4397 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603860
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603860 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4398 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603861
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603861 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4399 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603863
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603863 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4400 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603866
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603866 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4401 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603867
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603867 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4402 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603868
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603868 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4403 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603869
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603869 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4404 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603871
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603871 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4405 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603876
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603876 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4406 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603877
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603877 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4407 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603878
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603878 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4408 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603879
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603879 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4409 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603880
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603880 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4410 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603881
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603881 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4411 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603882
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603882 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4412 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603883
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603883 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4413 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603885
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603885 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4414 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603886
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603886 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4415 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603887
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603887 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4416 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603888
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603888 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4417 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603889
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603889 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4418 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603890
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603890 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4419 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603893
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603893 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4420 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603895
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603895 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4421 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603896
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603896 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4422 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603897
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603897 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4423 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603898
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603898 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4424 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 84.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603899
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603899 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4425 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603900
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603900 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4426 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603901
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603901 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4427 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603903
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603903 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4428 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603906
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603906 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4429 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603908
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603908 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4430 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603909
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603909 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4431 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603912
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603912 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4432 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603915
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603915 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4433 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603916
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603916 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4434 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603917
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603917 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4435 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603918
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603918 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4436 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603919
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603919 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4437 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603920
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603920 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4438 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603922
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603922 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4439 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603926
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603926 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4440 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603927
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603927 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4441 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603928
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603928 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4442 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603929
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603929 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4443 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603931
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603931 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4444 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603933
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603933 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4445 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603936
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603936 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4446 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603937
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603937 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4447 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603938
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603938 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4448 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603939
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603939 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4449 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603948
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603948 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4450 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603949
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603949 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4451 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603950
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603950 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4452 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603955
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603955 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4453 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603956
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603956 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4454 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603958
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603958 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4455 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603959
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603959 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4456 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603960
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603960 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4457 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603966
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603966 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4458 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603967
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603967 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4459 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603968
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603968 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4460 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603969
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603969 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4461 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603970
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603970 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4462 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603976
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603976 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4463 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603977
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603977 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4464 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603978
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603978 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4465 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603979
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603979 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4466 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603980
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603980 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4467 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603982
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603982 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4468 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603983
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603983 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4469 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603985
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603985 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4470 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603986
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603986 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4471 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603987
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603987 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4472 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603988
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603988 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4473 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603989
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603989 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4474 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603990
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603990 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4475 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603991
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603991 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4476 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 85.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603992
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603992 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4477 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603993
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603993 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4478 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603995
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603995 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4479 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603997
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603997 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4480 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603998
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603998 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4481 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 603999
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 603999 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4482 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605001
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605001 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4483 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605003
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605003 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4484 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605005
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605005 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4485 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605006 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4486 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605007 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4487 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605008 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4488 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605009 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4489 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605011 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4490 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605016 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4491 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605018
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605018 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4492 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605020 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4493 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605028
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605028 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4494 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605033
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605033 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4495 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605050
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605050 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4496 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605055
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605055 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4497 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605056
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605056 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4498 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605058
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605058 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4499 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605060
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605060 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4500 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605066
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605066 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4501 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605068
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605068 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4502 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605069
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605069 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4503 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605077
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605077 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4504 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605080
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605080 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4505 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605086
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605086 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4506 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605088
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605088 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4507 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605089
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605089 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4508 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605090
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605090 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4509 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605098
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605098 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4510 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605099
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605099 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4511 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605100
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605100 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4512 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605108
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605108 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4513 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605111
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605111 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4514 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605116
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605116 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4515 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605117
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605117 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4516 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605118
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605118 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4517 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605122
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605122 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4518 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605123
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605123 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4519 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605128
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605128 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4520 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605133
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605133 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4521 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605136
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605136 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4522 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605138
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605138 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4523 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605151
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605151 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4524 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605155
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605155 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4525 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605158
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605158 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4526 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605162
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605162 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4527 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605166
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605166 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4528 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 86.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605167
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605167 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4529 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605168
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605168 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4530 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605169
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605169 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4531 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605177
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605177 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4532 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605178
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605178 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4533 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605179
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605179 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4534 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605180
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605180 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4535 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605183
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605183 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4536 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605186
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605186 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4537 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605188
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605188 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4538 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605189
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605189 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4539 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605196
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605196 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4540 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605198
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605198 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4541 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605199
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605199 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4542 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605208
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605208 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4543 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605218
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605218 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4544 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605222
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605222 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4545 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605228
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605228 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4546 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605255
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605255 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4547 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605258
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605258 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4548 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605259
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605259 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4549 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605266
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605266 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4550 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605268
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605268 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4551 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605277
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605277 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4552 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605286
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605286 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4553 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605287
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605287 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4554 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605288
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605288 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4555 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605289
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605289 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4556 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605296
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605296 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4557 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605298
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605298 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4558 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605299
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605299 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4559 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605300
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605300 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4560 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605303
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605303 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4561 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605305
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605305 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4562 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605318
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605318 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4563 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605319
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605319 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4564 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605333 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4565 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605336
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605336 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4566 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605337
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605337 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4567 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605338
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605338 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4568 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605339
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605339 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4569 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605358
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605358 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4570 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605365
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605365 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4571 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605366
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605366 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4572 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605368
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605368 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4573 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605369
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605369 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4574 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605376
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605376 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4575 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605377
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605377 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4576 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605378
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605378 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4577 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605388
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605388 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4578 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605389
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605389 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4579 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605398
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605398 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4580 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 87.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605399
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605399 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4581 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605488
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605488 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4582 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605499
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605499 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4583 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605500
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605500 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4584 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605507
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605507 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4585 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605555
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605555 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4586 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605566
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605566 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4587 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605567
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605567 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4588 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605577
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605577 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4589 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605580
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605580 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4590 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605588
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605588 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4591 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605589
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605589 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4592 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605598
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605598 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4593 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 605599
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 605599 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4594 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688001
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688001 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4595 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688002
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688002 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4596 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688003
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688003 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4597 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688004
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688004 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4598 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688005
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688005 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4599 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688006 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4600 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688007 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4601 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688008 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4602 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688009 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4603 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688010
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688010 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4604 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688011 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4605 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688012
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688012 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4606 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688013
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688013 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4607 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688015
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688015 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4608 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688016 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4609 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688017
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688017 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4610 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688018
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688018 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4611 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688019
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688019 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4612 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688020 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4613 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688021
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688021 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4614 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688022
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688022 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4615 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688023
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688023 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4616 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688025
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688025 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4617 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688026
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688026 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4618 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688027
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688027 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4619 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688028
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688028 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4620 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688029
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688029 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4621 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688030
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688030 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4622 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688031
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688031 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4623 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688032
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688032 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4624 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688033
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688033 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4625 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688035
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688035 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4626 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688036
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688036 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4627 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688037
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688037 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4628 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688038
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688038 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4629 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688039
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688039 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4630 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688041
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688041 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4631 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688045
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688045 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4632 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 88.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688046
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688046 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4633 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688047
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688047 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4634 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688048
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688048 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4635 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688049
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688049 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4636 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688050
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688050 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4637 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688051
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688051 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4638 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688052
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688052 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4639 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688053
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688053 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4640 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688055
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688055 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4641 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688056
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688056 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4642 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688057
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688057 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4643 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688058
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688058 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4644 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688059
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688059 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4645 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688060
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688060 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4646 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688061
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688061 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4647 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688062
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688062 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4648 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688063
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688063 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4649 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688065
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688065 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4650 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688066
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688066 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4651 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688067
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688067 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4652 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688068
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688068 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4653 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688069
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688069 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4654 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688070
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688070 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4655 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688071
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688071 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4656 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688072
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688072 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4657 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688073
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688073 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4658 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688075
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688075 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4659 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688076
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688076 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4660 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688077
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688077 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4661 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688078
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688078 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4662 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688079
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688079 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4663 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688080
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688080 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4664 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688081
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688081 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4665 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688082
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688082 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4666 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688083
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688083 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4667 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688084
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688084 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4668 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688085
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688085 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4669 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688087
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688087 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4670 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688088
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688088 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4671 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688089
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688089 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4672 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688090
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688090 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4673 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688091
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688091 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4674 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688092
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688092 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4675 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688093
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688093 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4676 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688095
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688095 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4677 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688096
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688096 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4678 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688097
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688097 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4679 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688098
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688098 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4680 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688099
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688099 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4681 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688100
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688100 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4682 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688101
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688101 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4683 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688102
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688102 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4684 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 89.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688103
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688103 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4685 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688105
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688105 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4686 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688106
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688106 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4687 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688107
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688107 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4688 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688108
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688108 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4689 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688109
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688109 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4690 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688110
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688110 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4691 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688111
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688111 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4692 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688112
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688112 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4693 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688113
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688113 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4694 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688114
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688114 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4695 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688115
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688115 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4696 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688116
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688116 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4697 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688117
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688117 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4698 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688118
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688118 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4699 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688119
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688119 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4700 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688120
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688120 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4701 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688121
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688121 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4702 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688122
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688122 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4703 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688123
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688123 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4704 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688125
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688125 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4705 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688126
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688126 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4706 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688127
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688127 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4707 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688128
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688128 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4708 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688129
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688129 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4709 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688130
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688130 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4710 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688131
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688131 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4711 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688132
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688132 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4712 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688133
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688133 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4713 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688135
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688135 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4714 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688136
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688136 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4715 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688137
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688137 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4716 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688138
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688138 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4717 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688139
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688139 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4718 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688141
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688141 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4719 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688143
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688143 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4720 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688146
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688146 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4721 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688147
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688147 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4722 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688148
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688148 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4723 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688150
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688150 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4724 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688151
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688151 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4725 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688152
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688152 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4726 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688153
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688153 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4727 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688155
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688155 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4728 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688156
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688156 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4729 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688157
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688157 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4730 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688158
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688158 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4731 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688159
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688159 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4732 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688160
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688160 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4733 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688161
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688161 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4734 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688162
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688162 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4735 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688163
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688163 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4736 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 90.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688165
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688165 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4737 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688166
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688166 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4738 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688167
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688167 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4739 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688168
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688168 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4740 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688169
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688169 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4741 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688170
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688170 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4742 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688171
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688171 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4743 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688172
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688172 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4744 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688173
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688173 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4745 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688175
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688175 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4746 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688176
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688176 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4747 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688177
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688177 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4748 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688178
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688178 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4749 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688179
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688179 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4750 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688180
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688180 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4751 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688181
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688181 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4752 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688182
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688182 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4753 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688183
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688183 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4754 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688184
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688184 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4755 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688185
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688185 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4756 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688186
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688186 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4757 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688187
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688187 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4758 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688188
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688188 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4759 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688189
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688189 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4760 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688190
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688190 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4761 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688191
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688191 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4762 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688192
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688192 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4763 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688193
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688193 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4764 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688195
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688195 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4765 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688196
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688196 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4766 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688197
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688197 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4767 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688198
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688198 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4768 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688199
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688199 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4769 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688200
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688200 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4770 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688201
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688201 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4771 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688202
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688202 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4772 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688203
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688203 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4773 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688205
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688205 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4774 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688206
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688206 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4775 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688207
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688207 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4776 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688208
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688208 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4777 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688209
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688209 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4778 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688210
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688210 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4779 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688211
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688211 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4780 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688212
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688212 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4781 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688213
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688213 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4782 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688215
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688215 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4783 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688216
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688216 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4784 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688217
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688217 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4785 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688218
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688218 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4786 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688219
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688219 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4787 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688220
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688220 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4788 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 91.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688221
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688221 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4789 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688222
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688222 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4790 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688223
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688223 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4791 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688225
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688225 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4792 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688226
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688226 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4793 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688227
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688227 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4794 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688228
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688228 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4795 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688229
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688229 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4796 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688230
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688230 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4797 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688231
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688231 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4798 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688232
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688232 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4799 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688233
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688233 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4800 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688234
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688234 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4801 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688235
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688235 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4802 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688236
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688236 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4803 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688237
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688237 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4804 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688238
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688238 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4805 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688239
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688239 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4806 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688244
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688244 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4807 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688246
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688246 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4808 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688247
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688247 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4809 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688248
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688248 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4810 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688249
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688249 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4811 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688251
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688251 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4812 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688252
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688252 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4813 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688253
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688253 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4814 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688255
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688255 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4815 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688256
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688256 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4816 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688257
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688257 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4817 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688258
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688258 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4818 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688259
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688259 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4819 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688260
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688260 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4820 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688261
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688261 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4821 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688262
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688262 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4822 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688265
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688265 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4823 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688266
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688266 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4824 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688267
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688267 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4825 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688268
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688268 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4826 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688269
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688269 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4827 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688270
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688270 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4828 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688271
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688271 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4829 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688272
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688272 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4830 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688273
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688273 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4831 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688275
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688275 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4832 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688276
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688276 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4833 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688277
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688277 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4834 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688278
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688278 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4835 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688279
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688279 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4836 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688280
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688280 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4837 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688281
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688281 from 2025-05-16 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4838 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688282
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688282 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4839 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688283
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688283 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4840 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 92.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688285
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688285 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4841 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688286
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688286 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4842 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688288
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688288 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4843 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688289
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688289 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4844 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688290
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688290 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4845 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688291
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688291 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4846 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688292
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688292 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4847 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688293
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688293 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4848 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688295
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688295 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4849 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688296
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688296 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4850 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688297
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688297 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4851 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688298
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688298 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4852 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688299
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688299 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4853 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688300
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688300 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4854 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688301
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688301 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4855 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688302
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688302 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4856 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688303
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688303 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4857 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688305
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688305 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4858 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688306
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688306 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4859 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688307
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688307 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4860 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688308
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688308 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4861 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688309
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688309 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4862 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688310
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688310 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4863 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688311
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688311 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4864 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688312
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688312 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4865 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688313
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688313 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4866 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688314
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688314 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4867 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688315
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688315 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4868 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688316
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688316 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4869 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688317
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688317 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4870 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688318
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688318 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4871 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688319
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688319 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4872 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688320
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688320 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4873 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688321
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688321 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4874 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688322
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688322 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4875 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688323
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688323 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4876 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688325
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688325 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4877 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688326
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688326 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4878 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688327
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688327 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4879 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688328
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688328 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4880 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688329
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688329 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4881 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688330
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688330 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4882 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688331
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688331 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4883 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688332
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688332 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4884 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688333 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4885 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688334
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688334 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4886 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688335
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688335 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4887 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688336
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688336 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4888 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688337
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688337 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4889 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688338
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688338 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4890 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688339
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688339 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4891 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688343
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688343 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4892 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 93.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688345
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688345 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4893 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688347
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688347 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4894 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688348
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688348 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4895 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688349
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688349 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4896 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688350
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688350 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4897 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688351
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688351 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4898 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688352
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688352 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4899 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688353
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688353 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4900 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688355
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688355 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4901 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688356
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688356 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4902 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688357
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688357 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4903 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688358
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688358 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4904 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688359
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688359 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4905 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688360
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688360 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4906 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688361
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688361 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4907 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688362
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688362 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4908 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688363
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688363 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4909 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688365
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688365 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4910 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688366
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688366 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4911 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688367
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688367 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4912 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688368
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688368 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4913 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688369
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688369 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4914 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688370
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688370 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4915 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688371
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688371 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4916 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688372
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688372 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4917 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688373
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688373 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4918 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688375
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688375 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4919 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688376
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688376 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4920 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688377
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688377 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4921 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688378
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688378 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4922 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688379
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688379 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4923 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688380
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688380 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4924 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688381
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688381 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4925 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688382
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688382 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4926 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688383
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688383 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4927 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688385
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688385 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4928 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688386
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688386 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4929 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688387
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688387 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4930 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688388
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688388 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4931 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688389
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688389 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4932 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688390
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688390 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4933 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688391
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688391 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4934 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688392
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688392 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4935 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688393
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688393 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4936 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688395
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688395 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4937 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688396
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688396 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4938 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688398
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688398 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4939 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688399
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688399 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4940 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688400
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688400 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4941 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688401
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688401 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4942 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688403
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688403 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4943 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688408
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688408 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4944 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 94.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688409
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688409 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4945 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688410
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688410 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4946 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688411
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688411 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4947 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688416
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688416 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4948 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688418
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688418 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4949 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688419
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688419 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4950 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688420
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688420 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4951 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688425
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688425 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4952 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688426
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688426 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4953 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688428
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688428 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4954 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688429
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688429 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4955 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688432
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688432 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4956 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688433
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688433 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4957 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688435
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688435 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4958 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688439
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688439 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4959 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688443
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688443 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4960 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688448
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688448 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4961 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688449
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688449 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4962 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688450
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688450 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4963 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688455
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688455 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4964 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688456
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688456 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4965 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688458
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688458 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4966 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688459
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688459 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4967 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688466
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688466 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4968 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688468
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688468 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4969 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688469
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688469 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4970 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688472
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688472 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4971 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688475
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688475 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4972 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688478
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688478 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4973 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688479
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688479 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4974 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688480
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688480 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4975 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688484
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688484 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4976 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688485
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688485 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4977 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688486
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688486 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4978 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688488
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688488 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4979 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688489
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688489 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4980 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688496
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688496 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4981 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688498
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688498 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4982 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688499
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688499 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4983 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688500
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688500 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4984 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688501
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688501 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4985 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688502
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688502 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4986 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688503
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688503 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4987 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688505
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688505 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4988 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688506
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688506 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4989 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688507
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688507 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4990 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688508
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688508 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4991 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688509
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688509 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4992 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688510
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688510 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4993 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688511
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688511 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4994 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688512
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688512 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4995 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688513
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688513 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4996 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 95.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688515
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688515 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4997 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688516
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688516 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4998 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688517
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688517 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 4999 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688518
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688518 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5000 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688519
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688519 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5001 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688520
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688520 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5002 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688521
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688521 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5003 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688522
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688522 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5004 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688523
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688523 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5005 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688525
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688525 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5006 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688526
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688526 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5007 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688528
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688528 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5008 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688529
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688529 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5009 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688530
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688530 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5010 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688531
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688531 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5011 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688533
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688533 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5012 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688535
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688535 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5013 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688536
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688536 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5014 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688538
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688538 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5015 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688539
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688539 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5016 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688543
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688543 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5017 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688545
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688545 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5018 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688548
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688548 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5019 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688549
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688549 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5020 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688550
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688550 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5021 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688551
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688551 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5022 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688552
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688552 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5023 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688553
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688553 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5024 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688556
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688556 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5025 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688557
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688557 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5026 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688558
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688558 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5027 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688559
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688559 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5028 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688560
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688560 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5029 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688561
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688561 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5030 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688562
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688562 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5031 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688563
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688563 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5032 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688565
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688565 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5033 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688566
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688566 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5034 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688567
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688567 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5035 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688568
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688568 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5036 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688569
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688569 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5037 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688570
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688570 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5038 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688571
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688571 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5039 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688573
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688573 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5040 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688575
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688575 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5041 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688576
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688576 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5042 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688577
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688577 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5043 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688578
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688578 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5044 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688579
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688579 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5045 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688580
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688580 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5046 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688581
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688581 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5047 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688582
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688582 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5048 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 96.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688583
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688583 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5049 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688584
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688584 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5050 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688585
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688585 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5051 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688586
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688586 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5052 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688588
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688588 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5053 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688589
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688589 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5054 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688590
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688590 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5055 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688591
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688591 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5056 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688592
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688592 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5057 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688593
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688593 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5058 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688595
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688595 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5059 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688596
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688596 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5060 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688597
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688597 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5061 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688598
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688598 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5062 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688599
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688599 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5063 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688600
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688600 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5064 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688601
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688601 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5065 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688602
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688602 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5066 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688603
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688603 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5067 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688605
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688605 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5068 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688606
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688606 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5069 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688607
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688607 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5070 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688608
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688608 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5071 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688609
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688609 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5072 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688610
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688610 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5073 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688611
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688611 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5074 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688612
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688612 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5075 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688613
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688613 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5076 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688615
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688615 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5077 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688616
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688616 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5078 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688617
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688617 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5079 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688618
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688618 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5080 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688619
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688619 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5081 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688620
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688620 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5082 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688621
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688621 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5083 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688622
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688622 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5084 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688623
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688623 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5085 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688625
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688625 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5086 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688626
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688626 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5087 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688627
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688627 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5088 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688628
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688628 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5089 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688629
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688629 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5090 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688630
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688630 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5091 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688631
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688631 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5092 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688633
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688633 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5093 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688635
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688635 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5094 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688636
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688636 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5095 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688638
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688638 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5096 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688639
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688639 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5097 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688646
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688646 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5098 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688648
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688648 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5099 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688651
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688651 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5100 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 97.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688652
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688652 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5101 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688653
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688653 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5102 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688655
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688655 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5103 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688656
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688656 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5104 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688657
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688657 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5105 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688658
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688658 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5106 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688659
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688659 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5107 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688660
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688660 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5108 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688661
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688661 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5109 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688662
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688662 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5110 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688663
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688663 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5111 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688665
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688665 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5112 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688667
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688667 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5113 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688668
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688668 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5114 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688669
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688669 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5115 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688670
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688670 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5116 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688671
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688671 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5117 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688676
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688676 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5118 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688677
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688677 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5119 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688678
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688678 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5120 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688679
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688679 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5121 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688680
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688680 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5122 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688681
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688681 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5123 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688682
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688682 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5124 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688683
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688683 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5125 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688685
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688685 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5126 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688686
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688686 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5127 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688687
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688687 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5128 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688689
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688689 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5129 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688690
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688690 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5130 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688691
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688691 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5131 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688692
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688692 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5132 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688693
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688693 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5133 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688695
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688695 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5134 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688696
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688696 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5135 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688697
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688697 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5136 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688698
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688698 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5137 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688699
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688699 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5138 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688700
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688700 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5139 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688701
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688701 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5140 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688702
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688702 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5141 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688707
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688707 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5142 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688708
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688708 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5143 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688709
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688709 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5144 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688710
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688710 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5145 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688711
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688711 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5146 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688712
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688712 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5147 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688716
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688716 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5148 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688717
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688717 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5149 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688718
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688718 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5150 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688719
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688719 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5151 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688720
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688720 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5152 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 98.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688721
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688721 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5153 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688722
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688722 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5154 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688726
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688726 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5155 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688727
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688727 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5156 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688728
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688728 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5157 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688729
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688729 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5158 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688733
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688733 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5159 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688737
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688737 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5160 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688739
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688739 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5161 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688750
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688750 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5162 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688755
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688755 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5163 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.1% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688757
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688757 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5164 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688758
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688758 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5165 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688759
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688759 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5166 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688765
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688765 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5167 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688766
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688766 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5168 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.2% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688767
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688767 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5169 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688768
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688768 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5170 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688772
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688772 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5171 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688775
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688775 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5172 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688776
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688776 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5173 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.3% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688777
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688777 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5174 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688778
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688778 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5175 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688779
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688779 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5176 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688781
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688781 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5177 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688783
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688783 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5178 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.4% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688785
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688785 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5179 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688786
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688786 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5180 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688787
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688787 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5181 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688788
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688788 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5182 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688789
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688789 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5183 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688790
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688790 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5184 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.5% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688793
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688793 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5185 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688795
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688795 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5186 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688796
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688796 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5187 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688797
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688797 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5188 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688798
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688798 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5189 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.6% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688799
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688799 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5190 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688800
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688800 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5191 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688802
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688802 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5192 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688805
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688805 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5193 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688806
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688806 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5194 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.7% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688807
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688807 from 1990-01-01 to 2026-07-07

'NoneType' object has no attribute 'columns'

QUANTAXIS>> The 5195 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688808
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688808 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5196 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688809
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688809 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5197 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688811
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688811 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5198 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688813
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688813 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5199 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.8% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688816
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688816 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5200 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688818
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688818 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5201 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688819
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688819 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5202 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688820
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688820 from 1990-01-01 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5203 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 688981
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 688981 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> The 5204 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 99.9% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 689009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 689009 from 2025-05-23 to 2026-07-07

name 'date' is not defined

QUANTAXIS>> ERROR CODE


name 'date' is not defined

True

In [15]:
get_mainmarket_ip(ip, port)

QUANTAXIS>> Selecting the Best Server IP of TDX
QUANTAXIS>> === The BEST SERVER ===
 stock_ip shtdx.gtjas.com future_ip 112.74.214.43

USING DEFAULT STOCK IP
USING DEFAULT FUTURE IP

('shtdx.gtjas.com', 7709)

In [72]:
ip = 'shtdx.gtjas.com'
port = 7709

In [76]:
code = '000001'
frequence = 'DAY'
start_date = '2025-05-23'

In [78]:
from pytdx.hq import TdxHq_API
import datetime

In [69]:
api = TdxHq_API()

In [79]:
with api.connect(ip, port, time_out=0.7):
    if frequence in ['day', 'd', 'D', 'DAY', 'Day']:
        frequence = 9
    elif frequence in ['w', 'W', 'Week', 'week']:
        frequence = 5
    elif frequence in ['month', 'M', 'm', 'Month']:
        frequence = 6
    elif frequence in ['quarter', 'Q', 'Quarter', 'q']:
        frequence = 10
    elif frequence in ['y', 'Y', 'year', 'Year']:
        frequence = 11
    start_date = str(start_date)[0:10]
    today_ = datetime.date.today()
    lens = QA_util_get_trade_gap(start_date, today_)

    data = pd.concat([api.to_df(
        api.get_security_bars(frequence, _select_market_code(
            code), code, (int(lens / 800) - i) * 800, 800)) for i in
        range(int(lens / 800) + 1)], axis=0, sort=False)

    # 这里的问题是: 如果只取了一天的股票,而当天停牌, 那么就直接返回None了
    if len(data) < 1:
        print('no data')
#         return None
    data = data[data['open'] != 0]

    data = data.assign(
        date=data['datetime'].apply(lambda x: str(x[0:10])),
        code=str(code),
        date_stamp=data['datetime'].apply(
            lambda x: QA_util_date_stamp(str(x)[0:10]))) \
        .set_index('date', drop=False, inplace=False)

    end_date = str(end_date)[0:10]
    data = data.drop(
        ['year', 'month', 'day', 'hour', 'minute', 'datetime'],
        axis=1)[
        start_date:end_date]
#     if if_fq in ['00', 'bfq']:
#         return data
#     else:
#         print('CURRENTLY NOT SUPPORT REALTIME FUQUAN')
#         return None
        # xdxr = QA_fetch_get_stock_xdxr(code)
        # if if_fq in ['01','qfq']:
        #     return QA_data_make_qfq(data,xdxr)
        # elif if_fq in ['02','hfq']:
        #     return QA_data_make_hfq(data,xdxr)

NameError: name 'QA_util_get_trade_gap' is not defined

In [47]:
data

,open,close,high,low,vol,amount,date,code,date_stamp
date,,,,,,,,,
2025-05-23,11.55,11.46,11.60,11.43,962643.0,1.108636e+09,2025-05-23,000001,1.747930e+09
2025-05-26,11.44,11.42,11.50,11.40,699158.0,8.004957e+08,2025-05-26,000001,1.748189e+09
2025-05-27,11.45,11.49,11.54,11.42,801915.0,9.219123e+08,2025-05-27,000001,1.748275e+09
2025-05-28,11.50,11.53,11.55,11.44,658179.0,7.575713e+08,2025-05-28,000001,1.748362e+09
2025-05-29,11.52,11.46,11.55,11.45,919806.0,1.056726e+09,2025-05-29,000001,1.748448e+09
...,...,...,...,...,...,...,...,...,...
2026-06-25,10.47,10.42,10.59,10.41,1083999.0,1.136742e+09,2026-06-25,000001,1.782317e+09
2026-06-26,10.42,10.23,10.47,10.19,1236481.0,1.270903e+09,2026-06-26,000001,1.782403e+09
2026-06-29,10.22,10.24,10.32,10.02,1124139.0,1.144167e+09,2026-06-29,000001,1.782662e+09
2026-06-30,10.22,10.05,10.22,10.04,1111352.0,1.121202e+09,2026-06-30,000001,1.782749e+09
2026-07-01,10.05,10.16,10.18,9.99,906889.0,9.158385e+08,2026-07-01,000001,1.782835e+09

In [80]:
start_date = '2025-05-23'
end_date = '2026-07-01'
frequence='day'
ip=None
port=None
if_fq='00'

In [84]:
from QUANTAXIS.QAFetch.QATdx import (
    QA_fetch_get_index_day,
    QA_fetch_get_stock_day,
    QA_fetch_get_stock_list
)

In [85]:
QA_fetch_get_stock_day('000001', start_date, end_date, if_fq, frequence, ip, port)

,open,close,high,low,vol,amount,date,code,date_stamp
date,,,,,,,,,
2025-05-23,11.55,11.46,11.60,11.43,962643.0,1.108636e+09,2025-05-23,000001,1.747930e+09
2025-05-26,11.44,11.42,11.50,11.40,699158.0,8.004957e+08,2025-05-26,000001,1.748189e+09
2025-05-27,11.45,11.49,11.54,11.42,801915.0,9.219123e+08,2025-05-27,000001,1.748275e+09
2025-05-28,11.50,11.53,11.55,11.44,658179.0,7.575713e+08,2025-05-28,000001,1.748362e+09
2025-05-29,11.52,11.46,11.55,11.45,919806.0,1.056726e+09,2025-05-29,000001,1.748448e+09
...,...,...,...,...,...,...,...,...,...
2026-06-25,10.47,10.42,10.59,10.41,1083999.0,1.136742e+09,2026-06-25,000001,1.782317e+09
2026-06-26,10.42,10.23,10.47,10.19,1236481.0,1.270903e+09,2026-06-26,000001,1.782403e+09
2026-06-29,10.22,10.24,10.32,10.02,1124139.0,1.144167e+09,2026-06-29,000001,1.782662e+09
2026-06-30,10.22,10.05,10.22,10.04,1111352.0,1.121202e+09,2026-06-30,000001,1.782749e+09
2026-07-01,10.05,10.16,10.18,9.99,906889.0,9.158385e+08,2026-07-01,000001,1.782835e+09

In [48]:
QA_fetch_get_stock_day('000001', start_date, end_date, if_fq, frequence, ip, port)

,open,close,high,low,vol,amount,date,code,date_stamp
date,,,,,,,,,
2025-05-23,11.55,11.46,11.60,11.43,962643.0,1.108636e+09,2025-05-23,000001,1.747930e+09
2025-05-26,11.44,11.42,11.50,11.40,699158.0,8.004957e+08,2025-05-26,000001,1.748189e+09
2025-05-27,11.45,11.49,11.54,11.42,801915.0,9.219123e+08,2025-05-27,000001,1.748275e+09
2025-05-28,11.50,11.53,11.55,11.44,658179.0,7.575713e+08,2025-05-28,000001,1.748362e+09
2025-05-29,11.52,11.46,11.55,11.45,919806.0,1.056726e+09,2025-05-29,000001,1.748448e+09
...,...,...,...,...,...,...,...,...,...
2026-06-25,10.47,10.42,10.59,10.41,1083999.0,1.136742e+09,2026-06-25,000001,1.782317e+09
2026-06-26,10.42,10.23,10.47,10.19,1236481.0,1.270903e+09,2026-06-26,000001,1.782403e+09
2026-06-29,10.22,10.24,10.32,10.02,1124139.0,1.144167e+09,2026-06-29,000001,1.782662e+09
2026-06-30,10.22,10.05,10.22,10.04,1111352.0,1.121202e+09,2026-06-30,000001,1.782749e+09
2026-07-01,10.05,10.16,10.18,9.99,906889.0,9.158385e+08,2026-07-01,000001,1.782835e+09

In [86]:
from QUANTAXIS.QAFetch import QA_fetch_get_stock_list,QA_fetch_get_stock_day

In [92]:
import QUANTAXIS as QA

df = QA.QA_fetch_get_stock_day('tdx',
    code='000001', 
    start='2025-05-23', 
    end='2026-07-01'
)
print(df.head())

             open  close   high    low       vol        amount        date  \
date
2025-05-23  11.55  11.46  11.60  11.43  962643.0  1.108636e+09  2025-05-23
2025-05-26  11.44  11.42  11.50  11.40  699158.0  8.004957e+08  2025-05-26
2025-05-27  11.45  11.49  11.54  11.42  801915.0  9.219123e+08  2025-05-27
2025-05-28  11.50  11.53  11.55  11.44  658179.0  7.575713e+08  2025-05-28
2025-05-29  11.52  11.46  11.55  11.45  919806.0  1.056726e+09  2025-05-29

              code    date_stamp
date
2025-05-23  000001  1.747930e+09
2025-05-26  000001  1.748189e+09
2025-05-27  000001  1.748275e+09
2025-05-28  000001  1.748362e+09
2025-05-29  000001  1.748448e+09

In [94]:
from QUANTAXIS import QA_SU_save_stock_day

In [ ]:
QA_SU_save_stock_day("tdx")

<class 'module'>

QUANTAXIS>> The 0 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.0% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000001
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000001 from 2025-05-23 to 2026-07-10
QUANTAXIS>> The 1 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000002
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000002 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 2 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000004
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000004 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 3 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.05% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000006
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000006 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 4 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.07% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000007
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000007 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 5 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.09% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000008
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000008 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 6 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.11% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000009
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000009 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 7 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.13% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000010
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000010 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 8 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.15% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000011
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000011 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 9 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.17% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000012
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000012 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 10 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.19% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000014
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000014 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 11 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.21% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000016
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000016 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 12 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.23% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000017
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000017 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 13 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000019
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000019 from 2025-05-16 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 14 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000020
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000020 from 2025-05-16 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 15 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000021
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000021 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 16 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.30% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000025
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000025 from 2025-05-16 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 17 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.32% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000026
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000026 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 18 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.34% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000027
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000027 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 19 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.36% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000028
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000028 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 20 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.38% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000029
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000029 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 21 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.40% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000030
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000030 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 22 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.42% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000031
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000031 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 23 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.44% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000032
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000032 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 24 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.46% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000034
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000034 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 25 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.48% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000035
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000035 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 26 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000036
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000036 from 2025-05-16 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 27 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000037
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000037 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 28 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.53% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000039
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000039 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 29 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.55% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000042
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000042 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 30 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.57% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000045
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000045 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 31 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.59% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000048
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000048 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 32 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.61% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000049
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000049 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 33 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.63% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000050
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000050 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 34 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.65% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000055
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000055 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 35 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.67% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000056
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000056 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 36 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.69% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000058
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000058 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 37 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.71% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000059
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000059 from 2025-05-16 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 38 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.73% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000060
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000060 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 39 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.74% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000061
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000061 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 40 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.76% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000062
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000062 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 41 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.78% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000063
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000063 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 42 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.80% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000065
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000065 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 43 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.82% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000066
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000066 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 44 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.84% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000068
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000068 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 45 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.86% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000069
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000069 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 46 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.88% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000070
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000070 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 47 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.90% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000078
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000078 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 48 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.92% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000088
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000088 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 49 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.94% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000089
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000089 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 50 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.96% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000090
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000090 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 51 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.97% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000096
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000096 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 52 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 0.99% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000099
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000099 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 53 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.01% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000100
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000100 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 54 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.03% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000151
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000151 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 55 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.05% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000153
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000153 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 56 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.07% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000155
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000155 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 57 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.09% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000156
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000156 from 2025-05-16 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 58 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.11% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000157
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000157 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 59 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.13% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000158
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000158 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 60 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.15% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000159
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000159 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 61 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.17% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000166
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000166 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 62 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.19% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000301
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000301 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 63 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.21% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000333
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000333 from 2025-05-16 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 64 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.22% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000338
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000338 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 65 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.24% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000400
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000400 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 66 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.26% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000401
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000401 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 67 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.28% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000402
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000402 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 68 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.30% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000403
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000403 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 69 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.32% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000404
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000404 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 70 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.34% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000407
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000407 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 71 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.36% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000408
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000408 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 72 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.38% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000409
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000409 from 2025-05-16 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 73 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.40% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000410
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000410 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 74 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.42% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000411
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000411 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 75 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.44% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000415
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000415 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 76 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.46% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000417
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000417 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 77 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.47% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000419
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000419 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 78 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.49% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000420
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000420 from 2025-05-23 to 2026-07-10

name 'date' is not defined

QUANTAXIS>> The 79 of Total 5205
QUANTAXIS>> DOWNLOAD PROGRESS 1.51% None
QUANTAXIS>> ##JOB01 Now Saving STOCK_DAY==== 000421
QUANTAXIS>> UPDATE_STOCK_DAY
 Trying updating 000421 from 2025-05-16 to 2026-07-10